### ISSUE TITLE
validation.tsv not present in qrels folder

### ISSUE THREAD

**Issue by regstuff** [embeddings-benchmark/mteb#100]
Hi
I'm  trying to run the below code on Colab
```
from mteb import MTEB
from sentence_transformers import SentenceTransformer
from mteb.tasks import QuoraRetrieval


model_name = "average_word_embeddings_komninos"
model = SentenceTransformer(model_name)

evaluation = MTEB(tasks=["QuoraRetrieval"]) # Only select clustering and retrieval tasks
results = evaluation.run(model, output_folder=f"results/{model_name}")
```
I get the following error
```
Retrieval
    - QuoraRetrieval, beir, s2s

ERROR:mteb.evaluation.MTEB:Error while evaluating QuoraRetrieval: File /root/.cache/huggingface/datasets/BeIR/quora/qrels/validation.tsv not present! Please provide accurate file.
ERROR:mteb.evaluation.MTEB:Please check all the error logs at: error_logs.txt
```
When I check the qrels folder, I only find dev and test tsvs. This issue occurs for other tasks as well, such as MSMARCO.
Any idea what I'm doing wrong?

**Comment by Muennighoff** [comment]
I've just fixed it - you can upgrade via `pip install --upgrade git+https://github.com/embeddings-benchmark/mteb.git`
If you're only interested in evaling on the test split, it also works with your current version by specifying the split:
```python
from mteb import MTEB
from sentence_transformers import SentenceTransformer
from mteb.tasks import QuoraRetrieval


model_name = "average_word_embeddings_komninos"
model = SentenceTransformer(model_name)

evaluation = MTEB(tasks=["QuoraRetrieval"])
# Only select clustering and retrieval tasks
results = evaluation.run(model, output_folder=f"results/{model_name}", eval_splits=["test"])
```

The problem was that there's a different split name when using the old BEIR loader (dev vs validation) - This should be fixed soon when we switch back to the new BEIR HF Data Loader cc @NouamaneTazi

**Comment by regstuff** [comment]
Got a new error. 
`ERROR:mteb.evaluation.MTEB:Error while evaluating QuoraRetrieval: Retrieval tasks require beir package. Please install it with `pip install mteb[beir]`
`
I had this error earlier as well, but pip install from pypi with mteb[beir] solved it. Not sure how to do the same with a git repo install

**Comment by Muennighoff** [comment]
You can just do 
```
pip install --upgrade git+https://github.com/embeddings-benchmark/mteb.git
pip install beir
```

**Comment by regstuff** [comment]
Hi,
Sorry to reopen but ran into another issue with the SGPT models.
Running this:
```
from mteb import MTEB
from sentence_transformers import SentenceTransformer
from mteb.tasks import QuoraRetrieval

model_name = "Muennighoff/SGPT-125M-weightedmean-msmarco-specb-bitfit"
model = SentenceTransformer(model_name)
evaluation = MTEB(tasks=['ArguAna'])
results = evaluation.run(model, output_folder=f"results/{model_name}", eval_splits=["test"])
```
Throws this error: `TypeError: __init__() got an unexpected keyword argument 'pooling_mode_weightedmean_tokens
`
Am I doing something wrong when it comes to SGPT models?

**Comment by Muennighoff** [comment]
I think you need to run `pip install --upgrade git+https://github.com/Muennighoff/sentence-transformers.git@sgpt_poolings_specb` or `pip install --upgrade git+https://github.com/UKPLab/sentence-transformers.git` depending on if you need to use the original sentence transformers or not.

See [here](https://github.com/Muennighoff/sgpt#asymmetric-semantic-search-be-st) & this issue: https://github.com/Muennighoff/sgpt/issues/14

**Comment by regstuff** [comment]
Thank
