### ISSUE TITLE
Paper Writing: Introduction [only missing final revisions]

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1004]
I did a rewrite/correction/update of the introduction.

@mariyahendriksen and @imenelydiaker: Do you guys have time to take a look at the introduction?

**Comment by mariyahendriksen** [comment]
I reviewed the introduction, let me know if you want me to do another pass over it again or focus on something else!

**Comment by mariyahendriksen** [comment]
finally done with it! went over the intro one more time, proposed some changes and incorporated the low resource double bind argument in it. Let me know what you think!

**Comment by KennethEnevoldsen** [comment]
Thanks @mariyahendriksen took a look at the changes. Most seem very nice. Will close this section for now

**Comment by KennethEnevoldsen** [comment]
@mariyahendriksen you have done quite large edits where it is very hard to see what has been done and why. For instance, an entire table was removed. 

I am very thankful for your help with edits, truly am, but please refrain from large rewrites without a comment or similar explaining why.

**Comment by mariyahendriksen** [comment]
thanks for pointing it out! Apologies for a large rewrite, my internet was unstable so I was working on the draft offline.
could you tell me which table is missing? I will try to bring it back to life asap

**Comment by KennethEnevoldsen** [comment]
Found it, no worries - I have brought it back to life ;) 

I really appreciated the rewrites though, and would have loved it if Overleaf had a better interface for displaying large rewrites - sadly that influences the usefulness of large edits
