### ISSUE TITLE
Paper Writing: Speeding up the benchmark [waiting for retrieval]

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1007]
This is still waiting for the retrieval part currently being worked on by @orionw - @orionw whenever you have the time will you give this second a pass notably adding the retrieval section and making sure that it all reads nicely.

(@isaac-chung adding you in here as well)

Edit: I did polish the section. Especially on the code optimization part

**Comment by isaac-chung** [comment]
Going through section for grammar etc during this pass.

**Comment by KennethEnevoldsen** [comment]
Thanks @isaac-chung, the changes were great, have gone through and accepted almost all of them. There is one section where the bridge seems a bit odd. It seems like it is due to some stuff being moved around. Could I ask you to have an extra look at that segment?

**Comment by isaac-chung** [comment]
@KennethEnevoldsen added the bridges as well 👍 .

**Comment by KennethEnevoldsen** [comment]
@wissam-sib - regarding the speedup of bitext and data loading it seems a bit thin atm. I was hoping I could get you to take a look at that section if you have the time?

**Comment by KennethEnevoldsen** [comment]
If you have the time this or the following week it would be great - does that work for you?

**Comment by wissam-sib** [comment]
That works, I'll start looking into this tomorrow

**Comment by isaac-chung** [comment]
Closing this as the first submission is completed.
