### ISSUE TITLE
Paper writing: Authors + appendix author contributions [needs review]

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1009]
@imenelydiaker I was planning to take a look at creating this - However you mentioned changing the format to TACL. Should I wait with this section until then?

Edit: Added an outline for the appendix. @imenelydiaker can I ask you to skim it through.

**Comment by KennethEnevoldsen** [comment]
I have added an outline to the author section in the appendix @imenelydiaker when you have the time will you check that it looks ok?

**Comment by imenelydiaker** [comment]
> I have added an outline to the author section in the appendix @imenelydiaker when you have the time will you check that it looks ok?

Yes I'll be giving the paper a full read 🙂. Thanks!
