### ISSUE TITLE
Change CPU default for E5 instruct

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1021]
E5 instruct defaults to running on CPU which cannot be easily changed by the user afaict: https://github.com/embeddings-benchmark/mteb/blob/1d1f7aadc71b89444837ea59bd142107789f648a/mteb/models/e5_instruct.py#L44

Maybe either
(a) making it configurable
(b) automatically moving to GPU if available like with GritLM: https://github.com/ContextualAI/gritlm/blob/0cc9aeab83b90f2e22bcdd2b084d51507c624d95/gritlm/gritlm.py#L50

**Comment by KennethEnevoldsen** [comment]
should the mteb run --device flag change it?

**Comment by Muennighoff** [comment]
I think autodetect suffices for now? If people ever do not want to use GPUs despite them being available they can just set `CUDA_VISIBLE_DEVICES=""` and it won't use the GPUs.

**Comment by KennethEnevoldsen** [comment]
Yea thinks that works as well
