### ISSUE TITLE
TenKGnadClusteringS2S.v2 sample size error

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1023]
mteb run -m sentence-transformers/all-MiniLM-L6-v2 -t TenKGnadClusteringS2S.v2

INFO:mteb.cli:Running with parameters: Namespace(model='sentence-transformers/all-MiniLM-L6-v2', task_types=None, categories=None, tasks=['TenKGnadClusteringS2S.v2'], languages=None, device=None, output_folder='results', verbosity=2, co2_tracker=False, eval_splits=None, model_revision=None, overwrite=False, func=<function run at 0x7f984f573010>)
/env/lib/conda/gritkto/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
INFO:mteb.evaluation.MTEB:

## Evaluating 1 tasks:
────────────────────────────────────────── Selected tasks  ───────────────────────────────────────────
Clustering
    - TenKGnadClusteringS2S.v2, s2s

INFO:mteb.evaluation.MTEB:

********************** Evaluating TenKGnadClusteringS2S.v2 **********************
INFO:mteb.evaluation.MTEB:Loading dataset for TenKGnadClusteringS2S.v2
INFO:mteb.abstasks.AbsTask:
Task: TenKGnadClusteringS2S.v2, split: test, subset: default. Running...
ERROR:mteb.evaluation.MTEB:Error while evaluating TenKGnadClusteringS2S.v2: Sample larger than population or is negative

Traceback (most recent call last):
  File "/env/lib/conda/gritkto/bin/mteb", line 8, in <module>
    sys.exit(main())
  File "/data/niklas/mteb/mteb/cli.py", line 370, in main
    args.func(args)
  File "/data/niklas/mteb/mteb/cli.py", line 118, in run
    eval.run(
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 388, in run
    raise e
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 354, in run
    results, tick, tock = self._run_eval(
  File "/data/niklas/mteb/mteb/evaluation/MTEB.py", line 251, in _run_eval
    results = task.evaluate(model, split, output_folder=output_folder, **kwargs)
  File "/data/niklas/mteb/mteb/abstasks/AbsTask.py", line 115, in evaluate
    scores[hf_subset] = self._evaluate_subset(model, data_split, **kwargs)
  File "/data/niklas/mteb/mteb/abstasks/AbsTaskClusteringFast.py", line 142, in _evaluate_subset
    example_indices = rng_state.sample(
  File "/env/lib/conda/gritkto/lib/python3.10/random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by KennethEnevoldsen** [comment]
#1014

**Comment by KennethEnevoldsen** [comment]
fix in #1026
