### ISSUE TITLE
Status of multi-gpu support for BEIR evaluation

### ISSUE THREAD

**Issue by PanicButtonPressed** [embeddings-benchmark/mteb#103]
It looks like the multi-gpu support for the BEIR benchmarks is still disabled as of https://github.com/embeddings-benchmark/mteb/releases/tag/1.0.1.

What is the current status of it? Is it actively developed in BEIR repo?

Btw. we are successful in running the multi gpu utils in the BEIR repository with downgraded dependencies but would like to switch over to MTEB to have a broader benchmark collection.

**Comment by Muennighoff** [comment]
It's actively developed - a few things:
- BEIR needs to release a new version, as there has been an important bug fix in their multi-gpu support on this branch https://github.com/beir-cellar/beir/tree/development (cc @thakur-nandan)
- @NouamaneTazi is working on extending multi-GPU support to all other MTEB tasks as well

Hopefully, we can have it done in the next few weeks!

**Comment by izhx** [comment]
I have a wrapper class that fits to all tasks (probably).
https://github.com/izhx/mteb/blob/feat/mult-gpu-wrapper-script/scripts/run_mteb_en_multi_gpu.py

**Comment by lixsh6** [comment]
Any progress of this issue?

**Comment by Muennighoff** [comment]
I think @NouamaneTazi is looking into it - Maybe he can give us a timeline?
