### ISSUE TITLE
Standardize scores structure for tasks

### ISSUE THREAD

**Issue by Samoed** [embeddings-benchmark/mteb#1037]
I've created a PR https://github.com/embeddings-benchmark/mteb/pull/1034 to address an issue where `main_score` was not consistently appearing in the scores "at top level", particularly affecting `PairClassification` and `Reranking` tasks (e.g., see the [TERRa results](https://github.com/embeddings-benchmark/mteb/blob/main/results/sergeyzh__rubert-tiny-turbo/8ce0cf757446ce9bb2d5f5a4ac8103c7a1049054/TERRa.json)). I propose changing the structure from:

```json
"cosine": {
  "accuracy": 0.5960912052117264,
  "ap": 0.5608760299515377
  // other metrics
}
```

to:

```json
"cosine_accuracy": 0.5960912052117264,
"cosine_ap": 0.5608760299515377
// other metrics similarly structured
```

This approach aligns with what was previously done with STS metrics and may provide clearer and more consistent results across different tasks.

----

edit by @KennethEnevoldsen: 
This would notably lead to breaking changes in the "ap" (which is "max_ap") scores for PairClassification and similarly for reranking. A solution for backward compatibility is to set "max_ap" -> "ap".

**Comment by KennethEnevoldsen** [comment]
@Muennighoff, @orionw tagging you here as you are probably the most familiar with how/if this will cause issues in the leaderboard?

**Comment by Muennighoff** [comment]
I'm fine with this change as it's more consistent with the changes that @KennethEnevoldsen made to the STS scores I think, no?

In the leaderboard I fixed backward compat by adding the legacy names here: https://huggingface.co/spaces/mteb/leaderboard/blob/main/app.py#L27

**Comment by KennethEnevoldsen** [comment]
I believe this issue is resolved - will close it for now, but if I am missing anything let me know
