### ISSUE TITLE
Error while evaluating MassiveIntentClassification: 'en'

### ISSUE THREAD

**Issue by westonli-thu** [embeddings-benchmark/mteb#1045]
Hi, I run the mteb (with 1.12.5) and got an error when evaluation:

```
File "/usr/local/lib/python3.10/dist-packages/mteb/abstasks/MultiSubsetLoader.py", line 14, in load_data
    self.fast_load()
  File "/usr/local/lib/python3.10/dist-packages/mteb/abstasks/MultiSubsetLoader.py", line 36, in fast_load
    df_grouped[lang].drop("lang")
KeyError: 'en'
```
For my experiments in last week, this code is good to be used.

While for yesterday's experiment, for dataset before MassiveIntentClassification, it run smoothly but failed here. Is there anything happened on this dataset 'MassiveIntentClassification'?

**Comment by KennethEnevoldsen** [comment]
Using the latest version (1.12.67), it seems to run without issue:
```
import mteb
tasks = mteb.get_tasks(tasks=["MassiveIntentClassification"], languages=["eng"])
model = mteb.get_model("sentence-transformers/all-MiniLM-L6-v2")
eval = mteb.MTEB(tasks=tasks)
eval.run(model, overwrite_results=True)
```

**Comment by isaac-chung** [comment]
Closing this for now. Feel free to reopen is the issue persists after testing on version 1.12.67.
