### ISSUE TITLE
Rmv Refresh instructions?

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1073]
`Hit the Refresh button at the bottom of the leaderboard and you should see your scores` in https://github.com/embeddings-benchmark/mteb/blob/778d7a3bf85b2023cc8ba9b2c35a810dcfa5e924/docs/adding_a_model.md?plain=1 seems outdated as we removed the Refresh button. I assume we don't plan on reintroducing the button so should we adapt that md? Maybe also mention the automatic update? @orionw likely knows best!

(see: https://huggingface.co/spaces/mteb/leaderboard/discussions/134)

**Comment by orionw** [comment]
Yes, sorry! I must have missed that when doing the PR.  We should definitely remove that. If we want we can mention the automatic updates or just not mention it at all.

**Comment by Muennighoff** [comment]
Yes, I think we should mention the automatic updates!

**Comment by KennethEnevoldsen** [comment]
I have added a fix ^
