### ISSUE TITLE
example code for OpenAI Embedding model

### ISSUE THREAD

**Issue by su-park** [embeddings-benchmark/mteb#1092]
Hello.
I am currently using the MTEB package and finding it very helpful.
Would you be able to provide an example code that utilizes OpenAI's embedding model?

**Comment by KennethEnevoldsen** [comment]
Check out;

https://github.com/embeddings-benchmark/mteb/tree/main/mteb/models

for sample model implementations.

Notably 
https://github.com/embeddings-benchmark/mteb/blob/main/mteb/models/openai_models.py

provide a wrapper for the openAI models.

You can retrieve it using:

```python
import mteb

model = mteb.get_model(text-embedding-3-small)

# run on a benchmark here
```

**Comment by su-park** [comment]
I was able to solve it with the code you provided. 
I also confirmed that you provide wrappers and instructions for several known models. 
Thank you.
