### ISSUE TITLE
Does `MTEB_MAIN_EN` still correspond to the original 56 MTEB tasks? 

### ISSUE THREAD

**Issue by yiboyang** [embeddings-benchmark/mteb#1102]
The official [readme](https://github.com/embeddings-benchmark/mteb/blob/07ea6f5eb25a99e34c011a2641535dfcbe2aee3a/README.md) says:

> There are also presets available for certain task collections, e.g. to select the 56 English datasets that form the "Overall MTEB English leaderboard":
> 
> from mteb import MTEB_MAIN_EN
> evaluation = mteb.MTEB(tasks=MTEB_MAIN_EN, task_langs=["en"])

However, when I imported `MTEB_MAIN_EN` from `mteb` (version 1.12.75), `len(MTEB_MAIN_EN)` gives me 67, not 56. 
Looking at [nomic's evaluation](https://github.com/nomic-ai/contrastors/blob/0c70843dc3ed3e8d3c199bffe0fb846ad9cb732d/src/contrastors/eval/mteb_eval/eval_mteb.py), it appears they also evaluated on 67 tasks, not 56. 

Is this intended behavior? How do I get the original 56 MTEB tasks?

**Comment by yiboyang** [comment]
Never mind. It turns out the `CQADupstack` tasks are listed separately in `MTEB_MAIN_EN`, but together they are considered only 1 task.

**Comment by KennethEnevoldsen** [comment]
Glad you found the solution @yiboyang. If you use the cli `mteb --create_meta` it will also calculate the metrics for CQADupstack based on its constituent tasks.
