### ISSUE TITLE
Error running MLSUMClusteringP2P.v2

### ISSUE THREAD

**Issue by Samoed** [embeddings-benchmark/mteb#1110]
Hi! I runned MLSUMClusteringP2P.v2 and got error `TypeError: 'int' object is not iterable`. I'm not shure why this happening

Here is the code that produces the error:
```python
import mteb
from mteb.models.sentence_transformers_models import all_MiniLM_L6_v2

model = mteb.get_model(model_name=all_MiniLM_L6_v2.name, revision=all_MiniLM_L6_v2.revision)
tasks = mteb.get_tasks(tasks=["MLSUMClusteringP2P.v2"])
evaluation = mteb.MTEB(tasks)
evaluation.run(model, output_folder="results", verbosity=2, overwrite_results=True)
```
colab https://colab.research.google.com/drive/1lY4Iv0PeGjIteLwfl3RaMtwUL6Ii8hoE?usp=sharing

**Comment by KennethEnevoldsen** [comment]
Thanks for reporting this. Will take a look at this first thing tomorrow

**Comment by KennethEnevoldsen** [comment]
Hmm odd seems like it was never properly converted:
https://github.com/embeddings-benchmark/mteb/blob/b70bb5afd808b7a46094029ab07604a08fbd7356/mteb/tasks/Clustering/multilingual/MLSUMClusteringP2P.py

(cc @isaac-chung)

**Comment by KennethEnevoldsen** [comment]
@Muennighoff this means that we need to rerun this task for the MMTEB
