### ISSUE TITLE
Creating model meta for HF model

### ISSUE THREAD

**Issue by Samoed** [embeddings-benchmark/mteb#1111]
I tied to export results to model_meta, but got several errors when pushing to huggingface. 
1. `Error: "model-index[0].results[23].dataset.type" with value "CQADupstackRetrieval is a combined dataset" fails to match the required pattern: /^(?:[\w-]+\/)?[\w-.]+$/` this caused by #1079 maybe this can be renamed to `CQADupstackRetrieval_is_a_combined_dataset`
2. `Error: "model-index[0].results[102].dataset.type" with value " " fails to match the required pattern: /^(?:[\w-]+\/)?[\w-.]+$/` When I tried to export `GPUSpeedTask` and `CPUSpeedTask` this caused by `GPUSpeedTask` and `CPUSpeedTask` doesn't have path in dataset, so task if empty. Maybe this can be ignored, but I'm just warning about this problem

**Comment by KennethEnevoldsen** [comment]
Thanks for reporting this. Will take a look at this first thing tomorrow

**Comment by Samoed** [comment]
Example results with that I had problems [segeyzh_rubert_tiny.md](https://github.com/user-attachments/files/16367405/segeyzh_rubert_tiny.md)
