### ISSUE TITLE
Task Metadata Pydantic rules are too strict

### ISSUE THREAD

**Issue by nprime496** [embeddings-benchmark/mteb#1121]
Hi, wonderful package.

I am trying to run experimentations on my laptop on custom datasets but I end up spending a lot of time configuring each and every parameters of [TaskMetadata](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/abstasks/TaskMetadata.py#L138). It feels too constrained and I end up forced to add meaningless values that bite my later.

For example, I'd like to fetch multiple datasets but I HAVE TO put a revision string for each which makes the ordeal very cumbersome.

I am not using classic datasets but custom ones so being able to just put `None` for most of these parameters would be really helpful.

Any plans adding a `bypass_verification` for Pydantic ??

**Comment by KennethEnevoldsen** [comment]
So, having strong validation for the TaskMetadata ensures high-quality documentation for mteb. E.g. for revision, we do require the revision id for reproducibility. We will not remove this requirement.

However, during the development of tasks, I understand entirely that this restriction can be frustrating. 
A solution might be to subclass the metadata. Something like this should work for you:

```python
class TaskMetadataNoValidation(TaskMetadata):
    """Metadata for a task with minimal validation and naive defaults"""

    dataset: dict

    name: str
    description: str = ""
    type: TASK_TYPE | None = None
    modalities: list[Literal["text"]] = ["text"]
    category: TASK_CATEGORY | None = None
    reference: STR_URL | None = None
    eval_splits: list[str] = ["test"]
    eval_langs: LANGUAGES
    main_score: str
    date: tuple[STR_DATE, STR_DATE] | None  = None
    domains: list[TASK_DOMAIN] | None = None
    task_subtypes: list[TASK_SUBTYPE] | None = None
    license: str | None = None
    annotations_creators: ANNOTATOR_TYPE | None = None 
    dialect: list[str] | None = None
    sample_creation: SAMPLE_CREATION_METHOD | None = None
    bibtex_citation: str | None = None

    descriptive_stats: dict[METRIC_NAME, Optional[dict[SPLIT_NAME, METRIC_VALUE]]] = {}

    # overwrite validators
    @field_validator("dataset")
    def _check_dataset_path_is_specified(cls, dataset):
        return dataset

    @field_validator("dataset")
    def _check_dataset_revision_is_specified(cls, dataset):
        return dataset

    @field_validator("eval_langs")
    def _check_eval_langs(cls, eval_langs):
        return eval_langs
```

**Comment by KennethEnevoldsen** [comment]
I would much prefer not to have multiple TaskMetadata objects to maintain.

A solution is to set `None` as the default for many of the fields (as seen above) but have the tests fail if they are not filled out. That way we ensure the quality on mteb while allowing flexibility on user side. Would that work for you?

**Comment by KennethEnevoldsen** [comment]
Will just check with @imenelydiaker and @isaac-chung to make sure that they agree as well

**Comment by KennethEnevoldsen** [comment]
@nprime496 on the note on revision I believe you can specify revision="main".
