### ISSUE TITLE
Allow Evaluation should return results from cached runs instead of skipping them 

### ISSUE THREAD

**Issue by nprime496** [embeddings-benchmark/mteb#1122]
The evaluation [do not run tasks twice](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/evaluation/MTEB.py#L334), that is smart as it saves ressources but why is the task deleted ??

I am using the python SDK and spent several minutes wondering why my code didn't work anymore (do not return any result) and that was the culprit.

I'd thought that the package should use already cached results instead of just not returning anything.

Any design justification ? Is it a bug ?

**Comment by KennethEnevoldsen** [comment]
So, if I understand correctly:

```
tasks = mteb.get_tasks(tasks=["sometask"])
eval = mteb.MTEB(tasks=tasks)
results = eval.run(my_model)

len(results) # should be 1

# if we rerun it:
results = eval.run(my_model) 
len(results) # is 0, but probably should be 1
```

I wouldn't say it is a bug, but it is definitely something that should be updated. If you have the time, feel free to submit a PR; otherwise, I have marked it as an open issue for contributors as I can't promise to have a look at it until after August.
