### ISSUE TITLE
QuoraRetrieval Task Issue

### ISSUE THREAD

**Issue by MythicalCow** [embeddings-benchmark/mteb#1138]
QuoraRetrieval seems to have been running properly until today. Some issue with the metadata block: "Repo card metadata block was not found. Setting CardData to empty"

**Comment by KennethEnevoldsen** [comment]
@MythicalCow, there shouldn't have been made any changes to the dataset "QuoraRetrieval" and running the code:

```
import mteb
tasks = mteb.get_tasks(tasks=["QuoraRetrieval"])
task = tasks[0]
task.load_data()
```

work without any issues. It might be that you need to reset your huggingface cache? It is pertains, do add an example then I would love to take a second look at it

**Comment by MythicalCow** [comment]
@KennethEnevoldsen Here is the code snippet
evaluation = MTEB(tasks=["QuoraRetrieval"], languages=["eng"])
eval_split = "test"
results = evaluation.run(l1, output_folder=f"results/large1_{eval_split}", eval_splits=[eval_split])
for result in results:
  print(result.scores[eval_split][0]['main_score'])

**Comment by MythicalCow** [comment]
I will try the huggingface cache reset as well. Thanks for the suggestion!

**Comment by MythicalCow** [comment]
One interesting thing is that other datasets like DBPedia seem to be working

**Comment by KennethEnevoldsen** [comment]
rewrote the code for testing and it seems to work just fine.

```python
tasks = mteb.get_tasks(tasks=["QuoraRetrieval"], languages=["eng"]) # note the change: recommended syntax
model = mteb.get_model("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
evaluation = mteb.MTEB(tasks=tasks)
results = evaluation.run(model, output_folder=f"tmp", eval_splits=["test"])
results
# [MTEBResults(task_name=QuoraRetrieval, scores=...)]
```
