### ISSUE TITLE
Sequence Length

### ISSUE THREAD

**Issue by gsaivinay** [embeddings-benchmark/mteb#114]
Hello,

Thanks for this extensive work.

I've question about the sequence length of the various models used for this benchmark. Different models supports different sequence lengths, like text-embedding-ada upto 8191 tokens, while instructor-xl trained only with 512 max token length. Are these considered during evaluation?

Please forgive if I'm being ignorant.

**Comment by Muennighoff** [comment]
Hey yes for the official evaluation they are i.e. ada was evaluated with its full seq length; I'm not sure about instructor-xl but u can probs ask here: https://huggingface.co/hkunlp/instructor-xl
