### ISSUE TITLE
Clustering German Text

### ISSUE THREAD

**Issue by slvnwhrl** [embeddings-benchmark/mteb#115]
Hi,
so, first of all, thank you for this great work!

I am particularly interested in clustering. As I am mostly working with German text, I have been working on a German clustering benchmark based on MTEB (as MTEB only includes English). The datasets I created use open-source data and follow MTEB task design (e.g. number of splits, different text lengths). I have already evaluated quite a lot of models. 

You can find it here: [German Text Embedding Clustering Benchmark](https://github.com/ClimSocAna/tecb-de)

I was wondering if there would be any interest to officially include these datasets as part of MTEB? Let me know what you think and if you have any questions :)

**Comment by Muennighoff** [comment]
> Hi, so, first of all, thank you for this great work!
> 
> I am particularly interested in clustering. As I am mostly working with German text, I have been working on a German clustering benchmark based on MTEB (as MTEB only includes English). The datasets I created use open-source data and follow MTEB task design (e.g. number of splits, different text lengths). I have already evaluated quite a lot of models.
> 
> You can find it here: [German Text Embedding Clustering Benchmark](https://github.com/ClimSocAna/tecb-de)
> 
> I was wondering if there would be any interest to officially include these datasets as part of MTEB? Let me know what you think and if you have any questions :)

Hey! That looks amazing, really cool work!
I think it would be great to have them included - the main things to do would be:

- Add the code with the task configurations; possibly the changes I think you made to the evaluators; adapt the README (If you want to do a PR that would be amazing!)
- Add them to the leaderboard (I can adapt the leaderboard code to fetch them & will add a new German tab to Clustering)
- Upload the results (If you benchmarked models where you cannot change the README files, we can just add those with the result files here: https://huggingface.co/datasets/mteb/results)

This is exciting - Let me know wherever I can be of help!

**Comment by slvnwhrl** [comment]
> > Hi, so, first of all, thank you for this great work!
> > I am particularly interested in clustering. As I am mostly working with German text, I have been working on a German clustering benchmark based on MTEB (as MTEB only includes English). The datasets I created use open-source data and follow MTEB task design (e.g. number of splits, different text lengths). I have already evaluated quite a lot of models.
> > You can find it here: [German Text Embedding Clustering Benchmark](https://github.com/ClimSocAna/tecb-de)
> > I was wondering if there would be any interest to officially include these datasets as part of MTEB? Let me know what you think and if you have any questions :)
> 
> Hey! That looks amazing, really cool work! I think it would be great to have them included - the main things to do would be:
> 
> * Add the code with the task configurations; possibly the changes I think you made to the evaluators; adapt the README (If you want to do a PR that would be amazing!)
> * Add them to the leaderboard (I can adapt the leaderboard code to fetch them & will add a new German tab to Clustering)
> * Upload the results (If you benchmarked models where you cannot change the README files, we can just add those with the result files here: https://huggingface.co/datasets/mteb/results)
> 
> This is exciting - Let me know wherever I can be of help!

That sounds great! :-) I am happy to open a PR (I am a bit busy right now so I will do it in the next days).

And yes, I also adapted the Evaluator class so it's possible to evaluate with different clustering algorithms. But I think it makes more sense to just include the datasets in MTEB otherwise it might complicate the evalaution. If you feel different, I am happy to contribute more. Anyway, I'll make a suggestion in the PR if that's alright.

**Comment by Muennighoff** [comment]
> > > Hi, so, first of all, thank you for this great work!
> > > I am particularly interested in clustering. As I am mostly working with German text, I have been working on a German clustering benchmark based on MTEB (as MTEB only includes English). The datasets I created use open-source data and follow MTEB task design (e.g. number of splits, different text lengths). I have already evaluated quite a lot of models.
> > > You can find it here: [German Text Embedding Clustering Benchmark](https://github.com/ClimSocAna/tecb-de)
> > > I was wondering if there would be any interest to officially include these datasets as part of MTEB? Let me know what you think and if you have any questions :)
> > 
> > 
> > Hey! That looks amazing, really cool work! I think it would be great to have them included - the main things to do would be:
> > 
> > * Add the code with the task configurations; possibly the changes I think you made to the evaluators; adapt the README (If you want to do a PR that would be amazing!)
> > * Add them to the leaderboard (I can adapt the leaderboard code to fetch them & will add a new German tab to Clustering)
> > * Upload the results (If you benchmarked models where you cannot change the README files, we can just add those with the result files here: https://huggingface.co/datasets/mteb/results)
> > 
> > This is exciting - Let me know wherever I can be of help!
> 
> That sounds great! :-) I am happy to open a PR (I am a bit busy right now so I will do it in the next days).
> 
> And yes, I also adapted the Evaluator class so it's possible to evaluate with different clustering algorithms. But I think it makes more sense to just include the datasets in MTEB otherwise it might complicate the evalaution. If you feel different, I am happy to contribute more. Anyway, I'll make a suggestion in the PR if that's alright.

Sounds good!

**Comment by slvnwhrl** [comment]
Solved by merged PR #116
