### ISSUE TITLE
Standardize license in task metadata

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1165]
Atm. we have multiple license which are equivalent but specified differently "mit" vs "MIT", are practically unknown ("Other (Commercial)"), custom licenses (typically specified as a link or some text), not specified by the dataset ("unknown", "Not specified", "Not Specified",... ) and not specified by us (None).

We can standardize the following:

- Use a predefined list of licenses to standardize spelling variations
- Use links for custom licenses
- Use "Not specified" for cases where the license is unknown (but we have checked)
- Use None in cases where we haven't checked the license

**Comment by harsha-mangena** [comment]
@KennethEnevoldsen, Can I pick up this issue?

**Comment by KennethEnevoldsen** [comment]
That would be great! Be sure to start from #1166 (it adds quite a few fixes to the metadata).
