### ISSUE TITLE
Add updated Touche-2020

### ISSUE THREAD

**Issue by orionw** [embeddings-benchmark/mteb#1170]
A great paper from Thakur et. al. 2024 at SIGIR: https://arxiv.org/abs/2407.07790 Has some nice improvements to Touche-2020 as a test collection.

**Comment by Samoed** [comment]
FYI, I have issues with dataset downloading https://huggingface.co/datasets/castorini/webis-touche2020-v3/discussions/1

**Comment by Samoed** [comment]
FYI, I have problems with dataset downloading https://huggingface.co/datasets/castorini/webis-touche2020-v3/discussions/1

**Comment by orionw** [comment]
Thanks for looking at this! Did you resolve the error? Looks like we could re-create it but drop the `metadata` field from the queries and it would work.

**Comment by Samoed** [comment]
I downloaded `queries.json` and added them to dataset as json. I think I couldn't download it becuase metadata in their repository broken

**Comment by orionw** [comment]
So just to clarify it is working? Thanks for handling that!

**Comment by Samoed** [comment]
Yes, It's working if download from `mteb/webis-touche2020-v3`

**Comment by isaac-chung** [comment]
Closing as PR is merged.
