### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by XIANYUNYEHE-DEL** [embeddings-benchmark/mteb#1176]
Looks like I'm having some internet problems. Is it possible to download the dataset ahead of time and load it locally, and if so is there an example for that ?

**Comment by KennethEnevoldsen** [comment]
There is no support for this behavior within `mteb`. However, we use Huggingface's [datasets](https://huggingface.co/docs/datasets/index) for loading datasets with. I believe you can do:

```
task.load_data() # load dataset

# new sessions without internet
task.load_data() # loads datasets from cache 
```

This is not a 100% consistent behaviour though as e.g. some of the datasets utilize a script when downloading. If you find that it works for some but not others, it might be worth looking into if it is possible to reformat the data to enable local caching.

**Comment by isaac-chung** [comment]
As this is more on the `datasets` side, I'm closing this issue.
