### ISSUE TITLE
[paper writing]: code in appendix is very low resolution

### ISSUE THREAD

**Issue by SaitejaUtpala** [embeddings-benchmark/mteb#1183]
![image](https://github.com/user-attachments/assets/9b083f3b-6038-4255-a852-7de6c446ec16)

should we codelisting to inline the code instead of a screenshot. I can help with this 

@KennethEnevoldsen

**Comment by KennethEnevoldsen** [comment]
That would be great if you wanted to do that @SaitejaUtpala

**Comment by SaitejaUtpala** [comment]
![image](https://github.com/user-attachments/assets/eeac14fa-1ddb-41f4-b49f-5c4ae7da78c8)


Done. Can you please take a look, let me know if have any comments? @KennethEnevoldsen

**Comment by asparius** [comment]
@Muennighoff name is also missing in the author list. @KennethEnevoldsen

**Comment by KennethEnevoldsen** [comment]
@SaitejaUtpala this looks great! Just removed the `List[ModelMeta]` etc. for clarity. I have accepted your changes in the paper!


> That is indeed a mistake @Muennighoff name is also missing in the author list unless it is intentional. 

Thanks for noticing @asparius. I have added him in #1188
