### ISSUE TITLE
Running all languages even when only one is specified

### ISSUE THREAD

**Issue by afurkank** [embeddings-benchmark/mteb#119]
Hi,

I'm trying to evaluate models under Sentence_Transformers library (https://huggingface.co/sentence-transformers?sort_models=downloads#models) with the following code:

```
from mteb import MTEB
from mteb.tasks import STS22CrosslingualSTS
from sentence_transformers import SentenceTransformer

model_name = 'xlm-r-100langs-bert-base-nli-stsb-mean-tokens'

model = SentenceTransformer(model_name)

evaluation = MTEB(tasks=[STS22CrosslingualSTS()], task_langs=['tr'])

evaluation.run(model, eval_splits=["test"], output_folder=f"results/{model_name}")
```

I'm using the STS22 dataset with the Turkish language. However, it still evaluates the model with all the languages.

How can I make sure the evaluation is only done for Turkish?

**Comment by Muennighoff** [comment]
In that case you should do:
```python
from mteb import MTEB
from mteb.tasks import STS22CrosslingualSTS
from sentence_transformers import SentenceTransformer

model_name = 'xlm-r-100langs-bert-base-nli-stsb-mean-tokens'

model = SentenceTransformer(model_name)

evaluation = MTEB(tasks=[STS22CrosslingualSTS(langs=['tr'])

evaluation.run(model, eval_splits=["test"], output_folder=f"results/{model_name}")
```

Sorry for the confusion. `task_langs` will select all languages of any task that has that language. Meanwhile, feeding langs directly is the way to limit the languages of a certain task.
This can definitely improved in terms of usability!

**Comment by Muennighoff** [comment]
Had a quick look and to fix this, we could reinitialize the task with the correct languages somewhere in [this if](https://github.com/embeddings-benchmark/mteb/blob/582553693de507f338a720a0bc572147b8c6ef33/mteb/evaluation/MTEB.py#L145), but then `STS22CrosslingualSTS(langs=['tr'])` would no longer work.

Hence would leave the code as is for now

**Comment by afurkank** [comment]
`evaluation = MTEB(tasks=[STS22CrosslingualSTS(langs=['tr'])`

This works for now.

Thanks a lot!
