### ISSUE TITLE
CrossEncoder object has no attribute model_card_data

### ISSUE THREAD

**Issue by isaac-chung** [embeddings-benchmark/mteb#1192]
https://github.com/embeddings-benchmark/mteb/pull/1186#discussion_r1740181063

> Getting WARNING:mteb.models:Failed to extract metadata from model: 'CrossEncoder' object has no attribute 'model_card_data'. Upgrading to sentence-transformers v3.0.0 or above is recommended. even though I'm using the below

on the following snippet:

```python
from mteb import MTEB
import mteb
from sentence_transformers import CrossEncoder, SentenceTransformer

cross_encoder = CrossEncoder("cross-encoder/ms-marco-TinyBERT-L-2-v2")
dual_encoder = SentenceTransformer("all-MiniLM-L6-v2")

tasks = mteb.get_tasks(tasks=["NFCorpus"], languages=["eng"])

subset = "default" # subset name used in the NFCorpus dataset
eval_splits = ["test"]

evaluation = MTEB(tasks=tasks)
evaluation.run(
    dual_encoder,
    eval_splits=eval_splits,
    save_predictions=True,
    output_folder="results/stage1",
)
evaluation.run(
    cross_encoder,
    eval_splits=eval_splits,
    top_k=5,
    save_predictions=True,
    output_folder="results/stage2",
    previous_results=f"results/stage1/NFCorpus_{subset}_predictions.json",
)
```

**Comment by x-tabdeveloping** [comment]
@isaac-chung Just for future reference, I ended up talking to [Tom about this](https://github.com/UKPLab/sentence-transformers/issues/3009) and he said that `model_card_data` will probably be implemented for CrossEncoders in a couple of months.
