### ISSUE TITLE
Sequence Length information in the leaderboard

### ISSUE THREAD

**Issue by sanjeev-kumar-4** [embeddings-benchmark/mteb#1202]
Hi,

Thanks for this leaderboard which is so so useful.

I just wanted to check if we already have max_sequence_length information for each model on the leaderboard? I tried looking for it on the leaderboard and in the issues section of this repo but could not locate it.

It could be very helpful if along with model size, we also display the max_seq_len for each model.

Thanks

**Comment by KennethEnevoldsen** [comment]
Def. agree @sanjeev-kumar-4. I have marked it as a potential contribution for new contributors.

**Comment by sanjeev-kumar-4** [comment]
I could possibly take it up if that works.

**Comment by KennethEnevoldsen** [comment]
That would be great if you have the time: Leaderboard code is located [here](https://github.com/embeddings-benchmark/leaderboard).

**Comment by Samoed** [comment]
In the overall tab, models have a `max tokens` field, which corresponds to `max_seq_len`, but the other tabs don't include this information

**Comment by san7988** [comment]
Yes, correct. Somehow I missed it, probably I was looking for keywords like max_seq_len or similar 😶. 
Anyways, I'll work on updating all the tables and submit a PR soon.

**Comment by sanjeev-kumar-4** [comment]
Hi. Should I open an issue in the 'leaderboard' repo and submit the PR over there?
Or should I just submit the PR and link it here?

**Comment by KennethEnevoldsen** [comment]
Either is fine - but let us just keep the discussion here (no need to have duplicates)

**Comment by sanjeev-kumar-4** [comment]
Created the PR https://github.com/embeddings-benchmark/leaderboard/pull/28
Please let me know if this looks fine.

**Comment by sanjeev-kumar-4** [comment]
One more question: I think I should also commit the latest task and board data(residing in `all_data_task` and `boards_data` folder. Is my understanding correct? Or is there some auto refresh that happens?
Please note that I have not pushed the updated data files yet.

**Comment by KennethEnevoldsen** [comment]
Let us move the discussion to the PR :)

**Comment by KennethEnevoldsen** [comment]
Thanks for the PR! Greatly appreciated
