### ISSUE TITLE
BUG: if the model defines a similarity score, STS pearson and spearman are written as arrays, not as scores.

### ISSUE THREAD

**Issue by stephantul** [embeddings-benchmark/mteb#1206]
Hello!

In `mteb==1.14.15`, if a model does not define a similarity score, the `STSEvaluator` writes arrays of length two, the first item of which is the score, and the second of which is the significance score. If, however, the model does _not_ define a similarity, the `STSEvaluator` writes a single score, the correlation score itself. Only the second is consistent with how the rest of MTEB works.

The discrepancy between these two is probably the result of a bug [this line](https://github.com/embeddings-benchmark/mteb/blob/16b222019c595aea7cdbbb04b506736851c6316b/mteb/evaluation/evaluators/STSEvaluator.py#L80). A couple of lines above, the pearson score is defined as:

```python
cosine_pearson, _ = pearsonr(self.gold_scores, cosine_scores)
```

While on this line, it is defined as:

```python
pearson = pearsonr(self.gold_scores, similarity_scores)
```

It is likely that this line should be rewritten to:

```python
pearson, _ = pearsonr(self.gold_scores, similarity_scores)            
```

Let me know if you would like additional info, happy to make a PR.

**Comment by KennethEnevoldsen** [comment]
Thanks for this PR @stephantul, I will take a look at this tomorrow, when I am at a workstation (it seems related to https://github.com/embeddings-benchmark/mteb/issues/1156)

**Comment by KennethEnevoldsen** [comment]
I have added a PR for it in #1207, based on your suggestion. Feel free to open a PR next time - thank again for opening the issue
