### ISSUE TITLE
Add benchmark overview table

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1209]
Add an overview of available benchmarks (similar to what we have for tasks).

**Comment by isaac-chung** [comment]
Are you envisioning a doc update to list all available benchmarks, a CLI call (like available tasks but for benchmarks), both, or something else?

**Comment by KennethEnevoldsen** [comment]
Documentation update, we could update the CLI as well, but I would probably start with the docs

**Comment by isaac-chung** [comment]
I'm starting to look into adding this table. What do we want in it? I'm envisioning these columns that aggregate all tasks from each benchmark:
- Name (str)
- Task type count (dict) (e.g. Retrieval: 4, Classification: 10)
- Domains (list)
- Languages (list)
