### ISSUE TITLE
Mismatch of the category of AmazonPolarityClassification

### ISSUE THREAD

**Issue by twadada** [embeddings-benchmark/mteb#1219]
In the current ver., AmazonPolarityClassification is registered as 's2s' but it was 'p2p' in the previous ver., and the paper also says it's p2p. I looked at the actual input text, and I guess p2p is the correct one?

**Comment by KennethEnevoldsen** [comment]
Added a fix in #1220 - @Muennighoff just adding you here in case there is something I missed, but I do agree with @twadada that it should probably be s2s

**Comment by KennethEnevoldsen** [comment]
Regardless: "avg_character_length" is probably a better metric.
