### ISSUE TITLE
Adding a new retrieval task

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#122]
Hi big fan of this package/leaderboard. I wanted to extend it to include Scandinavian languages (let me know if you want a PR or prefer that I keep it as a fork).

I however have a few issues with understanding the "relevant_docs" for the retriever. Currently, I am having issues with this specific dataset:

```python
import datasets
from mteb.abstasks.AbsTaskRetrieval import AbsTaskRetrieval

from sentence_transformers import SentenceTransformer

from mteb import MTEB

class SweFAQRetrieval(AbsTaskRetrieval):
    """ """

    @property
    def description(self):
        return {
            "name": "SweFAQ",
            "hf_hub_name": "AI-Sweden/SuperLim",
            "description": "A Swedish FAQ dataset. Available as a part of Superlim",
            "reference": "https://spraakbanken.gu.se/en/resources/superlim",
            "type": "Retrieval",
            "category": "s2p",
            "eval_splits": ["test"],
            "eval_langs": ["sv"],
            "main_score": "ndcg_at_10",
            "revision": "7ebf0b4caa7b2ae39698a889de782c09e6f5ee56",
            "beir_name": "NA",
        }

    def load_data(self, **kwargs):
        """
        Load dataset from HuggingFace hub and convert to MTEB format
        """
        if self.data_loaded:
            return

        self.dataset = datasets.load_dataset(
            self.description["hf_hub_name"], "swefaq", revision=self.description.get("revision")
        )
        self.data_loaded = True

        self.corpus, self.queries, self.relevant_docs = {}, {}, {}
        for split in self.description["eval_splits"]:
            dataset = self.dataset[split]  # type: ignore
            # answers = dataset["candidate_answer"]
            answers = dataset["correct_answer"]
            self.corpus[split] = {
                str(idx): {"_id": str(idx), "title": "", "text": answer} for idx, answer in enumerate(answers)
            }

            questions = dataset["question"]
            self.queries[split] = {str(idx): question for idx, question in enumerate(questions)}

            # Not sure what to do here:
            # first guess: Relevant documents is a mapping between each query and the desired responses (most relevant documents) for that query
            # result: Performance is 0.0 for all metrics
            self.relevant_docs[split] = {str(idx): {str(idx): 1} for idx in range(len(answers))}

            # second guess: Relevant documents is a mapping between each query and the relevant documents a pre-search would return
            # in which case. There is no pre-search, so we assume all documents are relevant.
            # result: Performance is perfect for all metrics

            # self.relevant_docs[split] = {}
            # # assume all are relevant
            # scores = {str(idx): 1 for idx in range(len(answers))}
            # for idx in range(len(answers)):
            #     self.relevant_docs[split][str(idx)] = scores
```

The code runs as is and can be run using:
```
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
evaluation = MTEB(tasks=[SweFAQRetrieval()])
evaluation.run(model)
```

**Comment by Muennighoff** [comment]
It'd be amazing to have those in MTEB as a PR! I can then add a leaderboard tab for them (similar to the German Clustering tab).

Also [this PR](https://github.com/embeddings-benchmark/mteb/pull/121) adding Polish retrieval may be helpful for reference.

Your first guess is correct, relevant docs should map to all document ids relevant to that query.
I'm surprised `self.relevant_docs[split] = {str(idx): {str(idx): 1} for idx in range(len(answers))}` doesn't work. Maybe the model you tested is just not very good at the task?

**Comment by KennethEnevoldsen** [comment]
> It'd be amazing to have those in MTEB as a PR! I can then add a leaderboard tab for them (similar to the German Clustering tab).

Perfect. I will make a PR once I have them ready.

> Also https://github.com/embeddings-benchmark/mteb/pull/121 adding Polish retrieval may be helpful for reference.
Yea did take a look at it, but they seem to use the BEIR format

> Your first guess is correct
Good to hear. I will keep using it and try it out with a few other models as well.

**Comment by KennethEnevoldsen** [comment]
I have added it in a PR. Along with the remainder of the Scandinavian tasks. I still can't get it to work (as mentioned in the PR).

**Comment by KennethEnevoldsen** [comment]
I have resolved this issue over at the [Scandinavian embedding benchmark](https://github.com/KennethEnevoldsen/scandinavian-embedding-benchmark/blob/main/src/seb/mteb_tasks.py). I will port the datasets to MTEB once I have a reasonable set of tasks.
