### ISSUE TITLE
Add proper metadata to models

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#1234]
Currently, many of the fields in model metadata are not filled.
These should either be specified manually or we should find ways to derive them (from HuggingFace Hub for example.)

**Comment by x-tabdeveloping** [comment]
We're also missing Metadata objects completely for some models (`all-MiniLM-L12-v2` for instance). Or some of them have no matching revision in the results.

**Comment by KennethEnevoldsen** [comment]
> We're also missing Metadata objects completely for some models (all-MiniLM-L12-v2 for instance). Or some of them have no matching revision in the results.

Might be worth changing the default revision to the one in the results.

**Comment by isaac-chung** [comment]
For some of the model configs such as `n_parameters`, `embed_dim`, and `max_tokens`, a script can be created to get those info from HF hub like how we do it in the [leaderboard code](https://github.com/embeddings-benchmark/leaderboard/blob/main/refresh.py). 

> We're also missing links

What do you mean here?

**Comment by x-tabdeveloping** [comment]
> We're also missing links

On the older leaderboard you could click on the models and it would lead you to their home page. We don't have links in the ModelMeta object right now.

> For some of the model configs such as n_parameters, embed_dim, and max_tokens, a script can be created to get those info from HF hub like how we do it in the [leaderboard code](https://github.com/embeddings-benchmark/leaderboard/blob/main/refresh.py).

I looked into this earlier, but it's not my preferred solution. A couple of reasons:
1. We  would rely on HuggingFace Hub's interfaces and implementation.
2. Consequently, it would be a piece of code that has to be written and maintained.
3. It would not work for models that are not on HuggingFace Hub
4. It would be awkward to work with models that are on the hub, but are not open access (like Llama).

I would prefer just writing these properties in by hand as:
1. We (the team) would only have to do this once for the models we have.
2. I think it would be relatively easy for people submitting new models as PRs to have to fill in this information.

I would love to hear others' thoughts tho, this is a slight preference, not a strong one.

**Comment by KennethEnevoldsen** [comment]
I believe this issue is resolved will close it feel free to reopen
