### ISSUE TITLE
Sort benchmarks by name

### ISSUE THREAD

**Issue by isaac-chung** [embeddings-benchmark/mteb#1257]
When listing all available benchmarks, we wish to
- list the MTEB ones first, sort those by name
- then sort the rest by name

From https://github.com/embeddings-benchmark/mteb/pull/1256#pullrequestreview-2335849861

**Comment by sathviknallamalli** [comment]
I completed this and opened a PR for it: https://github.com/embeddings-benchmark/mteb/pull/1271

**Comment by isaac-chung** [comment]
Thanks! In future, feel free to tag the issue within the PR.
