### ISSUE TITLE
Allow toggle for raising errors

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#126]
Currently, tasks fail silently and are written to a file. It would make it easier to debug if it was possible to toggle the raising of errors.

I can create the PR with a solution if this is something you want.

**Comment by Muennighoff** [comment]
Yeah, I agree that would make things easier. I think we can even make it the default.
Would be amazing if you can open a PR!

**Comment by KennethEnevoldsen** [comment]
Sure thing. It will probably be there today or tomorrow.
