### ISSUE TITLE
Only skip benchmarking if split results are the same too

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1260]
We currently skip evaluation if the results file already exists, however, it may be that the file exists but not with the same splits/subsets as requested by the current evaluation. I think we may want to also check equivalence across splits & subsets and then run the ones still missing and edit the existing results file to put them back in.

**Comment by thivyanth** [comment]
#1268 I tried my best but I need to make myself more familiar with the codebase and try again.
