### ISSUE TITLE
Allow Numpy 2.0

### ISSUE THREAD

**Issue by mgraczyk** [embeddings-benchmark/mteb#1263]
It looks like the issue blocking Numpy 2.0 has been closed:
via https://github.com/embeddings-benchmark/mteb/blob/main/pyproject.toml#L29
issue
https://github.com/huggingface/datasets/issues/6980

Would it be possible to bump maximum allowed numpy version from <2 to <3 or <2.2?

I'm happy to create a PR and test if necessary

**Comment by isaac-chung** [comment]
I don't think there's anything more blocking us other than that issue. It would be great if you could create a PR @mgraczyk ! Looping in @KennethEnevoldsen as well.
