### ISSUE TITLE
Add mteb(eng), mteb(europe), mteb(indic) and mteb(multilingual)

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1273]
- [ ] MTEB(eng):
  - Notably update touche to v3: https://github.com/embeddings-benchmark/mteb/pull/1262

- [ ] MTEB(multilingual):
  - add miraclhardnegatives

- [ ] MTEB(europe) and MTEB(indic) need to be added

**Comment by isaac-chung** [comment]
Is this issue about adding/extending benchmarks in [benchmarks.py](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/benchmarks/benchmarks.py)?

**Comment by isaac-chung** [comment]
Just noticed that [MTEB(pol)](https://github.com/embeddings-benchmark/mteb/blob/b1a6caef3aa2f4733d890b3ef1057478676dca34/mteb/benchmarks/benchmarks.py#L470) is in lowercase instead of upper case for the lang code. Can update that in the next PR as well.
