### ISSUE TITLE
Question about the chosen of language code

### ISSUE THREAD

**Issue by ZiyiXia** [embeddings-benchmark/mteb#1298]
I noticed that when using `get_tasks()`, the language code of C-MTEB tasks is `cmn` but not `zho`. However the definition classes of those tasks are in the 'zho' directories, which confused me a little at the beginning because I cannot get those tasks by specifying `languages='zho'`.

So I'm wandering how is this designed. Appreciate any idea, discussion, or explanation!

**Comment by isaac-chung** [comment]
Based on [git blame](https://github.com/embeddings-benchmark/mteb/commit/f0daece8d8c6491a9d06153763f0d76c2773e251), these were mapped to "Mandarin Chinese" (cmn), whereas zho maps to "Chinese". I don't see an issue aligning the lang codes in the tasks to the folder name, i.e. updating all relevant lang codes to `zho`.

@ZiyiXia thanks for catching this. Feel free to open a PR!

CC @KennethEnevoldsen just in case I missed something obvious or there was a reason I wasn't aware of.

**Comment by ZiyiXia** [comment]
Got it. Keeping `cmn` now make sense to me. Happy to discuss in the future when there's demand to align the lang codes. Thanks!

**Comment by isaac-chung** [comment]
Sounds good. I'll close this for now, but feel free to reopen whenever this topic comes back.

**Comment by KennethEnevoldsen** [comment]
I believe "cmn" is a more specific language than "zho", which also refers to "cmn", "yue". 

<img width="485" alt="Screenshot 2024-10-21 at 21 37 08" src="https://github.com/user-attachments/assets/b7377505-2a3b-4b4c-8ebf-05a0c5e4b18f">

I would accept either "cmn" and "yue" OR "zho," but I would probably not use both. Would love the opinion of a Chinese speaker on this as I don't have much experience on the differences.
