### ISSUE TITLE
Arxiv paper submission

### ISSUE THREAD

**Issue by gentaiscool** [embeddings-benchmark/mteb#1299]
@KennethEnevoldsen @Muennighoff I was wondering whether we are going to release the preprint of the MMTEB paper for better visibility and engagement. I think it would be a great idea to put it on arxiv, so we can promote it.

Let me know what you think

**Comment by Samoed** [comment]
There was discussion recently https://github.com/embeddings-benchmark/mteb/issues/896#issuecomment-2400717615

**Comment by isaac-chung** [comment]
Closing this as there's an existing discussion in the above issue.

**Comment by KennethEnevoldsen** [comment]
Appreciate it @gentaiscool and yea let us keep it in #896 - as expressed there we would really like to get the updated leaderboard up and running first. We expect how have that ready within the month or so.
