### ISSUE TITLE
BrazilianToxicTweetsClassification broken

### ISSUE THREAD

**Issue by Samoed** [embeddings-benchmark/mteb#1324]
When running tests, I encountered an error with `BrazilianToxicTweetsClassification`.

In #1300 [runner logs](https://github.com/embeddings-benchmark/mteb/actions/runs/11507752472/job/32034563069?pr=1300):
```
FAILED tests/test_benchmark/test_benchmark_integration_with_datasets.py::test_benchmark_sentence_transformer[model0-BrazilianToxicTweetsClassification] - KeyError: "Column homophobia not in the dataset. Current columns in the dataset: ['text', 'label']"
```

And in #1323 [runner logs](https://github.com/embeddings-benchmark/mteb/actions/runs/11507398870/job/32033481147?pr=1323):
```
FAILED tests/test_benchmark/test_benchmark_integration_with_datasets.py::test_benchmark_sentence_transformer[model0-task1] - FileNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
```

I suggest changing the "integration" tasks in tests to tasks with datasets from the MTEB organization, as it would allow us better control over them

**Comment by Samoed** [comment]
I think that there are some issues in github, because my main page is not loading, but on githubstatus everything is fine

**Comment by KennethEnevoldsen** [comment]
I agree - using a smaller dataset uploaded to the mteb org would be ideal

**Comment by Samoed** [comment]
Done in https://github.com/embeddings-benchmark/mteb/pull/1352
