### ISSUE TITLE
Leaderboard: Add benchmark description and citation

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1342]
It would be nice to have a benchmark description somewhere on the page, e.g. here:

<img width="528" alt="Screenshot 2024-10-28 at 09 06 26" src="https://github.com/user-attachments/assets/2e1831f2-ca13-47cf-ad2d-01a4d7b3497d">

It could also be at the very bottom or in another tab (Benchmark Overview). I could imagine this tab also including citations (should be there somewhere) and an overview of tasks.

**Comment by x-tabdeveloping** [comment]
PR #1345 fixes this, closing
