### ISSUE TITLE
Increased memory usage for FEVER (and/or other retrieval tasks?)

### ISSUE THREAD

**Issue by tomaarsen** [embeddings-benchmark/mteb#1343]
Hello!

I'm noticing that with the `main` branch I'm no longer able to run FEVER on a 1024-dim model with 32GB of memory. Have we recently switched something up there?
Granted, I haven't ran BEIR on any model in quite a while.

This is a slight bottleneck for a new model release of mine - I'm using NanoBEIR now instead: https://huggingface.co/collections/zeta-alpha-ai/nanobeir-66e1a0af21dfd93e620cd9f6

- Tom Aarsen

**Comment by tomaarsen** [comment]
I figured it out - I didn't specify `eval_splits=["test"]` and so it started running evaluations on the training set 😅 
Runs smoothly now!

- Tom Aarsen

**Comment by tomaarsen** [comment]
That might be valuable, although I think that just a warning if a `train` split is requested might also fix it.

**Comment by KennethEnevoldsen** [comment]
Added a PR. It might be nice to know that we have a fast dataset`"FEVERHardNegatives"` and a fast benchmark `"MTEB(eng, beta)"`. The second one is zero-shot but approximates the original MTEB(eng, classic) well (except for cases where a model is fitted on one of the tasks).
