### ISSUE TITLE
Clarification on samples_per_label Settings for Each Dataset

### ISSUE THREAD

**Issue by Nieleilei** [embeddings-benchmark/mteb#1350]
Thank you very much for providing this code! I’m interested in understanding the samples_per_label parameter for each task. Specifically, I’d like to know how this parameter is set for each dataset. Is there any official documentation available that outlines the standard settings for samples_per_label for each dataset? I’d appreciate the chance to review this if possible.

Thank you!

**Comment by isaac-chung** [comment]
Hi @Nieleilei ! 

Currently each AbsTask has a default `samples_per_label`, e.g. 8 for [AbsTaskClassification](https://github.com/embeddings-benchmark/mteb/blob/d9626abbc5d438024a21e7f21a29d4741bb94188/mteb/abstasks/AbsTaskClassification.py#L69). Each task can override this parameter by setting a `medata_dict` property like the following:
```python
@property
--
def metadata_dict(self) -> dict[str, str]:
    metadata_dict = super().metadata_dict
    metadata_dict["samples_per_label"] = 16
    return metadata_dict
```

A [quick search over the repo](https://github.com/search?q=repo%3Aembeddings-benchmark%2Fmteb%20samples_per_label%20&type=code) should lead to the rest of the defaults. If you'd like to contribute to the docs on this, we'd definitely welcome a PR!

**Comment by KennethEnevoldsen** [comment]
Might be worth moving this to be a task attribute to document it:

```
class AbsTaskClassification(AbsTask):
    """Abstract class for kNN classification tasks
    The similarity is computed between pairs and the results are ranked.

    self.load_data() must generate a huggingface dataset with a split matching self.metadata_dict["eval_splits"], and assign it to self.dataset. It
    must contain the following columns:
        text: str
        label: int

    Attributes:
       samples_per_label: Number of samples to use pr. label. These samples are embedded and a classifier is fit using the labels and samples.

    """
    samples_per_label: int = 8


    def __init__(...
