### ISSUE TITLE
Code to replicate Figure 2 in the paper

### ISSUE THREAD

**Issue by econabhishek** [embeddings-benchmark/mteb#136]
You've all done an excellent job putting this together! I was wondering if you have a replication code somewhere for generating the Figure 2 (if not the figure, at least the numbers) before I start writing it from scratch. 

My team is in the process of releasing a new benchmark with the texts coming from a period between 1920-1980 and we were hoping to see how different it is compared to the datasets in MTEB and also how things evolve over the years. 

(Well, it's already out)
[Dataset ](https://huggingface.co/datasets/dell-research-harvard/headlines-semantic-similarity) | [Paper](https://arxiv.org/pdf/2306.17810.pdf#:~:text=The%20headlines%20of%20reproduced%20articles%20form%20positive%20semantic,and%20covers%20a%20much%20longer%20span%20of%20time.)
It was put together with the help of @nreimers ' sentence-transformers package)

**Comment by Muennighoff** [comment]
Sure all plotting code is in the mtebscripts repo; Specifically Fig 2 uses this script: https://github.com/embeddings-benchmark/mtebscripts/blob/main/plotstables/dataset_sim.py

**Comment by econabhishek** [comment]
That was quick! Thank you!
