### ISSUE TITLE
No module named 'datasets.tasks'

### ISSUE THREAD

**Issue by bwanglzu** [embeddings-benchmark/mteb#1363]
when running MMTEB, i got the error:

```
  File "/home/bo/.cache/huggingface/modules/datasets_modules/datasets/SpellOnYou--kor_sarcasm/0
0d38c200d4d563ed94efb9ff4ca119ded94fe3cdf1e381ed95274de0a9d59f0/kor_sarcasm.py", line 21, in <m
odule>
    from datasets.tasks import TextClassification
ModuleNotFoundError: No module named 'datasets.tasks'
```

The reason is in huggingface datasets 3.X, the tasks has been removed: https://github.com/huggingface/datasets/pull/6999

This affect some of the MMTEB datasets, such as https://huggingface.co/datasets/SpellOnYou/kor_sarcasm, the temp solution is to downgrade huggingface datasets to `datasets==2.21.0` (the latest before `3.0`).

**Comment by KennethEnevoldsen** [comment]
I can reproduce the error. Added a specific fix here #1364 

rerunning MTEB(Multilingual, beta) to see if there is other cases
