### ISSUE TITLE
When (manually) caching embeddings this line breaks the order and renders caching useless

### ISSUE THREAD

**Issue by alexeifigueroa** [embeddings-benchmark/mteb#1366]
https://github.com/embeddings-benchmark/mteb/blob/992d470eea34fc9c2cc684d40d6854e9567c7f72/mteb/evaluation/evaluators/PairClassificationEvaluator.py#L84

consider a change for
`sentences = list({s:None for s in self.sentences1 + self.sentences2}.keys())`

**Comment by isaac-chung** [comment]
Hi! Would you mind sharing a minimally reproducible example and the outputs? Would really help us understand the context more. Thanks!

**Comment by isaac-chung** [comment]
Closing this now. Cannot reproduce. Feel free to reopen with a reproducible example.
