### ISSUE TITLE
Leaderboard 2.0: should we fetch data from model card?

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1373]
Currently, model metadata files become quite extensive if they cover all tasks in mteb (#1368). This makes it frustrating for users to see what scores a model has (having scores for >30 datasets doesn't really give a great overview). The ideal solution would probably be to either:

1) Allow users to upload an `mteb_results/*` folder
2) Only accept results pushed to embedding-benchmark/results

Let me know what you guys think (@Muennighoff, @imenelydiaker, @isaac-chung, @orionw, @x-tabdeveloping)

**Comment by isaac-chung** [comment]
It's not like they are blocked from doing so, right? One option was to use git-lfs. I see some pros and cons of this suggestion:
- pros:
  - we can validate the scores before accepting them, e.g. in terms of structure
  - single source of truth
- cons:
  - additional step for users to submit to the leaderboard
  - additional items for maintainers to review: though this can be alleviated by automating checks.

**Comment by orionw** [comment]
+1 to everything.

If at some point we want to switch over entirely, we could convert the metadata on HF pages into files we can PR into the results repo.

**Comment by KennethEnevoldsen** [comment]
I agree with everything here. The current benchmark does not support the metadata files from HF. We can either have it fetch from the model metadata from HF or add CI to `embedding-benchmark/results` to do it. I am fine with either (whatever is the easiest to implement).

**Comment by x-tabdeveloping** [comment]
It would be great if we at least transfered the results from the old leaderboard to `embedding-benchmark/results` so that the old leaderboard can be used out of the box within the new one.

**Comment by Samoed** [comment]
I'll try to collect all available scores

**Comment by x-tabdeveloping** [comment]
Moved the discussion to the referenced (https://github.com/embeddings-benchmark/results/pull/43)
