### ISSUE TITLE
Disabling rich output.

### ISSUE THREAD

**Issue by Napuh** [embeddings-benchmark/mteb#1385]
Hi. Im using mteb library as part of long-running scripts for evaluating embedding models. 

When running this on on terminals the output from `logging` and `rich` uses a lot of prints and takes a lot of space on the terminal, I'd rather implement my own logs on my application code and disabling the ones included in mteb. 

Setting `logging.basicConfig(level=logging.ERROR)` get most of them gone, in combination with `verbose=0` on `evaluation.run`. I want to disable `rich` output too. I've found that setting env variable `RANK` to a value different than 0 can solve my problem, but It's a terrible idea when running my code on distributed environments like slurm.

Is there any way I can make a PR to disable `rich` output? Is it better to have an ENV variable for this or to pass an argument to `evaluation.run`. I'd like some guidance on how to solve this issue.

**Comment by KennethEnevoldsen** [comment]
Thanks @Napuh. Seems like it might be ideal to solve #1046

Ideally, it should be possible to set the verbosity level such that you don't get rich output. I believe wrapping this in an if statement (dependent on your logging level) should solve your issue.

https://github.com/embeddings-benchmark/mteb/blob/ef4df6209fc1583fbad611b305f5add24828e150/mteb/evaluation/MTEB.py#L365

**Comment by Napuh** [comment]
Here is the PR: https://github.com/embeddings-benchmark/mteb/pull/1395
