### ISSUE TITLE
RetrievalEvaluator NaN values for similarity scores

### ISSUE THREAD

**Issue by gnatesan** [embeddings-benchmark/mteb#1389]
I am looking at RetrievalEvaluator.py and I see the line   **cos_scores[torch.isnan(cos_scores)] = -1**

Basically, if a query-document similarity score has a NaN value, then it gets changed to -1. 

My question is how would a NaN score appear when using cosine similarity as the distance metric? Would the query and document embedding vectors contain very small values when a NaN value appears?

**Comment by KennethEnevoldsen** [comment]
My guess is that it can appear as a result of an invalid model output. @Muennighoff or @orionw might know more about it? We should probably log a warning around that statement.

**Comment by KennethEnevoldsen** [comment]
Generation of the text embedding. Adding logging to in #1398. Ran through tests, but couldn't find a case where it was actually used.

**Comment by Samoed** [comment]
I think that you can look throught results repo to find nan values and retest them, e. g. https://github.com/embeddings-benchmark/results/blob/7695129d2b450f2c22b3a8633ab3deb1f8c54b4a/results/intfloat__multilingual-e5-small/e4ce9877abf3edfe10b0d82785e83bdcb973e22e/LegalBenchConsumerContractsQA.json#L91

**Comment by gnatesan** [comment]
Ok thanks
