### ISSUE TITLE
Evaluating a custom dataset

### ISSUE THREAD

**Issue by ashokrajab** [embeddings-benchmark/mteb#141]
Say, I have my own dataset on which I want to benchmark on. It would be great if there is a native support to carry out the same.

**Comment by Muennighoff** [comment]
There is supposed to be native support for that as detailed in this section: https://github.com/embeddings-benchmark/mteb#evaluating-on-a-custom-task
Is it unclear in any way / can it be improved?

**Comment by ashokrajab** [comment]
Thank you for pointing it out, this does satisfy my requirement. 
Thank you for the prompt response.

**Comment by ashokrajab** [comment]
> Is it unclear in any way / can it be improved?
to so happens to be that one has to import the newly created in Custom task in the [__init__.py](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Retrieval/__init__.py) in order for the custom task to be recognised by [select_tasks()](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/evaluation/MTEB.py#L153) under MTEB.py. 

This does not makes it ideal for someone who wanted to install mteb in non editable mode. Any thoughts on how to circumvent this?

**Comment by ashokrajab** [comment]
@Muennighoff 

> Is it unclear in any way / can it be improved?
 <br>
it to so happens to be the case that one has to import the newly created in Custom task in the [__init__.py](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Retrieval/__init__.py) in order for the custom task to be recognised by [select_tasks()](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/evaluation/MTEB.py#L153) under MTEB.py. 
 <br>
This does not makes it ideal for someone who wants to install mteb in non editable mode and not making any changes in the source code. Any thoughts on how to circumvent this?

**Comment by Muennighoff** [comment]
The code snippet below from the README should work without adding it to `init.py`. You just have to initialize the class i.e. `tasks=[MindSmallReranking()]`

```
from mteb import MTEB
from mteb.abstasks.AbsTaskReranking import AbsTaskReranking
from sentence_transformers import SentenceTransformer


class MindSmallReranking(AbsTaskReranking):
    @property
    def description(self):
        return {
            "name": "MindSmallReranking",
            "hf_hub_name": "mteb/mind_small",
            "description": "Microsoft News Dataset: A Large-Scale English Dataset for News Recommendation Research",
            "reference": "https://www.microsoft.com/en-us/research/uploads/prod/2019/03/nl4se18LinkSO.pdf",
            "type": "Reranking",
            "category": "s2s",
            "eval_splits": ["validation"],
            "eval_langs": ["en"],
            "main_score": "map",
        }

model = SentenceTransformer("average_word_embeddings_komninos")
evaluation = MTEB(tasks=[MindSmallReranking()])
evaluation.run(model)
```

**Comment by Jeru2023** [comment]
1. What’s the format of custom dataset required? - just corpus and queries in id+text format? 
2. Do I have to upload data file to huggingface? 
3. and how corpus and queries matched automatically with human label during the evaluation process?

**Comment by Muennighoff** [comment]
> 1. What’s the format of custom dataset required? - just corpus and queries in id+text format?
> 2. Do I have to upload data file to huggingface?
> 3. and how corpus and queries matched automatically with human label during the evaluation process?

1. It depends on the task you'd like to benchmark. For retrieval, yes pretty much - you can check the format of some of the Retrieval datasets in MTEB, e.g. https://huggingface.co/datasets/C-MTEB/T2Retrieval and their accompanying code
2. You can also load it from disk, though you will probably have to modify a code a bit for that to work; Also you can upload it as a private dataset on HF and supply your API key if you don't want it to be public
3. They are evaluated based on the qrels; you need to provide the ground truth mapping of which docs are correct for which query for Retrieval

**Comment by Jeru2023** [comment]
> > 1. What’s the format of custom dataset required? - just corpus and queries in id+text format?
> > 2. Do I have to upload data file to huggingface?
> > 3. and how corpus and queries matched automatically with human label during the evaluation process?
> 
> 1. It depends on the task you'd like to benchmark. For retrieval, yes pretty much - you can check the format of some of the Retrieval datasets in MTEB, e.g. https://huggingface.co/datasets/C-MTEB/T2Retrieval and their accompanying code
> 2. You can also load it from disk, though you will probably have to modify a code a bit for that to work; Also you can upload it as a private dataset on HF and supply your API key if you don't want it to be public
> 3. They are evaluated based on the qrels; you need to provide the ground truth mapping of which docs are correct for which query for Retrieval

Thanks, appreciate your clear answer.

**Comment by Jeru2023** [comment]
One more question:
the datasets in hug is parquet format, what's the raw data format of corpus, queries and qrels? and should i also convert it to parquet when using them locally.

**Comment by Muennighoff** [comment]
> One more question: the datasets in hug is parquet format, what's the raw data format of corpus, queries and qrels? and should i also convert it to parquet when using them locally.

I think the file extension does not matter as long as it can be loaded; jsonl etc. should also be ok

**Comment by Jeru2023** [comment]
> > One more question: the datasets in hug is parquet format, what's the raw data format of corpus, queries and qrels? and should i also convert it to parquet when using them locally.
> 
> I think the file extension does not matter as long as it can be loaded; jsonl etc. should also be ok

OK but however the format matters, it depends on how the code parse the file, right?

**Comment by Jeru2023** [comment]
corpus.json
[{
  "name": "corpus",
  "text": "红棉优级小粒老黄冰糖1.2kg大罐炖煮煲汤红烧肉酵素柠檬花茶雪梨",
  "id": 1,
  "dev": {}
}]

queries.json
[{
  "name": "queries",
  "text": "红棉",
  "id": 1,
  "dev": {}
}]

-qrels.json
[{
  "name": "dev",
  "dev":{
    "qid": 1,
    "pid": 1,
    "score": 1
  }
}]

this is the smallest test dataset I defined according to parser logic, however i got an error below:
All the data files must have the same columns, but at some point there are 2 new columns ({'id', 'text'})

I'm not able to figure out why, pls kindly help.

**Comment by Jeru2023** [comment]
> corpus.json [{ "name": "corpus", "text": "红棉优级小粒老黄冰糖1.2kg大罐炖煮煲汤红烧肉酵素柠檬花茶雪梨", "id": 1, "dev": {} }]
> 
> queries.json [{ "name": "queries", "text": "红棉", "id": 1, "dev": {} }]
> 
> -qrels.json [{ "name": "dev", "dev":{ "qid": 1, "pid": 1, "score": 1 } }]
> 
> this is the smallest test dataset I defined according to parser logic, however i got an error below: All the data files must have the same columns, but at some point there are 2 new columns ({'id', 'text'})
> 
> I'm not able to figure out why, pls kindly help.

Now i changed the format
queries.json and corpus.json have same format below:
```
[{
  "id": 1,
  "text": "红棉"
}]
```

qrels.json
```
[{
    "qid": 1,
    "pid": 1,
    "score": 1
}]
```

It's wired qrels required same format as corpus and quries.
All the data files must have the same columns, but at some point there are 2 new columns (id, text) and 3 missing columns (qid, score, pid).

**Comment by Jeru2023** [comment]
Above issue solved already, i should place qrels in different folder, but anther issue jumped out:
Message: KeyError: 'corpus'
Relevant code: corpus = {e['id']: {'text': e['text']} for e in dataset['corpus']}

after corpus and queries dataset loaded:
dataset = load_dataset(hf_hub_name)

I printed out the dataset:
DatasetDict({
    train: Dataset({
        features: ['text', 'id'],
        num_rows: 4
    })
})
Obviously corpus is not a key in dataset dict

My file sturcture as below:
dataset
  - queries.json
  - corpus.json
dataset-qrels
  - qrels.json

**Comment by Jeru2023** [comment]
finally worked, we must strictly follow the directory structure and file name prefix convention.

**Comment by KennethEnevoldsen** [comment]
Seems like this issue is resolved, I will close this issue for know, but feel free to open it if needed.

**Comment by Jeru2023** [comment]
For retrieval custom dataset, can someone explain to me why the score in qrels are all 1 given there are positive and negative content related to query.
