### ISSUE TITLE
Running models before leaderboard release

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#1411]
### Models we have

Currently, when you run the leaderboard, the only models that appear on the majority of our new benchmarks (e.g. `MTEB(Multilingual)`, `MTEB(Europe)`, etc.) are the following:
- [multilingual-e5-large-instruct](https://huggingface.co/intfloat/multilingual-e5-large-instruct)
- [GritLM-7B](https://huggingface.co/GritLM/GritLM-7B)
- [e5-mistral-7b-instruct](https://huggingface.co/intfloat/e5-mistral-7b-instruct)
- [multilingual-e5-base](https://huggingface.co/intfloat/multilingual-e5-base)
- [paraphrase-multilingual-mpnet-base-v2](https://huggingface.co/sentence-transformers/paraphrase-multilingual-mpnet-base-v2)
- [LaBSE](https://huggingface.co/sentence-transformers/LaBSE)
- [paraphrase-multilingual-MiniLM-L12-v2](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2)
- [all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2)

###  Models we want

I suspect this is because the other models were not run on all the tasks from these benchmarks.
Ideally, we would have a suit of other relevant models on the benchmark to start with.
I'm opening this issue to discuss which models should be run before the leaderboard release, and which models we should focus primarily on when it comes to getting correct metadata (e.g. whether models are zero-shot)

 To start off the discussion, I suggest to run the following and add results to the result repo:
 - [ ] The [E5 family](https://huggingface.co/intfloat)
 - [ ] [NV-Embed](https://huggingface.co/collections/nvidia/nv-embed-66588aba24f3d17e4bdd3c3a) (potentially not zero-shot)
 - [ ] [BGE](https://huggingface.co/BAAI) (potential data leak)
 - [ ] [Stella](https://huggingface.co/dunzhang)
 - [ ] [GTE](https://huggingface.co/collections/Alibaba-NLP/gte-models-6680f0b13f885cb431e6d469)
 - [ ] [Salesforce SFR](https://huggingface.co/Salesforce/SFR-Embedding-Mistral)
 - [ ] [Voyage](https://docs.voyageai.com/docs/embeddings)
 - [ ] [Google's embeddings](https://docs.voyageai.com/docs/embeddings)
 - [ ] [LLM2Vec](https://huggingface.co/collections/McGill-NLP/llm2vec-660e14f536b3c8d10b3f1c34)
 - [ ] [Jina](https://huggingface.co/arkohut/jina-embeddings-v3)
 - [ ] [OpenAI embeddings](https://openai.com/index/new-embedding-models-and-api-updates/)
 - [ ] [Cohere](https://huggingface.co/Cohere/Cohere-embed-multilingual-v3.0)

If you think some of these are not relevant for us, or think that I missed something, please say so.

**Comment by x-tabdeveloping** [comment]
@Muennighoff You said that you have some GPUs lying around yesterday, maybe something for you?

**Comment by Muennighoff** [comment]
Nice, I can definitely run them!
For NV-Embed, I think we need to add it to MTEB - @YashDThapliyal was going to look into that I think?
I think the others should all be there; I will start by running them all on MMTEB if that sounds good? cc @KennethEnevoldsen 

(btw the new leaderboard looks really amazing!)

**Comment by YashDThapliyal** [comment]
@Muennighoff Yep I will be working on addding NV-Embed

**Comment by Muennighoff** [comment]
For BGE would be great if someone can integrate bge-en-icl

**Comment by Muennighoff** [comment]
Added a lot of the models in https://github.com/embeddings-benchmark/results/pull/40/ ; i can run dozens more, just that they need to be implemented & working in mteb

**Comment by x-tabdeveloping** [comment]
@Muennighoff Can you check off the boxes so that people know what has already been run? (thanks for the compliments on the leaderboard :D)

**Comment by KennethEnevoldsen** [comment]
Seems to be a copy of #1571 so will close this in one in favor of the other
