### ISSUE TITLE
Query Regarding the relevant_docs in retrieval 

### ISSUE THREAD

**Issue by kshitij0-0** [embeddings-benchmark/mteb#142]
Hey ,
Firstly, Thanks for building a common benchmark for all the models.

I had a query about how the relevant_docs are being gathered in the Information Retrieval Tasks?

Thank You in advance

**Comment by iavinasoss** [comment]
if that's the case then how would evaluating the model be effective? wont the model pick the same docs while evaluation also?

Also , this is what i was referring when i said relevant_docs , not the ones that are derived from the model.

relevant_docs: Dict[str, Set[str]]
query_relevant_docs = self.relevant_docs[query_id]

Thanks for helping out

**Comment by Muennighoff** [comment]
The model encodes all queries, then all corpus documents.
Then for each query the cosine similarity is computed with the query & all corpus docs. The top k with the highest cosine similarity are kept.
Then it is compared how many of them are correct.

Maybe the relevant_docs you are referring to are the ground truth labels not the one predicted by the model, sorry. The scores are computed depending on how many of the model's predicted docs are in the ground truth correct docs.

**Comment by iavinasoss** [comment]
Yeah im referring to the ground truth labels here ..... how or from where are they being fetched or calculated?

**Comment by Muennighoff** [comment]
From e.g. here https://huggingface.co/datasets/BeIR/arguana-qrels

**Comment by iavinasoss** [comment]
Got it thanks for helping

**Comment by Jeru2023** [comment]
> From e.g. here https://huggingface.co/datasets/BeIR/arguana-qrels

Good question, i have some concern.
Above link is the ground truth label i'm looking for, but the dataset in MTEB only have corpse and queries, i don't find any label like above link, so how it works?

**Comment by KennethEnevoldsen** [comment]
Seems like this issue has been resolved. Will close it.
