### ISSUE TITLE
Enable Code Carbon by default in evaluation runs

### ISSUE THREAD

**Issue by isaac-chung** [embeddings-benchmark/mteb#1427]
[Edit] Was discussing with @KennethEnevoldsen about [this suggestion](https://github.com/embeddings-benchmark/results/pull/43#issuecomment-2465058800) as a way to combine run eval time + hardware info so we don't have to keep track of both. Enabling this would be a convenient step towards that before we decide to use something else that is more representative (such as FLOPS).

**Comment by Muennighoff** [comment]
What's the motivation for enabling it by default? I think @imenelydiaker intentionally made it optional in https://github.com/embeddings-benchmark/mteb/pull/712#issuecomment-2110933622 🤔

**Comment by isaac-chung** [comment]
Was discussing with @KennethEnevoldsen about [this suggestion](https://github.com/embeddings-benchmark/results/pull/43#issuecomment-2465058800) as a way to combine run eval time + hardware info so we don't have to keep track of both. Enabling this would be a convenient step towards that before we decide to use something else that is more representative (such as FLOPS).

**Comment by Muennighoff** [comment]
Makes sense, thanks for the context!!

**Comment by isaac-chung** [comment]
No worries, my bad for not filling out the description in the first place. Updated!

**Comment by Samoed** [comment]
CO² added to open llm leaderboard https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard

**Comment by isaac-chung** [comment]
Merged into branch v2.0.0
