### ISSUE TITLE
[MIEB] Flickr30K not matching openAI ViT B32 results

### ISSUE THREAD

**Issue by isaac-chung** [embeddings-benchmark/mteb#1434]
Openai ViT B32 I2T R@5 should be [94.9 in CLIP benchmark](https://github.com/LAION-AI/CLIP_benchmark/blob/main/benchmark/benchmark.csv). Right now I just ran it and got 65.68.

Cc @gowitheflow-1998 @Jamie-Stirling

**Comment by gowitheflow-1998** [comment]
likely relevant to dataset implementation of Flickr30k (splits, setting etc) as most MSCOCO results have are matching with papers if @Jamie-Stirling can look into it?

**Comment by Jamie-Stirling** [comment]
I will look into this ASAP
