### ISSUE TITLE
Leaderboard: Fix code benchmarks

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#1439]
Currently `CoIR` and `MTEB(Code)` do not work with the new leaderboard, as they contain a completely different set of languages from the rest, and this confuses the Gradio elements that have been told that the only list of choices is the languages that are present in the Multilingual benchmark.

This issue is also a question on whether this is something we would like to have on the main leaderboard.
@KennethEnevoldsen @Muennighoff @isaac-chung

**Comment by isaac-chung** [comment]
I think we should support them as well.
Can we aggregate all the languages across all benchmarks, or is it more complicated than that?

**Comment by x-tabdeveloping** [comment]
I'll look into it.

**Comment by x-tabdeveloping** [comment]
Turns out it was pretty easy to fix: #1441
