### ISSUE TITLE
Leaderboard: Add radar chart 

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1443]
Not planned for the current release of the leaderboard, but it would be nice to have a radio chart for the plots. To make it clear where models excel. The radar plot could include task types, languages and/or domains.

It could either be placed where the description is now (moving the description up) or we could have it below the table.

Example of a radar chart
![radar_chart](https://github.com/user-attachments/assets/4a4d5735-9f4c-4e94-bdf1-7feb6dbe4be8)

A critique of radar chart:
https://blog.scottlogic.com/2011/09/23/a-critique-of-radar-charts.html

There might be better plots available to access model capabilities quickly (though I think radar is a good fit on our case).

**Comment by isaac-chung** [comment]
Would this chart be per-model? I'm trying to imagine where it would fit in the current layout. Maybe a separate tab as a single-model-view would fit this better

**Comment by KennethEnevoldsen** [comment]
Yea, I also considered a tab where you compare models (e.g. 1-4) - otherwise it would get two crowded

**Comment by x-tabdeveloping** [comment]
I'm working on a prototype, will send screenshots once it gets neat enough

**Comment by x-tabdeveloping** [comment]
![image](https://github.com/user-attachments/assets/af613c23-05db-478c-be4a-e7634bc1b257)

Whatcha think about this?

**Comment by KennethEnevoldsen** [comment]
Looks great @x-tabdeveloping - is it possible to remove the shading i think that would make the plot more readable.

I would also change the tabs headers to:

"Performance by Size", "Performance by Task Category"

And then in the plot add "Performance by Task Category for the top-5 models."

Otherwise Wonderful addition.
