### ISSUE TITLE
Can't load some datasets because of datasets 3.0

### ISSUE THREAD

**Issue by Samoed** [embeddings-benchmark/mteb#1465]
When I try to download datasets, I get the error `ModuleNotFoundError: No module named 'datasets.tasks'` or a similar one, because in `datasets` version 3.0, `tasks` was deprecated
Tasks with errors:
- IndicQARetrieval
- HotelReviewSentimentClassification
- TweetEmotionClassification
- TenKGnadClassification
- ArxivClassification
- PatentClassification
- FilipinoHateSpeechClassification
- MyanmarNews
- DutchBookReviewSentimentClassification
- SwedishSentimentClassification
- WisesightSentimentClassification
- UrduRomanSentimentClassification
- JSTS

Simple solution would be fix datasets version `<3.0`, but I'm not sure if it good.

**Comment by KennethEnevoldsen** [comment]
It is a good temp. fix. A better fix is to re-upload the datasets

**Comment by KennethEnevoldsen** [comment]
> Simple solution would be fix datasets version <3.0, but I'm not sure if it good.

That is a good temp. solution, but not a good long-term one. I think it is the right move right now though

**Comment by reneleonhardt** [comment]
@KennethEnevoldsen datasets 3.5 has been released, when is the [migration](https://github.com/huggingface/datasets/releases/tag/3.0.0) planned to apply all those improvements?
Time doesn't stand still, at least in the AI universe 😄

As a side note, it's sad that you have to use an unmaintained dependency like [salesforce-lavis](https://github.com/salesforce/LAVIS) and therefore had to [downgrade Python](https://github.com/embeddings-benchmark/mteb/pull/2323) 😞
Salesforce profits 2024: $26 billion

**Comment by Samoed** [comment]
We have fixed these datasets in `v2` branch

**Comment by reneleonhardt** [comment]
> We have fixed these datasets in `v2` branch

Nice!
