### ISSUE TITLE
CQA Retrieval Tasks file loading error

### ISSUE THREAD

**Issue by asparius** [embeddings-benchmark/mteb#147]
Beir==2.0.0
mteb==1.1.0

INFO:mteb.evaluation.MTEB:Loading dataset for CQADupstackEnglishRetrieval
INFO:beir.util:Unzipping cqadupstack.zip ...
ERROR:mteb.evaluation.MTEB:Error while evaluating CQADupstackEnglishRetrieval: File is not a zip file

**Comment by Muennighoff** [comment]
Hm works fine for me: https://colab.research.google.com/drive/18XXbYxYwHAV4sBIT_vO_WhRpGLGkN_f5?usp=sharing
maybe a corrupted download & just need to delete & retry

**Comment by asparius** [comment]
Yep, it worked but for those that will face it make sure that you delete it from the cache as well.
