### ISSUE TITLE
Expose get_model in README.md

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1497]
Currently the README.md (https://github.com/embeddings-benchmark/mteb/blob/main/README.md) never mentions the .get_model functionality; I think it would be great to mention it, maybe in a collapsible section!

**Comment by Samoed** [comment]
I updated it in https://github.com/embeddings-benchmark/mteb/pull/1493

**Comment by Samoed** [comment]
Added to readme and think this can be closed
