### ISSUE TITLE
NameError: name 'tasks' is not defined

### ISSUE THREAD

**Issue by moon09I980616I** [embeddings-benchmark/mteb#150]
### Discussed in https://github.com/embeddings-benchmark/mteb/discussions/148

<div type='discussions-op-text'>

<sup>Originally posted by **moon09I980616I** September  3, 2023</sup>
from mteb import MTEB
from sentence_transformers import SentenceTransformer

# Define the sentence-transformers model name
model_name = "average_word_embeddings_komninos"

model = SentenceTransformer(model_name)
evaluation = MTEB(tasks=["Banking77Classification"])
results = evaluation.run(model, output_folder=f"results/{model_name}")

hello. I am running the code using the mteb dataset. However, today, suddenly, at this part of "evaluation = MTEB(tasks=["Banking77Classification"])", an error occurs: "NameError: name 'tasks' is not defined." Can you tell me why?
The code above is the code I wrote accordingly.</div>

**Comment by Muennighoff** [comment]
```python
from mteb import MTEB
from sentence_transformers import SentenceTransformer
model_name = "average_word_embeddings_komninos"

model = SentenceTransformer(model_name)
evaluation = MTEB(tasks=["Banking77Classification"])
results = evaluation.run(model, output_folder=f"results/{model_name}")
```

The code above works fine for me

**Comment by KennethEnevoldsen** [comment]
@moon09I980616I, seems like this issue is stale. Will close it for now, but feel re-open it if you are still experiencing the issue.
