### ISSUE TITLE
Add minishlab models (model2vec)

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1503]
We have these in the results repo, but we do not have an implementation in the repo. These are also very good integration test models due to their very small size and low number of dependencies.
 
 'minishlab/M2V_base_glove',
 'minishlab/M2V_base_glove_subword',
 'minishlab/M2V_base_output',
[ 'minishlab/potion-base-2M',](https://huggingface.co/minishlab/potion-base-2M)
 'minishlab/potion-base-4M',
 'minishlab/potion-base-8M',
 

You can find the documentation on custom models [here](https://github.com/embeddings-benchmark/mteb?tab=readme-ov-file#using-a-custom-model) and you can find an example of an implementation [here](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/models/openai_models.py)

**Comment by KennethEnevoldsen** [comment]
@HadiaSamil will take a stab at this problem here

**Comment by KennethEnevoldsen** [comment]
related to https://github.com/embeddings-benchmark/mteb/issues/1515

**Comment by x-tabdeveloping** [comment]
These were added a week and a half ago
