### ISSUE TITLE
Odd column breaks on the leaderboard e.g.  the S of STS lands on a newline

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#1513]
Originally posted here: https://github.com/embeddings-benchmark/mteb/issues/1317#issuecomment-2504416638

Odd column breaks on the leaderboard e.g.  the S of STS lands on a newline:

<img width="1090" alt="Screenshot 2024-11-27 at 20 14 05" src="https://github.com/user-attachments/assets/b92a607e-657f-4a00-8dbb-9cf69820d54d">

**Comment by x-tabdeveloping** [comment]
working on it

**Comment by KennethEnevoldsen** [comment]
There is a button here:
https://www.gradio.app/docs/gradio/downloadbutton

Seems like it would get the job done if you pass it a file path

**Comment by x-tabdeveloping** [comment]
I fixed this
