### ISSUE TITLE
leaderboard 2.0: custom urls

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#1518]
would be great to have custom urls for each benchmark selection for the new leaderboard like we have for the current one e.g. https://huggingface.co/spaces/mteb/leaderboard?task=retrieval&language=bright

**Comment by x-tabdeveloping** [comment]
I looked into this, and unfortunately, it's a one way street. You can't modify the URL query parameters while people are browsing the leaderboard, which is a limitation of Gradio, I can't remember if I filed an issue on this but if not, we probably should.
On the other hand, we can totally parse query parameters.
I'm wondering if it would make sense to add a "Share" button or like a text field people can copy a link from, which leads to the current leaderboard they're looking at.

**Comment by KennethEnevoldsen** [comment]
It sounds like it would be doable just to have an entry point link for e.g. "the English MTEB", but which is not updated with selection.

**Comment by x-tabdeveloping** [comment]
Added in #1603
