### ISSUE TITLE
Add cost per token for APIs

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#1527]
I'm wondering if it would make sense to add the cost per token as metadata for embedding APIs so people can compare right at the leaderboard, which API solution might be the most cost effective for them.

**Comment by isaac-chung** [comment]
IMO pricing can change often and without warning. It is also dated, so would that mean each time pricing is changed, it should be tracked? or will only the latest pricing is fetched and shown?

I'd defer this unless there's strong signals from user asks, as there are more and higher priority items for us to take on. Though I'd say this could be something contributed from the community.

**Comment by KennethEnevoldsen** [comment]
I will close it for now, if someone wants to reopen it feel free to do so
