### ISSUE TITLE
DBPedia and HotPotQA scores are missing for almost all models

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#1549]
Currently, no models on the `MTEB(Classic)` leaderboard have a mean score, since these two tasks are missing from the main table, likely due to missing results.\
This is strange, since, in theory, old leaderboard scores were all scraped and added to the results repo.

**Comment by x-tabdeveloping** [comment]
I'm wondering if this is an error, or if we really mean to use all three as eval splits.

**Comment by Samoed** [comment]
In old leaderboard by default test split was used

**Comment by x-tabdeveloping** [comment]
I opened a PR #1554
