### ISSUE TITLE
MTEB Leaderboard

### ISSUE THREAD

**Issue by SantiDianaClibrain** [embeddings-benchmark/mteb#158]
Hi! I have a quick question. I am reproducing some results regarding the MTEB Leaderboard using the standard methodology you show in your README.md.

I have found that some models do not show the same performance when running that script against the results shown in the Leaderboard. Is every model shown in the leaderboard using a possible different version of the library? Is that being reviewed? Just to know if my calculus are wrong! Thanks!!

**Comment by SantiDianaClibrain** [comment]
By the way, the vast majority of the models show the same performance as is shown in the MTEB Leaderboard.

**Comment by Muennighoff** [comment]
Thanks for doing that!
There may be small differences depending on your Python / PyTorch versions, however, overall the scores should be very close to the ones in the leaderboard. If you see very large differences could you share them in more detail?

**Comment by SantiDianaClibrain** [comment]
Yeah! I am trying to evaluate on spanish benchmarks. I am basically running this: `evaluation = MTEB(task_langs=["es"])`, and here is a list of models that receive the same exact results:
- LaBSE
- sentence-t5-xl
- sentence-t5-large

Nevertheless, models such as multilingual-e5 (large, base and small) do give different results to me. What do you think about this? When talking about different, I am talking about more than 2 or 3 percentual points of difference.

**Comment by Muennighoff** [comment]
I see that may be because `LaBSE, sentence-t5-xl, sentence-t5-large` were run by me using MTEB & SentenceTransformers so the scores should be very easy to repro.

multilingual-e5 was run using this code I think: https://github.com/microsoft/unilm/tree/master/e5
Maybe you're not using the right code

**Comment by SantiDianaClibrain** [comment]
Nice! Thank you very much!!
