### ISSUE TITLE
The score_function is cos_sim() by default, when evaluating ColBert model in Retrieval task 

### ISSUE THREAD

**Issue by CZH-THU** [embeddings-benchmark/mteb#1589]
In mteb\evaluation\evaluators\RetrievalEvaluator.py:450. The score_function is cos_sim by default which will cause 
"File d:\ProgramData\Anaconda3\envs\embedding\lib\site-packages\mteb\evaluation\evaluators\utils.py:34, in cos_sim(a, b)      32 a_norm = torch.nn.functional.normalize(a, p=2, dim=1)      33 b_norm = torch.nn.functional.normalize(b, p=2, dim=1) ---> 34 return torch.mm(a_norm, b_norm.transpose(0, 1))  RuntimeError: self must be a matrix" when evaluating ColBert model in Retrieval task.
  The score_function should be  max_sim when the model is ColBert. Maybe score_function need be choosed by users.

**Comment by Samoed** [comment]
@sam-hey

**Comment by sam-hey** [comment]
Hello @CZH-THU, passing a ColBERT model directly is not supported and will default to cosine similarity, which results in an error.

You can refer to this example for guidance:
[Using Late Interaction Models for Retrieval](https://github.com/embeddings-benchmark/mteb?tab=readme-ov-file#using-late-interaction-models-for-retrieval)

**Comment by CZH-THU** [comment]
> Hello @CZH-THU, passing a ColBERT model directly is not supported and will default to cosine similarity, which results in an error.
> 
> You can refer to this example for guidance: [Using Late Interaction Models for Retrieval](https://github.com/embeddings-benchmark/mteb?tab=readme-ov-file#using-late-interaction-models-for-retrieval)
I use the demo （https://github.com/embeddings-benchmark/mteb?tab=readme-ov-file#using-late-interaction-models-for-retrieval） code:
'''
from mteb import MTEB
import mteb


colbert = mteb.get_model("colbert-ir/colbertv2.0")
tasks = mteb.get_tasks(tasks=["NFCorpus"], languages=["eng"])

eval_splits = ["test"]

evaluation = MTEB(tasks=tasks)

evaluation.run(
    colbert,
    eval_splits=eval_splits,
    corpus_chunk_size=500,
)
'''
but still result in error,I have figure it out by changing score_function.Maybe the demo code need be  modified
