### ISSUE TITLE
Unknown tasks: SummEval.

### ISSUE THREAD

**Issue by bm777** [embeddings-benchmark/mteb#159]
@Muennighoff I got a bad overall score on the leaderboard, I discovered that one task was missing SummEval.

### The script 

```bash
python scripts/run_mteb_english.py
```

### The Warning

```bash
INFO:main: Running task: SummEval
WARNING:mteb.evaluation.MTEB:WARNING: Unknown tasks: SummEval.
```

<img width="831" alt="Screenshot 2023-09-25 at 17 07 24" src="https://github.com/embeddings-benchmark/mteb/assets/29865600/f5bfd6a2-ef43-43d6-bb42-419d112b84cd">

### The score on the Summarisation task

![Screenshot 2023-09-25 at 17 15 27](https://github.com/embeddings-benchmark/mteb/assets/29865600/0b08c3ed-ee5b-4a7b-9ccc-282e719efc75)

I still don't understand why, Any explanation?

**Comment by Muennighoff** [comment]
Hmm that's weird; SummEval exists here: https://github.com/embeddings-benchmark/mteb/blob/4d75ddf448c93b4b879e60e110061f7dcf76ae42/mteb/tasks/Summarization/SummEvalSummarization.py#L4

Maybe try updating the version or running it directly

**Comment by DunZhang** [comment]
@bm777 @Muennighoff  Hi, same problem, add `from .SummEvalSummarization import *` to `mteb/tasks/Summarization/__init__.py`, problem solved

**Comment by Muennighoff** [comment]
Fixed it thanks (https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Summarization/__init__.py)! Seems like @NouamaneTazi somehow removed it in a previous commit  🤔

**Comment by bm777** [comment]
Exactly @Muennighoff, it was removed by him by mistake maybe 😉
In his previous [commit](https://github.com/embeddings-benchmark/mteb/blob/6a58b5d3b0c122d004de3f7476c1c169432208f5/mteb/tasks/Summarization/__init__.py)

**Comment by zanussbaum** [comment]
@Muennighoff can you release a new version on PyPi? Otherwise, we have to update the installed package each time if we want to use `SummEval`

**Comment by Muennighoff** [comment]
Yes! I will do it this week, sorry for the delay 👍

**Comment by zanussbaum** [comment]
Thank you!

**Comment by Muennighoff** [comment]
Released a new version - lmk if you encounter any issues in the new version!

**Comment by zanussbaum** [comment]
Thank you!
