### ISSUE TITLE
Benchmarks for Titan Embeddings

### ISSUE THREAD

**Issue by gsaivinay** [embeddings-benchmark/mteb#163]
Hello,

Please forgive me if I'm being ignorant. I'd like to ask if there are any evaluations done for AWS Bedrock Titan Embedding model. If not, how can I run the benchmark myself if assuming I have access. The Readme contains loading model with Sentence Transformer and I could find any info on using external model. Any hint/help would be much appreciated.

**Comment by Muennighoff** [comment]
Would be amazing if you could run it & add it to the leaderboard.

Below are some scripts for running APIs that may help for your reference
- Sionic
  - https://huggingface.co/sionic-ai/sionic-ai-v1/blob/main/mteb_evaluate.py
  - https://huggingface.co/sionic-ai/sionic-ai-v1/blob/main/model_api.py
- OpenAIV2: 
  - https://github.com/embeddings-benchmark/mtebscripts/blob/main/run_array_openaiv2.py

**Comment by gsaivinay** [comment]
I did some dirty hack to openai code in above reference link to caluclate one data set and got result below... I'm not sure but I'm assuming it is worse than `e5-large-v2`

I've difficulties running for longer periods (due to short ttl of assume-role)... I'll see what can I do


code changes:

```python
boto3_bedrock = bedrock.get_bedrock_client(
    assumed_role=os.environ.get("BEDROCK_ASSUME_ROLE", None),
    region=os.environ.get("AWS_DEFAULT_REGION", None)
)

from langchain.embeddings import BedrockEmbeddings
from langchain.llms.bedrock import Bedrock

bedrock_embeddings = BedrockEmbeddings(model_id="amazon.titan-embed-text-v1", client=boto3_bedrock)
```


```python
out = [[]] * len(batch)
                if all_tokens:
                    response = np.array(bedrock_embeddings.embed_documents(all_tokens))
                    # May want to sleep here to avoid getting too many requests error
                    # time.sleep(1)
                    assert len(response) == len(
                        all_tokens
                    ), f"Sent {len(all_tokens)}, got {len(response['data'])}"

                    idx = 0
                    for data in response:
                        embedding = data
                        out[idx] = embedding
                        idx += 1

                fin_embeddings.extend(out)
```


SciFact results:

```json
{
  "dataset_revision": null,
  "mteb_dataset_name": "SciFact",
  "mteb_version": "1.1.1",
  "test": {
    "evaluation_time": 996.91,
    "map_at_1": 56.761,
    "map_at_10": 68.491,
    "map_at_100": 69.049,
    "map_at_1000": 69.06,
    "map_at_3": 65.385,
    "map_at_5": 67.549,
    "mrr_at_1": 59.667,
    "mrr_at_10": 69.37,
    "mrr_at_100": 69.832,
    "mrr_at_1000": 69.842,
    "mrr_at_3": 67.333,
    "mrr_at_5": 68.617,
    "ndcg_at_1": 59.667,
    "ndcg_at_10": 73.5,
    "ndcg_at_100": 75.757,
    "ndcg_at_1000": 76.041,
    "ndcg_at_3": 68.558,
    "ndcg_at_5": 71.38,
    "precision_at_1": 59.667,
    "precision_at_10": 10,
    "precision_at_100": 1.107,
    "precision_at_1000": 0.113,
    "precision_at_3": 27.222,
    "precision_at_5": 18.467,
    "recall_at_1": 56.761,
    "recall_at_10": 87.933,
    "recall_at_100": 97.833,
    "recall_at_1000": 1.0,
    "recall_at_3": 74.756,
    "recall_at_5": 81.467
  }
}
```

**Comment by Muennighoff** [comment]
Nice that's strong performance; Need to run more datasets to get a comprehensive view - ideally run all of them

**Comment by KennethEnevoldsen** [comment]
This issue seem to have gotten stale so will close it
