### ISSUE TITLE
how to submit results for open ai models and similar ?

### ISSUE THREAD

**Issue by songsey** [embeddings-benchmark/mteb#167]
Hi, it seems like the results of the open ai model on the leader board are not from a huggingface repo. It leads to company websites. Where should I place the .md file ?

**Comment by Muennighoff** [comment]
Hi! You can open a PR here https://huggingface.co/datasets/mteb/results with your result files in a folder!
I will then merge it & link the model to where you want me to link it :)

**Comment by songsey** [comment]
Thansk pr was opened

**Comment by songsey** [comment]
could you restart your space so that it is visible ? thank you
