### ISSUE TITLE
Use MTEB evaluation via API

### ISSUE THREAD

**Issue by SantiDianaClibrain** [embeddings-benchmark/mteb#168]
Hello. I have a question. Can I use this library to evaluate embedding models via API? Or the models can just be HuggingFace models? Thank you in advance.

**Comment by Muennighoff** [comment]
Yes of course, you can refer to https://github.com/embeddings-benchmark/mteb/issues/163#issuecomment-1764699306

**Comment by SantiDianaClibrain** [comment]
Thank you very much!!

**Comment by KennethEnevoldsen** [comment]
Hi @SantiDianaClibrain, seems like this issue is resolved? I will close it, but feel free to open it if you have additional questions related to this issue.
