### ISSUE TITLE
How to add private model to mteb leaderboard

### ISSUE THREAD

**Issue by stanpcf** [embeddings-benchmark/mteb#182]
Hi guys,
thank for your great work for embedding model.
Now I have a private model which is accessible via an API (such as voyage). I want the result which is visible for everyone. what should I do. thanks.

**Comment by Muennighoff** [comment]
You can open a PR here: https://huggingface.co/datasets/mteb/results with the result files; Please also provide a link to your API

**Comment by stanpcf** [comment]
@Muennighoff thanks for your reply~
A PR and API is done with link https://huggingface.co/datasets/mteb/results/discussions/23
thanks for your great work.

**Comment by KennethEnevoldsen** [comment]
Hi @stanpcf, seems like this issue is resolved. Will close the PR, but feel free to open it if you have additional questions related to the issue.
