### ISSUE TITLE
Why those two links redirect to bioRxiv rather than Medrxiv?

### ISSUE THREAD

**Issue by zhimin-z** [embeddings-benchmark/mteb#184]
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/39b2f183-3894-4655-94c9-2915138c586c)

**Comment by Muennighoff** [comment]
Thanks for noticing! That's a mistake we should fix - do you want to submit a PR with a fix? :)

**Comment by zhimin-z** [comment]
> Thanks for noticing! That's a mistake we should fix - do you want to submit a PR with a fix? :)

Thanks, proposed!
check https://github.com/embeddings-benchmark/mteb/pull/187
