### ISSUE TITLE
The ms marco v2 dataset download link fail to redirect 

### ISSUE THREAD

**Issue by zhimin-z** [embeddings-benchmark/mteb#186]
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/9508b620-7041-4f58-b163-a0edf2a6b250)
https://huggingface.co/datasets/BeIR/msmarco-v2
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/d4d38e3c-d461-467f-bf38-ef30dc4ff19e)

**Comment by Muennighoff** [comment]
Thanks for noting! Hmm I'm not sure if it has been deleted - maybe we should link to the official MSMARCO v2 website then? If you want feel free to open a PR - would be amazing!

**Comment by zhimin-z** [comment]
> Thanks for noting! Hmm I'm not sure if it has been deleted - maybe we should link to the official MSMARCO v2 website then? If you want feel free to open a PR - would be amazing!

Thanks, but I am not sure where to locate it. I check the MTEB original paper but still get confused about the difference between v1 and v2 in terms of MSMARCO. Would you like to specify?

**Comment by KennethEnevoldsen** [comment]
This change is being addressed in #233. The new dataset can be found [here](https://huggingface.co/datasets/mteb/msmarco-v2).
