### ISSUE TITLE
SweFAQ seems to misdirect...

### ISSUE THREAD

**Issue by zhimin-z** [embeddings-benchmark/mteb#188]
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/1b5e4eec-3db3-49ee-b1a7-5d1fd800577a)
What is SweFAQ after all? I check the original MTEB paper but fail to locate its provenance:
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/8d5b5d49-72f8-4a56-a75f-f20d85844d29)
Currently, both URLs seem to be misdirected.
SweFAQ leads me to TREC-COVID, while another leads to me SuperLim.

**Comment by Muennighoff** [comment]
I think @KennethEnevoldsen added them - Could you correct the URLs?

**Comment by zhimin-z** [comment]
> I think @KennethEnevoldsen added them - Could you correct the URLs?

Is that this one: https://spraakbanken.gu.se/en/resources/swefaq?

**Comment by Muennighoff** [comment]
Yes I think so thanks!

**Comment by KennethEnevoldsen** [comment]
Sorry for the late response due to holidays, I will just confirm that it is indeed correct that SweFAQ is a part of SuperLIM (and that the link is correct).
