### ISSUE TITLE
Dalaj seems to misdirect

### ISSUE THREAD

**Issue by zhimin-z** [embeddings-benchmark/mteb#189]
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/3741c3bb-32a9-49be-ab80-554969134a6c)
It redirects me to SuperLim but it is misleading since it is only part of this large dataset...
Why not redirect to https://spraakbanken.gu.se/en/resources/dalaj-1-0 instead?

**Comment by Muennighoff** [comment]
Good point cc @KennethEnevoldsen 
Feel free to submit a PR with the updated link

**Comment by KennethEnevoldsen** [comment]
Agree directly linking to the dataset is better
