### ISSUE TITLE
Broken link for SummEval

### ISSUE THREAD

**Issue by zhimin-z** [embeddings-benchmark/mteb#190]
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/6a0e9904-4a87-4bc2-8d12-2267ae8b00e3)
Check the first column: https://tabilab.cmpe.boun.edu.tr/BIOSSES/DataSet.html
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/2c372a26-d919-4f49-8674-6a74ffa65f9e)

**Comment by Muennighoff** [comment]
Hmm for SummEval the link should probably be https://github.com/Yale-LILY/SummEval - Do you want to submit a PR?
