### ISSUE TITLE
Is it `MMarcoReranking` rather than `MMarcoRetrieval`?

### ISSUE THREAD

**Issue by zhimin-z** [embeddings-benchmark/mteb#191]
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/23426d6f-f0ce-4af9-bfe0-b84570d15496)

**Comment by Muennighoff** [comment]
Thanks I submitted a PR here https://github.com/FlagOpen/FlagEmbedding/pull/368

**Comment by KennethEnevoldsen** [comment]
Seems like this issue is resolved so will close it for now. Feel free to re-open it if it is not the case.
