### ISSUE TITLE
Which version is used for the retrieval?

### ISSUE THREAD

**Issue by zhimin-z** [embeddings-benchmark/mteb#192]
Unlike the reranking task of `CMedQA`, there is no specification of the version for this benchmark...
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/aed23eba-1634-4353-af65-a2f93a2f272b)
![image](https://github.com/embeddings-benchmark/mteb/assets/8592144/ebaeee5d-d2f7-46fa-b6d3-5ab5eae5d0b7)
Which version is used for the retrieval?

**Comment by Muennighoff** [comment]
Based on the number of samples I think CMedQAv2 is the same data as CmedqaRetrieval. Maybe @staoxiao can confirm

**Comment by zhimin-z** [comment]
> Based on the number of samples I think CMedQAv2 is the same data as CmedqaRetrieval. Maybe @staoxiao can confirm

Thanks, is that fine to make its name more explicit?

**Comment by staoxiao** [comment]
> Based on the number of samples I think CMedQAv2 is the same data as CmedqaRetrieval. Maybe @staoxiao can confirm

Yes, CmedqaRetrieval is v2.

**Comment by zhimin-z** [comment]
> > Based on the number of samples I think CMedQAv2 is the same data as CmedqaRetrieval. Maybe @staoxiao can confirm
> 
> Yes, CmedqaRetrieval is v2.

Thanks, can we make a pr to clearly clarify it in the names, so people won't get confused in the future? @staoxiao @Muennighoff

**Comment by KennethEnevoldsen** [comment]
I have added a specification in the dataset description in #886
