### ISSUE TITLE
CSV download or copy/paste of leaderboard?

### ISSUE THREAD

**Issue by turian** [embeddings-benchmark/mteb#200]
It's frustrating I can't copy-paste the leaderboard. Because of the JS toolkit, nodes disappear when you scroll.

Could you offer CSV download? Or copy/paste?

I just want to collect all the names

**Comment by Muennighoff** [comment]
Yeah, I think that should be doable, maybe you or @tomaarsen wants to open a PR to add Download buttons? Would be amazing!

**Comment by x-tabdeveloping** [comment]
I'm adding this feature to the new leaderboard right now.
