### ISSUE TITLE
Is it possible to add a custom task to leaderboard?

### ISSUE THREAD

**Issue by jingedawang** [embeddings-benchmark/mteb#201]
Thank you for open-source this fantastic project.

I want to evaluate the models for an address retrieval task. Is it possible to add this task to the leaderboard when I finished it?

Thank you!

**Comment by Muennighoff** [comment]
> Thank you for open-source this fantastic project.
> 
> I want to evaluate the models for an address retrieval task. Is it possible to add this task to the leaderboard when I finished it?
> 
> Thank you!

Yes of course, I am happy to add the task to the leaderboard after we have merged it into this repository if you open a PR 👍

**Comment by KennethEnevoldsen** [comment]
This issue seems to have been answered. Will close it
