### ISSUE TITLE
Full width layout

### ISSUE THREAD

**Issue by lasharela** [embeddings-benchmark/mteb#205]
I'm not sure if I'm opening this in right place, but is there a way to see table with full width? 

https://huggingface.co/spaces/mteb/leaderboard

<img width="1549" alt="image" src="https://github.com/embeddings-benchmark/mteb/assets/2189316/b45ac351-5af8-4087-b8e5-d29f2715159a">

Can't find a good way to see name of the models (this column needs to have a little more space)

**Comment by Muennighoff** [comment]
Hey, I'm not sure how to do that / if it's possible in Gradio; If you know how, a PR is very welcome / you can also ask Gradio, they know about the space: https://github.com/gradio-app/gradio/issues

**Comment by KennethEnevoldsen** [comment]
Will close this issue for now as it is probably not something we will get to in the near future.
