### ISSUE TITLE
Now there are some issues in MTEB huggingface leaderboard.

### ISSUE THREAD

**Issue by LeeSureman** [embeddings-benchmark/mteb#208]
![image](https://github.com/embeddings-benchmark/mteb/assets/32452367/c3e5271e-46ff-4e43-a9ac-93a540a884e8)
![image](https://github.com/embeddings-benchmark/mteb/assets/32452367/966f8afa-00e0-4fc0-b261-394790959439)
The issue is as shown in the figure above.

**Comment by Muennighoff** [comment]
Fixed it thanks for raising!
