### ISSUE TITLE
Encoding a dict instead of text in some retrieval tasks

### ISSUE THREAD

**Issue by avidale** [embeddings-benchmark/mteb#219]
When running MTEB on some tasks (they all seem to be instances of `BeIRPLTask`: ArguAna-PL, DBPedia-PL, FiQA-PL, HotpotQA-PL, MSMARCO-PL, NFCorpus-PL, NQ-PL, Quora-PL, SCIDOCS-PL, SciFact-PL, TRECCOVID-PL), the corpus to be encoded looks like a list of dicts: `[{"text": "blablabla", "title": "blah"}, ...]`. And my encoder chokes on these inputs, because it expects a list of strings.

For retrieval tasks in other languages, though, the corpus is a list of strings, just like my encoder expects.

Shouldn't we fix something in `BeIRPLTask` implementation?

**Comment by Muennighoff** [comment]
cc @kwojtasi

**Comment by avidale** [comment]
Here is how I reproduce the problem.

Code (implements a toy text encoder)

```Python
from mteb import MTEB
import numpy as np
from sklearn.feature_extraction.text import HashingVectorizer

class NonTrainableEmbedder():
    def __init__(self, dim=512):
        self.vectorizer = HashingVectorizer(
            analyzer='char_wb', n_features=dim, ngram_range=(1, 6), dtype=np.float32
        )
        self.vectorizer.fit([])
        
    def encode(self, sentences, batch_size=32, **kwargs):
        print(sentences[0]) # for debug purposes
        return self.vectorizer.transform(sentences).toarray()

model = NonTrainableEmbedder()
evaluation = MTEB(tasks=["FiQA-PL"])
evaluation.run(model)
```

The print output, representing the first input fed to the model:
```
{'text': 'Gdzie powinienem zaparkować mój fundusz na deszczowy dzień / awaryjny?'}
```

Resulting error when trying to process this input as a text:
```
File ~/.conda/envs/isc2/lib/python3.8/site-packages/sklearn/feature_extraction/text.py:68, in _preprocess(doc, accent_function, lower)
     49 """Chain together an optional series of text preprocessing steps to
     50 apply to a document.
     51 
   (...)
     65     preprocessed string
     66 """
     67 if lower:
---> 68     doc = doc.lower()
     69 if accent_function is not None:
     70     doc = accent_function(doc)

AttributeError: 'dict' object has no attribute 'lower'
```

**Comment by avidale** [comment]
@Muennighoff  @kwojtasi up

**Comment by kwojtasi** [comment]
@avidale Looking into it!

**Comment by kwojtasi** [comment]
I have created pull request, it seems I missed it at the beginning because the tokenizer from SentenceTransformers does the job and takes the "text" from the dictionary  `{"text" : "Some sample text"}`.  So this was working fine:
`from mteb import MTEB
from mteb.abstasks import BeIRPLTask
from sentence_transformers import SentenceTransformer

# Define the sentence-transformers model name
model_name = "intfloat/multilingual-e5-base"

model = SentenceTransformer(model_name, device="cuda:1")
evaluation = MTEB(tasks=["SciFact-PL"])
evaluation.run(model)`

**Comment by Muennighoff** [comment]
Merged, nice! Btw it'd be very cool to also have the still missing BEIR-PL tasks at some point if you want @kwojtasi 🙌

**Comment by avidale** [comment]
If I understood correctly, SentenceTransformers, [when fed a dict, use the first field in this dict](https://github.com/UKPLab/sentence-transformers/blob/a1ed49cb24a54f2d364393905ad372a57c70dc35/sentence_transformers/models/Transformer.py#L123) as the text input
```
        elif isinstance(texts[0], dict):
            to_tokenize = []
            output["text_keys"] = []
            for lookup in texts:
                text_key, text = next(iter(lookup.items()))
                to_tokenize.append(text)
```
Are we ok with this behaviour? What happens when the input dict has both `title` and `text` fields; do we embed only title?

**Comment by Muennighoff** [comment]
> If I understood correctly, SentenceTransformers, [when fed a dict, use the first field in this dict](https://github.com/UKPLab/sentence-transformers/blob/a1ed49cb24a54f2d364393905ad372a57c70dc35/sentence_transformers/models/Transformer.py#L123) as the text input
> 
> ```
>         elif isinstance(texts[0], dict):
>             to_tokenize = []
>             output["text_keys"] = []
>             for lookup in texts:
>                 text_key, text = next(iter(lookup.items()))
>                 to_tokenize.append(text)
> ```
> 
> Are we ok with this behaviour? What happens when the input dict has both `title` and `text` fields; do we embed only title?

I think it is not passed as a dict to SentenceT cuz it's concatted first here: https://github.com/embeddings-benchmark/mteb/blob/def3c9146ff437d4b9bb690dea183070ccb36a7f/mteb/abstasks/AbsTaskRetrieval.py#L152
