### ISSUE TITLE
task_langs don't work when task is specified

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#23]
>>> valuation = MTEB(tasks=["AmazonCounterfactualClassification"],task_langs=["zh"])
>>> valuation.run(model)

Task: AmazonCounterfactualClassification, split: validation, language: en. Running...
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>

**Comment by NouamaneTazi** [comment]
`AmazonCounterfactualClassification` only supports [these languages](https://github.com/embeddings-benchmark/mteb-draft/blob/39d0926ee3f2f094e843eab7cd16b762244c2183/mteb/tasks/Classification/AmazonCounterfactualClassification.py#L4), and `zh` is not one of them. So in this case, the evaluation runs on all the languages for AmazonCounterfactualClassification.

Can you provide a better Traceback for your error?

**Comment by Muennighoff** [comment]
Yeah I think we shouldn't run any if it's not supported & just log a warning that nothing was found for the language

**Comment by NouamaneTazi** [comment]
Agreed. We can also make that validation stricter by not generating language pairs ourselves (for example `["zh", "en"] ->  ["zh", "en", "zh-en", "en-zh"] `) and leave it to the user to precise which language they want.

Feel free to open a PR for this, or else I can make one as soon as I can :)

**Comment by KennethEnevoldsen** [comment]
For people finding this issue, we how now deprecated the MTEB (at the moment only gives a warning) the interface: 

```
MTEB(tasks=["AmazonCounterfactualClassification"],task_langs=["zh"])
```
and instead recommend using the 
```
tasks = mteb.get_tasks(tasks=["AmazonCounterfactualClassification"], languages=["eng"])
eval = MTEB(tasks=tasks)
eval.run(model)
```
