### ISSUE TITLE
Chinese leaderboard crashed frequently?

### ISSUE THREAD

**Issue by Jeru2023** [embeddings-benchmark/mteb#231]
I guessed someone submitted new model causing rerun? if this is the case please consider set overwrite_rule to false

**Comment by Muennighoff** [comment]
the leaderboard is working fine for me https://huggingface.co/spaces/mteb/leaderboard

**Comment by Jeru2023** [comment]
Yes now it's fine, a couple hours before it's empty, although I reloaded many times, seems there two new models running yesterday, I not not sure if the process will trigger all models rerun or just rerun the new models

**Comment by KennethEnevoldsen** [comment]
@Muennighoff as I understand the leaderboard does not run any models it only presents scores of models already run.

**Comment by KennethEnevoldsen** [comment]
will close this, if it is still a problem feel free to reopen
