### ISSUE TITLE
Metric explaination

### ISSUE THREAD

**Issue by Jeru2023** [embeddings-benchmark/mteb#232]
For each task in leaderboard there is only one overview score, while the generated result file contains dozens indicators such as:
mrr_at_1000
ndcg_at_1000
map_at_1000
precision_at_1000
recall_at_1000

1. how's the overview score calculated?
2. mrr_at_1000, mrr_at_500 - what's the last number stands for?
3. 
Please kindly help

**Comment by Muennighoff** [comment]
overview score is an average of the individual task leaderboard scores
the number refers to how many top documents are considered for scoring

**Comment by Jeru2023** [comment]
> overview score is an average of the individual task leaderboard scores the number refers to how many top documents are considered for scoring

the number refers to how many top documents are considered for scoring - I'm trying to understand, are you saying that number is actually the top-k param in similarity search? so the bigger the number the better the hit rate?

For overview score, it's just one figure, but in the evaluation result file that are multiple indicators and each indicator concat with different numbers, how to calculate the overview score when I'm using my own dataset?

**Comment by Jeru2023** [comment]
@imenelydiaker Thanks for such a detail reply, much appreciate.

**Comment by KennethEnevoldsen** [comment]
@Jeru2023 seems like this is resolved so will close it.
