### ISSUE TITLE
Warning for benchmarking all datasets constituting the MTEB Semantic Text Similarity (STS) French leaderboard.

### ISSUE THREAD

**Issue by LeMoussel** [embeddings-benchmark/mteb#237]
I want to evaluate some french embeddings models using MTEB Semantic Text Similarity (STS) task.
To do this, I took inspiration from this code [run_mteb_french.py](https://github.com/embeddings-benchmark/mteb/blob/main/scripts/run_mteb_french.py)
```python
  import logging

  from sentence_transformers import SentenceTransformer
  from mteb import MTEB

  logging.basicConfig(level=logging.INFO)
  logger = logging.getLogger("main")

  # https://huggingface.co/dangvantuan/sentence-camembert-large
  model_name = "dangvantuan/sentence-camembert-large"
  model = SentenceTransformer(model_name)

   TASK_LIST_STS = [
        "SummEvalFr",
        "STSBenchmarkMultilingualSTS",
        "STS22",
        "SICKFr"
    ]
    
    for task in TASK_LIST_STS:
      logger.info(f"Running task: {task}")
      evaluation = MTEB(tasks=[task], task_langs=["fr"]) 
      evaluation.run(model, output_folder=f"fr_results/{model_name}")
```
while running I have this warning about unknown tasks `SummEvalFr`, `STSBenchmarkMultilingualSTS`
 & `SICKFr`.

`WARNING:mteb.evaluation.MTEB:WARNING: Unknown tasks: SummEvalFr. Known tasks: 8TagsClustering,AFQMC,ATEC,AllegroReviews,AmazonCounterfactualClassification,AmazonPolarityClassification,AmazonReviewsClassification,AngryTweetsClassification,.....`

It seems that only task "STS22" is available.
What should I do ? 
Do we have any errors in [run_mteb_french.py](https://github.com/embeddings-benchmark/mteb/blob/main/scripts/run_mteb_french.py)?

**Comment by Muennighoff** [comment]
Hey did you install MTEB from source via `pip install git+https://github.com/embeddings-benchmark/mteb.git`? They are not yet in the latest release

**Comment by LeMoussel** [comment]
No, I installed MTEB from PyPi.
By installing from source: `pip install git+https://github.com/embeddings-benchmark/mteb.git`, It's OK.

**Python Test code:**
``` python
from mteb import MTEB
from sentence_transformers import SentenceTransformer

model_name = 'OrdalieTech/Solon-embeddings-base-0.1'
model = SentenceTransformer(model_name)

evaluation = MTEB(task_types=['STS'], task_langs=["fr"])
evaluation.run(model, output_folder=f"fr_results/{model_name}")
```
**Output:**
```
STS
    - SICKFr, s2s
    - STS22, p2p, crosslingual 1 / 18 pairs
    - STSBenchmarkMultilingualSTS, s2s, multilingual 1 / 10 langs
....
```

So what does `s2s`, `p2p` mean?

**Comment by Muennighoff** [comment]
Great! Those are explained here: https://github.com/embeddings-benchmark/mteb?tab=readme-ov-file#dataset-selection essentially it relates to the length :)
