### ISSUE TITLE
Strange reranking eval result

### ISSUE THREAD

**Issue by Jeru2023** [embeddings-benchmark/mteb#238]
I performed a reranking task on MMacroReranking dataset with bge-reranker-large, the result looks fine to me.
but when I switch to bge-large evaluating the same dataset, its result seems unreasonable, any clue?

bge-reranker-large eval result
```
{
  "dataset_revision": "8e0c766dbe9e16e1d221116a3f36795fbade07f6",
  "dev": {
    "evaluation_time": 33091.37,
    "map": 0.37640824211259494,
    "mrr": 0.36576587301587304
  },
  "mteb_dataset_name": "MMarcoReranking",
  "mteb_version": "1.1.2"
}
```

bge-large-zh-v1.5 eval result
```
{
  "dataset_revision": "8e0c766dbe9e16e1d221116a3f36795fbade07f6",
  "dev": {
    "evaluation_time": 39180.88,
    "map": 0.006013297204484398,
    "mrr": 0.0
  },
  "mteb_dataset_name": "MMarcoReranking",
  "mteb_version": "1.1.2"
}
```

**Comment by Muennighoff** [comment]
cc @staoxiao

**Comment by staoxiao** [comment]
The loading methods of reranker and embedding model are different. You can refer to this [script](https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/eval_C-MTEB.py#L31) to evaluate bge embedding model.

**Comment by KennethEnevoldsen** [comment]
This seems to resolve the issue. Will close it.
