### ISSUE TITLE
ada not in mteb?

### ISSUE THREAD

**Issue by Jeru2023** [embeddings-benchmark/mteb#239]
I'm curious why ada-embedding is not in the model list in MTEB?
Is there any particular reason?

**Comment by Muennighoff** [comment]
Do you mean the leaderboard? If so the OpenAI ada 1, ada 2 and their third embedding model are there I think

**Comment by Jeru2023** [comment]
> Do you mean the leaderboard? If so the OpenAI ada 1, ada 2 and their third embedding model are there I think

Yes, I mean ADA is not shown in the leaderboard.
I just went through 153 models in English leaderboard again but still couldn't find it.
For Chinese leaderboard, I can't verify yet as it's currently empty.

**Comment by Muennighoff** [comment]
Attached are some screenshots from the leaderboard - The models are there?
<img width="638" alt="Screenshot 2024-03-04 at 5 39 39 AM" src="https://github.com/embeddings-benchmark/mteb/assets/62820084/b941d1f3-2130-40e3-86f9-ad32e9fc68d0">
<img width="689" alt="Screenshot 2024-03-04 at 5 40 19 AM" src="https://github.com/embeddings-benchmark/mteb/assets/62820084/24f50511-d571-4e24-b3b8-849ae0aa79cf">
<img width="688" alt="Screenshot 2024-03-04 at 5 40 44 AM" src="https://github.com/embeddings-benchmark/mteb/assets/62820084/1761b2c2-d2d7-48cc-a720-71c9c97a177d">

**Comment by Jeru2023** [comment]
@Muennighoff Thanks to your kind reply, it's my bad. I didn't realized that text-embedding-3 is actually also ada.

**Comment by KennethEnevoldsen** [comment]
@Jeru2023 seems like this resolves the issue, I will close it for now, but feel free to re-open if that is not the case.
