### ISSUE TITLE
MTEB leaderboard Retrieval task numbers issue

### ISSUE THREAD

**Issue by shivrajjadhav733** [embeddings-benchmark/mteb#240]
I see an overall problem with numbers on leaderboard.
I am trying few models on Retrieval task type with SciFact dataset for English Language. 

I am using sample example from readme.

`

from mteb import MTEB
from sentence_transformers import SentenceTransformer

model_name = "infrastructure/Stella-base-en-v2"

model = SentenceTransformer(model_name)
evaluation = MTEB(tasks=["SciFact-PL"], task_langs=[“en”])
results = evaluation.run(model, output_folder=f"results/{model_name}")

`

The results json output file has ndcg_at_10 showing values like 0.35 or 0.36

I tried variety of different models and the numbers listed on leaderboard are about 72 or 74 etc. 

So there is huge difference in the number got thru running script.

I have tried it on MacOS(M1 chip) as well as AWS EC2 g5 instance (Ubuntu 22).
The results are almost similar but they are way off when compared to leaderboard.

is there a specific way to read the results.json against leaderboard numbers?

**Comment by shivrajjadhav733** [comment]
Sample output results json file for model ‘Stella-base-en-v2’
![151720DE-8C44-42BD-9A18-35D3C47B585E](https://github.com/embeddings-benchmark/mteb/assets/35407279/1f4ec1d5-af47-488e-a5a5-db9ae004beed)

**Comment by imenelydiaker** [comment]
I think you're just comparing two evaluations from different languages... `SciFact-PL` is for Polish, you're comparing it to English evaluation on `SciFact`. 

For English you should run: 
`evaluation = MTEB(tasks=["SciFactRetrieval"], task_langs=["en"])`
You should be able to recover the same results as in the leaderboard here (as @Muennighoff  mentionned scores are multiplied by 100 on the leaderboard).

For Polish you should run: 
`evaluation = MTEB(tasks=["SciFactPLRetrieval"], task_langs=["pl"])`
The model you're evaluating is not present in the Polish leaderboard.

**Comment by shivrajjadhav733** [comment]
@imenelydiaker Thanks.
It worked. Task name should just be ‘SciFact’ for English. 
result value came out to be 0.72506
