### ISSUE TITLE
ValueError: Found array with dim 3. LogisticRegression expected <= 2.

### ISSUE THREAD

**Issue by ozoMain** [embeddings-benchmark/mteb#241]
Hi, can you help me, please? I run the following code and get an ValueError: Found array with dim 3. LogisticRegression expected <= 2.

```python
class MyModel():
    def encode(self, sentences, batch_size=32, **kwargs):
        padding = torch.nn.ZeroPad2d((0,0,0,512))

        def encode_seq(seq):
            return padding(torch.tensor(
                    [w2v.get_vector(token).tolist() if token in w2v else np.ones(100)
                    for token in tokenize(seq)]
                ))[:512]

        def encode_batch(batch):
            return [encode_seq(seq) for seq in batch]

        return encode_batch(sentences)

model = MyModel()
evaluation = MTEB(tasks=["Banking77Classification"])
evaluation.run(model)
```

**Comment by ozoMain** [comment]
Oooops, I'm sorry for the curvature

**Comment by ozoMain** [comment]
Тогда есть еще один вопрос) Как правильно вставить сюда код?

**Comment by imenelydiaker** [comment]
Hello,

I have some trouble understanding your code.  Can you please give us more details: 
1. What are you trying to do ? Are you using `gensim` to get `word2vec` word embeddings ?
2. What's the error message you're getting ? (copy paste it please)

**Comment by ozoMain** [comment]
1. I'm trying to evaluate a "custom" model, and yes i using `gensim` to get `word2vec` embeddings
2. ```
Classification
    - Banking77Classification, s2s

ERROR:mteb.evaluation.MTEB:Error while evaluating Banking77Classification: Found array with dim 3. LogisticRegression expected <= 2.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-47-53338dcfd6d4> in <cell line: 28>()
     26 model = MyModel()
     27 evaluation = MTEB(tasks=["Banking77Classification"])
---> 28 evaluation.run(model)

8 frames
/usr/local/lib/python3.10/dist-packages/mteb/evaluation/MTEB.py in run(self, model, verbosity, output_folder, eval_splits, overwrite_results, raise_error, **kwargs)
    287                 logger.error(f"Error while evaluating {task.description['name']}: {e}")
    288                 if raise_error:
--> 289                     raise e
    290                 logger.error(f"Please check all the error logs at: {self.err_logs_path}")
    291                 with open(self.err_logs_path, "a") as f_out:

/usr/local/lib/python3.10/dist-packages/mteb/evaluation/MTEB.py in run(self, model, verbosity, output_folder, eval_splits, overwrite_results, raise_error, **kwargs)
    269                 for split in task_eval_splits:
    270                     tick = time()
--> 271                     results = task.evaluate(model, split, output_folder=output_folder, **kwargs)
    272                     tock = time()
    273                     logger.info(f"Evaluation for {task.description['name']} on {split} took {tock - tick:.2f} seconds")

/usr/local/lib/python3.10/dist-packages/mteb/abstasks/AbsTaskClassification.py in evaluate(self, model, eval_split, train_split, **kwargs)
     53         else:
     54             logger.info(f"\nTask: {self.description['name']}, split: {eval_split}. Running...")
---> 55             scores = self._evaluate_monolingual(model, self.dataset, eval_split, train_split, **kwargs)
     56             self._add_main_score(scores)
     57 

/usr/local/lib/python3.10/dist-packages/mteb/abstasks/AbsTaskClassification.py in _evaluate_monolingual(self, model, dataset, eval_split, train_split, **kwargs)
     88                 raise ValueError(f"Method {self.method} not supported")
     89 
---> 90             scores_exp, test_cache = evaluator(model, test_cache=test_cache)
     91             scores.append(scores_exp)
     92 

/usr/local/lib/python3.10/dist-packages/mteb/evaluation/evaluators/ClassificationEvaluator.py in __call__(self, model, test_cache)
    217             X_test = test_cache
    218         logger.info("Fitting logistic regression classifier...")
--> 219         clf.fit(X_train, self.y_train)
    220         logger.info("Evaluating...")
    221         y_pred = clf.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py in fit(self, X, y, sample_weight)
   1194             _dtype = [np.float64, np.float32]
   1195 
-> 1196         X, y = self._validate_data(
   1197             X,
   1198             y,

/usr/local/lib/python3.10/dist-packages/sklearn/base.py in _validate_data(self, X, y, reset, validate_separately, **check_params)
    582                 y = check_array(y, input_name="y", **check_y_params)
    583             else:
--> 584                 X, y = check_X_y(X, y, **check_params)
    585             out = X, y
    586 

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py in check_X_y(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)
   1104         )
   1105 
-> 1106     X = check_array(
   1107         X,
   1108         accept_sparse=accept_sparse,

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator, input_name)
    913             )
    914         if not allow_nd and array.ndim >= 3:
--> 915             raise ValueError(
    916                 "Found array with dim %d. %s expected <= 2."
    917                 % (array.ndim, estimator_name)

ValueError: Found array with dim 3. LogisticRegression expected <= 2.```

**Comment by imenelydiaker** [comment]
I think that there's is a problem with your vectors dimensions.
Word2Vec builds a vector for each token, which means that you're getting for your sentence a vector of 3 dimensions `(batch, seq_len_ hidden_dim)` instead of the expeced 2D vectors `(batch, hidden_dim)`. The classification task of MTEB expects one vector per sentence, so a 2D list of vectors.

**Comment by ozoMain** [comment]
aaaah MTEB for evaluating embeddings of sequences, not individual tokens, understood, thank you. Or can you tell me the benchmark for the purchase of tokens, if there is one?

**Comment by imenelydiaker** [comment]
Sorry, I don't have in mind a benchmark for purchase orders if that's what you're looking for. There exist datasets on invoices and receipts, for the information extraction task. Maybe you can have a look at this [link](https://paperswithcode.com/datasets?mod=texts&task=named-entity-recognition-ner) and try to find what suits you best.

**Comment by ozoMain** [comment]
Sorry, it's a Google translator. Is there a benchmark for evaluate token embeddings?

**Comment by imenelydiaker** [comment]
> Sorry, it's a Google translator. Is there a benchmark for evaluate token embeddings?

Nothing comes to my mind sorry. Generally token embeddings models are evaluated on downstream tasks, like Question-Answering. There is a benchmark called GLUE that is commonly used to evaluated embedders. You can refer to the [BERT paper](https://arxiv.org/abs/1810.04805) and see how they evaluated their model.

**Comment by ozoMain** [comment]
Thank you for your time!

**Comment by KennethEnevoldsen** [comment]
@ozoMain it seems like this resolves this issue, feel free to open it up again if you have more related questions.
