### ISSUE TITLE
READEME should be updated

### ISSUE THREAD

**Issue by archersama** [embeddings-benchmark/mteb#242]
READEME should be updated, DRESModel at mteb/mteb/abstasks/AbsTaskRetrieval.py about how to encode_query as well as encode_corpus has been modified and deleted

**Comment by loicmagne** [comment]
Thanks for notifying, DRESModel has been moved to https://github.com/embeddings-benchmark/mteb/blob/96103788cd135caecdb439b5d26af38ab6cd33ef/mteb/evaluation/evaluators/RetrievalEvaluator.py#L99 

I've modified the README accordingly
