### ISSUE TITLE
Structure of mteb/tasks

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#243]
Currently the structure of `mteb/tasks` is: 

`mteb/tasks/{task_type}/{task_name}`.

This has become a bit unruly given the large number of datasets available. I was hoping to propose the structure:

`mteb/tasks/{task_type}/{language}/{task_name}`.

Alternatively, we could also do (though I believe the other approach is better as it follows the existing structure):
`mteb/tasks/{language}/{task_type}/{task_name}`.

Where language is the language (en, fr, nl, da, sv) of the specific task. We can additionally add a "multilingual" folder for multilingual tasks. 

This would make it easier to search for datasets and see if the datasets exist within a target language.

**Comment by Muennighoff** [comment]
I think `mteb/tasks/{task_type}/{language}/{task_name}` w/ one `multilingual` folder where needed is good!
