### ISSUE TITLE
How to get the leaderboard score without adding metadata?

### ISSUE THREAD

**Issue by Hannibal046** [embeddings-benchmark/mteb#244]
Hi, Teams,
Thanks so much for the great work! I am currently evaluating a very old embedding model (facebook-dpr-ctx_encoder-multiset-base) on MTEB. Following the instruction, I have successfully got the `mteb_metadata.md` file. However, since `facebook-dpr-ctx_encoder-multiset-base` is not an active repo anyone, adding information from `metb_metadata.md` to the `README.md` is not feasible.

So my question is, how to get the leaderboard score without adding metadata to a model's `README.md` file?

This is the `mteb_metadata.md` I got:
[mteb_metadata.md](https://github.com/embeddings-benchmark/mteb/files/14609837/mteb_metadata.md)

**Comment by Muennighoff** [comment]
You can open a PR here: https://huggingface.co/datasets/mteb/results :)

**Comment by Hannibal046** [comment]
Done. https://huggingface.co/datasets/mteb/results/discussions/32

Thanks so much!

**Comment by Muennighoff** [comment]
> Done. https://huggingface.co/datasets/mteb/results/discussions/32
> 
> Thanks so much!

Oh sorry not with the metadata but with the result files in a folder similar to the other results in there

**Comment by Hannibal046** [comment]
Modified
