### ISSUE TITLE
docs: document schema for datasets in tasks

### ISSUE THREAD

**Issue by MartinBernstorff** [embeddings-benchmark/mteb#250]
When I added #247, it was non-obvious for me which columns a dataset should contain.

I propose documenting this at the `AbsTask` level, e.g. for classification something like:

```python
class AbsTaskClassification(AbsTask):
    """
    Abstract class for kNN classification tasks
    The similarity is computed between pairs and the results are ranked. 
    
    Dataset must be a huggingface dataset split into train/test, and contain the following columns:
        text: str
        label: int
    """

**Comment by imenelydiaker** [comment]
> When I added #247, it was non-obvious for me which columns a dataset should contain.
> 
> I propose documenting this at the `AbsTask` level, e.g. for classification something like:
> 
> ```python
> class AbsTaskClassification(AbsTask):
>     """
>     Abstract class for kNN classification tasks
>     The similarity is computed between pairs and the results are ranked. 
>     
>     Dataset must be a huggingface dataset split into train/test, and contain the following columns:
>         text: str
>         label: int
>     """
> ```

I completely agree with you! We ran into the same issue when creating the benchmark for French. We should add a doctring like this one for each task type maybe 🤔

**Comment by MartinBernstorff** [comment]
Strong agree. I'd gladly take on part of this work 👍

**Comment by KennethEnevoldsen** [comment]
Perfect @MartinBernstorff will assign it to you
