### ISSUE TITLE
Autogenerate table of tasks

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#252]
Seems like the table of tasks can be autogenerated from the existing metadata. 

I would suggest removing it from the readme and then linking to a new autogenerated markdown.

What are some thoughts on this?

**Comment by MartinBernstorff** [comment]
In the same vein, I'd love if the metadata was a dataclass as well. This makes it easy to:
* Type-hint the attributes
* Auto-complete in IDEs
* Get runtime-errors if keys are missing

**Comment by imenelydiaker** [comment]
> Seems like the table of tasks can be autogenerated from the existing metadata.
> 
> I would suggest removing it from the readme and then linking to a new autogenerated markdown.
> 
> What are some thoughts on this?

Yep let's go! Autogeneration >>> manual generation 🚀

**Comment by KennethEnevoldsen** [comment]
Wonderful glad we agree! Will see if I can find the time to implement it

**Comment by KennethEnevoldsen** [comment]
This PR awaits #260. 
@MartinBernstorff Since the table contains the size of the datasets and it would be problematic to fetch all datasets to generate it, it might be ideal to the dataset sizes to the metadata. What do you think?

**Comment by MartinBernstorff** [comment]
Makes a lot of sense. There might be some work in formalising what "size" means for each task type, but let's cross that bridge when we get there!

**Comment by KennethEnevoldsen** [comment]
<img width="575" alt="Screenshot 2024-03-20 at 09 41 21" src="https://github.com/embeddings-benchmark/mteb/assets/23721977/b2ee55fb-ebbd-4d8b-bccb-94beec9b3961">

^was just thinking of this

**Comment by HLasse** [comment]
This seems to be fixed by #525 and #541 . Should it be closed?
