### ISSUE TITLE
dev: most files are not formatted

### ISSUE THREAD

**Issue by MartinBernstorff** [embeddings-benchmark/mteb#256]
I just ran `make style` and got:

```
All done! ✨ 🍰 ✨
73 files reformatted, 188 files left unchanged.
```

This means that PRs that touch unformatted files, e.g. #255, end up with diffs that are unrelated semantically to what was changed.

I'd recommend to:
* Land as many PRs as possible
* Make a PR formatting all files
* Set up formatting as part of CI

What do you think? @KennethEnevoldsen, @Muennighoff

**Comment by Muennighoff** [comment]
Agreed, great point!

**Comment by MartinBernstorff** [comment]
I ran it in #260, so this should be fixed now!
