### ISSUE TITLE
Task description metadata as dataclass

### ISSUE THREAD

**Issue by MartinBernstorff** [embeddings-benchmark/mteb#257]
I'd love if the metadata was a dataclass as well. This makes it easy to:
* Type-hint the attributes
* Auto-complete in IDEs
* Get runtime-errors if keys/attributes are missing

**Comment by KennethEnevoldsen** [comment]
@imenelydiaker and @Muennighoff what are your thoughts here?

I am generally good with a dataclass. Alternatively, we can keep it as a "typedDict" or type check it during tests.

**Comment by imenelydiaker** [comment]
> @imenelydiaker and @Muennighoff what are your thoughts here?
> 
> I am generally good with a dataclass. Alternatively, we can keep it as a "typedDict" or type check it during tests.

Both are good for me, I let you choose the easiest one to use 😄

**Comment by Muennighoff** [comment]
> > @imenelydiaker and @Muennighoff what are your thoughts here?
> > I am generally good with a dataclass. Alternatively, we can keep it as a "typedDict" or type check it during tests.
> 
> Both are good for me, I let you choose the easiest one to use 😄

Same, I'm not too familiar with the trade-offs & trust your judgement - I'd just focus on maximizing ease of use + minimizing complexity (i.e. minimizing the lines of code)

**Comment by KennethEnevoldsen** [comment]
As I see it the trade-offs are between using a data class and getting more robust metadata (as it is validated) or using simpler Python primitives (dicts). More robust metadata of course makes the chance the user encounters a bug less likely, especially when we are gonna have a lot of new contributors.

@MartinBernstorff do you want to discuss this f2f once you are free?

**Comment by MartinBernstorff** [comment]
Have made a first draft in #260.
