### ISSUE TITLE
Regarding the process of submitting results to the leaderboard and the verification of metric authenticity

### ISSUE THREAD

**Issue by AugustLHHHHHH** [embeddings-benchmark/mteb#259]
Hi,

Thank you for sharing the leaderboard evaluation code.

I am currently trying to submit evaluation results following the steps in this [link ](https://github.com/embeddings-benchmark/mteb?tab=readme-ov-file#leaderboard), but there are two points that I'm not quite clear about and I would like to ask for your guidance:

Question 1: In step 3, after copying the results from the .md file to the readme file in the hub, how does the leaderboard collect my results? Why does clicking "Refresh" on the leaderboard allow the data to be retrieved?

Question 2: The test results are submitted after local testing. How do ensure the authenticity of the metrics? Does the leaderboard have a process for reviewing and replicating the results? What if a submitter maliciously modifies some metrics?

Of course, many authors have already open-sourced their models, and I believe that no one would modify them maliciously. I just recently learned about the leaderboard, so I am curious about whether there is a result review process. In some competitions I have previously participated in, such as on Kaggle, not only are we required to submit metrics, but we also need to submit results for auxiliary verification of these metrics.(Hope this question is not offensive)

Thank you.

**Comment by Muennighoff** [comment]
Thanks for your interest! :)

1) See https://huggingface.co/spaces/mteb/leaderboard/blob/8342bdf786af6742a79b22090a03a17c8b2d2fe7/app.py#L1132

2) There's no automatic testing but (i) The community is quick to test models and check them on some benchmarks - errors etc. can be pointed out in the community tab or here on github (ii) The incentives strongly work against cheating to avoid loss of reputation as once someone tests it, it would be discovered anyways

**Comment by AugustLHHHHHH** [comment]
> Thanks for your interest! :)
> 
> 1. See https://huggingface.co/spaces/mteb/leaderboard/blob/8342bdf786af6742a79b22090a03a17c8b2d2fe7/app.py#L1132
> 2. There's no automatic testing but (i) The community is quick to test models and check them on some benchmarks - errors etc. can be pointed out in the community tab or here on github (ii) The incentives strongly work against cheating to avoid loss of reputation as once someone tests it, it would be discovered anyways

Thank you for your timely response and contributions to the community.

**Comment by KennethEnevoldsen** [comment]
Hi @AugustLHHHHHH I assume this issue is resolved so will close it.
