### ISSUE TITLE
CI: Automatic release workflow

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#261]
It might be ideal to set up an automatic release schedule to pipy as well as automatic version bump.

This requires us to make a few decisions:

1) Decide on a versioning style, we can use either [SemVer](https://semver.org), [calver](https://calver.org), or some simple heuristic like "always bump minor version". I generally recommend the simple heuristic or calver as it does not require anything from the user.
2) it requires some pypi authentication (@Muennighoff can you set up [trusted publishing](https://docs.pypi.org/trusted-publishers/) or alternative invite me to the pypi org) 

@Muennighoff , @imenelydiaker what are your thoughts? (I can set it up once we agree)

**Comment by Muennighoff** [comment]
Cool idea! I don't have rights to invite / set it up - I think @nreimers has - could you give me rights?

<img width="811" alt="Screenshot 2024-03-19 at 9 42 43 AM" src="https://github.com/embeddings-benchmark/mteb/assets/62820084/6bbd8361-5b0d-4a91-9551-3c3248f3e6e8">

**Comment by KennethEnevoldsen** [comment]
@Muennighoff any updated here?

**Comment by Muennighoff** [comment]
I think it is only @nreimers who has rights and unfortunately I cannot reach him :(

**Comment by Muennighoff** [comment]
Resolved & invited you to the project 😊

**Comment by KennethEnevoldsen** [comment]
Added in #288
