### ISSUE TITLE
CI: Linting does not fail if there is changes to be made

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#263]
In a recent PR I noticed that the linting does not fail the CI. I recommend we fix this along with #256 once the #262 and #260 are merged in.

@MartinBernstorff you might be interested to know this one as well as it related to #256.

@Muennighoff a lot of the formatting (isort, black, flake8) can all be done with ruff. Was hoping to simplify the CI a bit by just using that everywhere?

**Comment by Muennighoff** [comment]
> In a recent PR I noticed that the linting does not fail the CI. I recommend we fix this along with #256 once the #262 and #260 are merged in.
> 
> @MartinBernstorff you might be interested to know this one as well as it related to #256.
> 
> @Muennighoff a lot of the formatting (isort, black, flake8) can all be done with ruff. Was hoping to simplify the CI a bit by just using that everywhere?

Simplifying it sounds good to me, great idea!
