### ISSUE TITLE
Enable Ruff rules

### ISSUE THREAD

**Issue by MartinBernstorff** [embeddings-benchmark/mteb#270]
By default, only a few rules are enabled, much fewer than was enabled before Ruff was added. Perhaps we want to enable some more? E.g.:

* isort (I)
* flake8-annotations (ANN)
* pydocstyle (D)

@KennethEnevoldsen Perhaps we want to enable all rules that were enabled before adding ruff?

I've explicated the defaults in #260 as well.

**Comment by KennethEnevoldsen** [comment]
I think those rules are great, feel free to just add them
