### ISSUE TITLE
Tatoeba evaluation not working

### ISSUE THREAD

**Issue by Joao-Maria-Janeiro** [embeddings-benchmark/mteb#294]
Hi,

I was trying to run evaluation on Tatoeba and I get the following error:
Error while evaluating Tatoeba: BuilderConfig 'sqi-eng' not found. Available: ['ace_Arab', ..., 'zul_Latn-zsm_Latn'].

This is a bit strange, but looking at the code here: https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/BitextMining/multilingual/TatoebaBitextMining.py

It looks like the dataset being loaded is FLORES and not Tatoeba, in specifically these lines:
```
hf_hub_name="facebook/flores",
reference="https://huggingface.co/datasets/facebook/flores",
```

**Comment by KennethEnevoldsen** [comment]
Thanks @Joao-Maria-Janeiro for reporting this, this seems to be due to a refactor in #260 which refactored the metadata structure.

**Comment by Joao-Maria-Janeiro** [comment]
Hi, to keep the new structure you currently have, you could update that class to:
```
class FixedTatoebaBitextMining(AbsTaskBitextMining, CrosslingualTask):
    metadata = TaskMetadata(
        name="Tatoeba_FIXED",
        hf_hub_name="mteb/tatoeba-bitext-mining",
        description="1,000 English-aligned sentence pairs for each language based on the Tatoeba corpus",
        reference="https://github.com/facebookresearch/LASER/tree/main/data/tatoeba/v1",
        type="BitextMining",
        category="s2s",
        eval_splits=["test"],
        eval_langs=_LANGUAGES,
        main_score="f1",
        revision="9080400076fbadbb4c4dcb136ff4eddc40b42553",
        date=None,
        form=None,
        domains=None,
        task_subtypes=None,
        license=None,
        socioeconomic_status=None,
        annotations_creators=None,
        dialect=None,
        text_creation=None,
        bibtex_citation=None,
        n_samples={"test": 2000},
        avg_character_length={"test": 39.4},
    )
```

Not sure if the revision number should be this one, but I just took this number from the last commit before this dataset was switched to flores.

This already has the correct dataset and structure.
