### ISSUE TITLE
Cannot import name 'DRESModel' from 'mteb' .

### ISSUE THREAD

**Issue by UnableToUseGit** [embeddings-benchmark/mteb#295]
When I run the eval code from repo of e5-mistral, the error occur: 

Traceback (most recent call last):
  File "/share/minghao/Projects/TestCIL4Embedding/unilm/e5/mteb_beir_eval.py", line 12, in <module>
    from mteb import MTEB, AbsTaskRetrieval, DRESModel
ImportError: cannot import name 'DRESModel' from 'mteb' (/share/kunluo/Envs/cms/lib/python3.9/site-packages/mteb/__init__.py)

**Comment by KennethEnevoldsen** [comment]
This issue seems to be related the repo of e5-mistral using an outdated version of MTEB. Should be solved either by downgrading the MTEB version (to ~1.2.X is my guess) or updating their scripts to match the most recent version of MTEB. I believe you can import `DRESModel` from:

```python
from mteb.evaluation.evaluators.RetrievalEvaluator import DRESModel
```

**Comment by isaac-chung** [comment]
Feel free to reopen if the issue persists after changing the version.
