### ISSUE TITLE
The implementation of SummEval Task 

### ISSUE THREAD

**Issue by SCULX** [embeddings-benchmark/mteb#300]
1. In the **SummEval** task, I tried debugging to enter the specific implementation process and found that 1600 **machine_summaries** were uniformly encoded, with batch_szie set to 32. 
2. However, this resulted in different contexts for each sentence, resulting in different embeddings for `model. encode()`. The original dataset consists of 100 samples, **which should be independent of each other**. Therefore, why not separately process the **machine_summaries** in each sample rather extract all the machine_summers from the 100 samples and encode them uniformly? This can lead to some sentences having context that should not exist,
``` python
       # Get the human & machine summaries for the text in one go for all
        human_lens = [len(human_summaries) for human_summaries in self.human_summaries]
        machine_lens = [len(machine_summaries) for machine_summaries in self.machine_summaries]

        logger.info(f"Encoding {sum(human_lens)} human summaries...")
        embs_human_summaries_all = model.encode(
            [summary for human_summaries in self.human_summaries for summary in human_summaries],
            batch_size=self.batch_size,
        )
        logger.info(f"Encoding {sum(machine_lens)} machine summaries...")
        embs_machine_summaries_all = model.encode(
            [summary for machine_summaries in self.machine_summaries for summary in machine_summaries],
            batch_size=self.batch_size,
        )

        # Split the embeddings into the original human & machine summaries
        embs_human_summaries_all = np.split(embs_human_summaries_all, np.cumsum(human_lens)[:-1])
        embs_machine_summaries_all = np.split(embs_machine_summaries_all, np.cumsum(machine_lens)[:-1])
```

**Comment by KennethEnevoldsen** [comment]
@Muennighoff I assume you implemented this so you might have a deeper understanding of why this decision was made

**Comment by Muennighoff** [comment]
I'm not sure I understand the problem 🤔

`different contexts for each sentence` - The sentences/summaries are passed as a list to .encode which then can embed them in one go depending on the batch size. Why are there different contexts? Each sentence/summary is its own batch item and is not influenced by other batch items.

**Comment by SCULX** [comment]
Thank you so much for taking the time to respond to my inquiry about the repository's code implementation details. 
I try to elaborate this issue in detail. If we use the `bert-base-uncased` model for encoding the `self.human_summaries` with different batch_size, such as **32(The sentince_transformer library defaults ), 16, 8 et al.**  Use the following code:
``` python
# try batch_size = 32, 16, 8 
embs_human_summaries_all_32 = model.encode(
            [summary for human_summaries in self.human_summaries for summary in human_summaries],
            batch_size=32
        )
embs_human_summaries_all_16 = model.encode(
            [summary for human_summaries in self.human_summaries for summary in human_summaries],
            batch_size=16
        )
embs_human_summaries_all_8 = model.encode(
            [summary for human_summaries in self.human_summaries for summary in human_summaries],
            batch_size=8
        )
```

1. In the final result, the `embs_human_summaries_all_32 `  $\neq$ `embs_human_summaries_all_16` $\neq$ `embs_human_summaries_all_8`.

2. Even for **1100** `human_summaries`, the embedding is not equal in three types of embedding mentioned above, that is to say    `embs_human_summaries_all_32[i] `  $\neq$ `embs_human_summaries_all_16[i]`  $\neq$ `embs_human_summaries_all_8[i]`, **i **represents the index of the sentence, i $\in$ [0, 1100).

3. I think the reason for this phenomenon is that **taking different batches** brings **different contexts to each individual sentence**, resulting in different embeddings encoded by the BERT model for this sentence.

4. Therefore, why is it necessary to use this method to obtain embeddings for the **mteb/summeval dataset**, rather than **encoding each sample's human_summaries** and discarding batches.

**Comment by SCULX** [comment]
Yes, that's what I mean, and the embedding of `hi`  is not equal between **batch_size=32** and **batch_size=16**

**Comment by Muennighoff** [comment]
I see but that would be an issue with sentence-transformers, not mteb, right?

**Comment by SCULX** [comment]
1. It is still a issue related to MTEB, because the **mteb/summeval dataset** has **100 samples**, each with **11 sentences of human_summaries**.  MTEB encodes **all the human_summaries (the total number of sentences is 1100)** and then split the embeddings into the original human_summaries for each sample.
2. Why not **encode each sample separately** using human_summaries, so that sample1's human_summaries does not carry sample2's human_summaries, resulting in an encoding that does not conform to human intuition? That is to say, `model.encode([sam1_s1, sam1_s2, ... , sam1_s11]) != model.encode([sam1_s1, sam1_s2, ... , sam1_s11, sam2_s1, sam2_s2, ... , sam2_s11])[:10]`

**Comment by SCULX** [comment]
Now I also agree with @Muennighoff  opinion as the batch_size is not key point on this task, when use the **MTEB** ,the implementation is same to everyone that can ensure the comparability. Feel free to open this issue.
