### ISSUE TITLE
Can't install mteb on windows or linux

### ISSUE THREAD

**Issue by shivijindal** [embeddings-benchmark/mteb#332]
1- first i tried running the code in windows it is giving statvfs error then i came to know windows doesn't support statvfs 
2- then i tried it on linux but it is also giving error      (make: *** No rule to make target 'test'.  Stop.)

**Comment by KennethEnevoldsen** [comment]
Hi @shivijindal, we do have tests running for both installing on windows and ubuntu in the CI. So it would be great if you could provide more detail:

- version of mteb
- full log of error
- version of os

**Comment by isaac-chung** [comment]
Feel free to reopen this if it's still relevant.
