### ISSUE TITLE
Is SciDocs the same as USEB SciDocs?

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#34]
It's inconvenient to have two datasets with the same case insensitive name: `SciDocs` & `SCIDOCS`. E.g. MacOS is by default case insensitive.

Let's rename SciDocs? I'd propose SciDocsS2S or SciDocsRR instead, but maybe someone has a better idea.

Also do I understand correctly that SciDocs is the same SciDocs as in [useb](https://github.com/UKPLab/useb)? I.e. it includes all the tasks of Cite, Co-Cite, Co-Read, Co-View, see their [paper](https://arxiv.org/pdf/2104.06979.pdf) for details[ (+ recomm).](https://github.com/allenai/scidocs)

cc @loicmagne as I think you added it?

**Comment by Muennighoff** [comment]
Still need to figure out whether it's the same as USEB or not

**Comment by NouamaneTazi** [comment]
Can we replace it with the SciDocs that is in useb, to make sure it's the one used?

**Comment by Muennighoff** [comment]
Based on comparing scores I got from USEB [here](https://arxiv.org/pdf/2202.08904.pdf) & from MTEB/SciDocsRR, they're not the same but in the same ballpark.
I think finding out what the exact differences are isn't worth it, but we should always recommend to run the MTEB versions for all datasets (including STS, BEIR etc).

Closing this one for now, feel free to reopen if you feel otherwise.
