### ISSUE TITLE
AttributeError: 'TNews' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by myhostone1990** [embeddings-benchmark/mteb#343]

**Comment by KennethEnevoldsen** [comment]
@myhostone1990 can you provide some more information about this bug? version and when you get it?

When I run the following I don't have an issue:

```
from mteb.tasks.Classification.zho.CMTEBClassification import TNews
task = TNews()
task.metadata
```

**Comment by myhostone1990** [comment]
> @myhostone1990 can you provide some more information about this bug? version and when you get it?
> 
> When I run the following I don't have an issue:
> 
> ```
> from mteb.tasks.Classification.zho.CMTEBClassification import TNews
> task = TNews()
> task.metadata
> ```

I apologize, I was an error reported while running C_MTEB, now I am reporting it to C_MTEB, sorry for the disturbance.
