### ISSUE TITLE
MMTEB Overview

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#360]
This issue is here to help people navigate the how to contribute to [MMTEB](https://github.com/embeddings-benchmark/mteb/tree/main/docs/mmteb) contributions.

## List of Reviewers
The following is a list of reviewers who can review PRs and what languages they prefer to review.

| GitHub User | PR Types |
| --- | --- |
| @KennethEnevoldsen | All types of PRs |
| @imenelydiaker | All types of PRs  |
| @Muennighoff | All types of PRs |
| @MartinBernstorff | PRs related to repo/code structure |
| @isaac-chung | PR related to dataset additions | 

If you want to be a reviewer please comment below and we will add you to the list.

## I would like to contribute, but don't know what datasets to add

Wonderful, we are glad to have you! You can find suggestions for new dataset on our issues. You can also find good first issues to start with as a new contributor:

- [Suggestion for new datasets](https://github.com/embeddings-benchmark/mteb/issues?q=is%3Aissue+is%3Aopen+label%3Anew-dataset)
 - [Good first issues](https://github.com/embeddings-benchmark/mteb/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

However, there are often languages that are missing that do not have suggested datasets yet but have good datasets available e.g. on Huggingface. So we do encourage you to help us explore.  

You can get an overview of language here: #366 

## Useful Links

- [Points](https://github.com/embeddings-benchmark/mteb/blob/main/docs/mmteb/points.md)
- [Guide to adding a dataset](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md)

**Comment by MartinBernstorff** [comment]
Meta: I see many projects with a `CONTRIBUTING.md`; should we have one linking to this issue, or have this issue link to the .md?

**Comment by KennethEnevoldsen** [comment]
@MartinBernstorff we have a contributing.md file, but it would probably be good to have a reference to this document in there as well.

**Comment by MartinBernstorff** [comment]
Ah, I'd strongly recommend having it top-level in the repo to make it easier to find and follow convention. 

Can whip up a PR with that move if we agree 👍

**Comment by KennethEnevoldsen** [comment]
Ahh yea, please do
