### ISSUE TITLE
How does MTEB handle truncation in embedding models?

### ISSUE THREAD

**Issue by rasdani** [embeddings-benchmark/mteb#377]
Embedding models have differing context lengths. `intfloat/multilingual-e5-base` for example has an input limit of 512 tokens. After that it just truncates the text.

Texts in MTEB's datasets are of differing length, too. Is MTEB in any way aware of the embedding's token limit?

I am working on a dataset and was considering chunking it and contemplating how to do it properly.

**Comment by KennethEnevoldsen** [comment]
@rasdani I believe that is up to the model to handle. 

The benchmark simply hands off the full-length texts (`list[str]`) to the model and then the model (typically implemented using SentenceTransformers) truncates the text. However, the model could essentially implement the `encode` method in any way they like, with their own custom method for dealing with documents that are too long.

I might be missing some implementation details, but I believe @Muennighoff can fill in the blanks here.

**Comment by Muennighoff** [comment]
My understanding is the same as that of @KennethEnevoldsen ! Great explanation!
