### ISSUE TITLE
Add HunSum-1 Dataset

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#383]
Low-hanging retrieval dataset here: https://huggingface.co/datasets/SZTAKI-HLT/HunSum-1?row=4 made by Szegedi Tudomanyegyetem.
Just leaving a note for me to add this.

**Comment by KennethEnevoldsen** [comment]
If you want to add this @x-tabdeveloping, I will assign you to the issue.
