### ISSUE TITLE
Remove BSARDRetrieval task for French?

### ISSUE THREAD

**Issue by imenelydiaker** [embeddings-benchmark/mteb#399]
**Problem**
This task seems to be very hard for almost all models, ndcg@10 is ~0-3%. 

**Dataset information**
The paper introducing the dataset have been published in ACL, so I supppose the quality of the dataset is good, see [paper](https://aclanthology.org/2022.acl-long.468/) and [HF dataset card](https://huggingface.co/datasets/maastrichtlawtech/bsard).

Realted to: https://github.com/embeddings-benchmark/mteb/issues/334

Is it a good idea to keep it? @KennethEnevoldsen @MartinBernstorff @Muennighoff

**Comment by KennethEnevoldsen** [comment]
We should probably start checking if the dataset contains a bug

**Comment by MartinBernstorff** [comment]
Agree with Kenneth.

In the abstract they mention `74.8% R@100`; I assume our benchmarks are _much_ worse than that? If so, I see two options:
* Our baseline models are much worse than theirs for this task, or
* There is a bug in their evaluation (e.g. target leakage), or
* There is a bug in the dataset they created, or
* There is a bug in the dataset on huggingface

We probably want to find out which is true before adding it to the benchmark 👍

**Comment by wissam-sib** [comment]
I did some testing yesterday here: https://colab.research.google.com/drive/1QMoEDoBlsGQlieSStvbSIShvZz44_o5z?usp=sharing
And I was able to produce good results with TF-IDF (recall@100 around 47% comparable to the [paper](https://aclanthology.org/2022.acl-long.468.pdf))
I also tested sentence-camembert-base and the results were way higher than [what we had](https://github.com/embeddings-benchmark/mteb/blob/9b648a0f6419215c31e348c5e840fe6e2bc53ab5/results/dangvantuan/sentence-camembert-base/BSARDRetrieval.json#L37)
I think I found the bug and I am opening a PR to fix it.

**Comment by wissam-sib** [comment]
Also, should we change the main score to recall@100? Seems to be the metric that the authors are pushing.

**Comment by KennethEnevoldsen** [comment]
Wonderful @wissam-sib, I believe both changing the score to be in accordance with the authors seems relevant as well.

**Comment by wissam-sib** [comment]
The fix did the trick: https://github.com/embeddings-benchmark/mteb/pull/615/files#diff-8b79d2850b7ba2ac2e003f1ed995b02db503a83401c7769bd0e8ad0a3f2dc936 🎉
