### ISSUE TITLE
Adding FQUAD for French Retrieval

### ISSUE THREAD

**Issue by imenelydiaker** [embeddings-benchmark/mteb#401]
Adding the [FQuad](https://huggingface.co/datasets/fquad) [[paper](https://arxiv.org/abs/2002.06071)] QA dataset as it can be used for retrieval.

Related to https://github.com/embeddings-benchmark/mteb/issues/334

Useful link from @ManuelFay : https://huggingface.co/datasets/manu/fquad2_test

**Comment by KennethEnevoldsen** [comment]
I have added the good first issue tag to allow people to take this PR. If you have someone on it please remove it.

**Comment by ManuelFay** [comment]
I'll do it this weekend if no one does beforehand, no need to remove the tag someone does !
