### ISSUE TITLE
Point tracking always introduces merge conflicts.

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#415]
The way we track points currently is that everyone has a row in an MD table, and pull requests have to update the file.
In my experience this has on just about every PR resulted in a merge conflict.
Considering how many PRs we get per day this is rather inconvenient.

I'm filing the issue to start a discussion on how we could potentially improve this.

### JSONL
@KennethEnevoldsen suggested that it could be a good idea to use one JSONL file to track points after each contribution.
I'm not exactly a Git genius, but my guess is that this would still result in a bunch of merge conflicts on the last lines.
Perhaps we could have one per person, which would be great, but could potentially cause issues with reviewers.
I think the cleanest solution would be to use one JSONL file for everyone who submits a PR, but their file would not only contain their own points but also reviewers' points on their PR.
For instance this would be a JSONL file for me, that I would append with each PR I submit:
```python
{"user": "x-tabdeveloping", "points": 6, "type": "dataset"}
{"user": "KennethEnevoldsen", "points": 4, "type": "review"}
```
We could potentially add even more granularity (separate lines for bonus points) so we can exactly track why people have the points.

What do you all think?

**Comment by KennethEnevoldsen** [comment]
a jsonl file would still lead to merge conflict (tracked as edits with n-lines), I would just do a folder with jsonl files (seperate pr. pr).

**Comment by isaac-chung** [comment]
A single folder with 1 JSONL file per PR sounds like a good option.
