### ISSUE TITLE
run_mteb_german.py throws errors at Retrival tasks

### ISSUE THREAD

**Issue by qsdhj** [embeddings-benchmark/mteb#426]
When running the german test script: [run_mteb_german.py](https://github.com/embeddings-benchmark/mteb/blob/main/scripts/run_mteb_german.py)
I get errors at the Retrival Tasks.

The dataset: "GermanDPR"
Gives this error: 
mteb\Lib\site-packages\mteb\tasks\Retrieval\deu\GermanDPRRetrieval.py", line 71, in load_data
    row["positive_ctxs"], id_prefix=f"doc_{i}_p_", existing_docs=all_docs
    KeyError: 'positive_ctxs'

The dataset: "GerDaLIR"
Gives this error: 
mteb\Lib\site-packages\datasets\builder.py", line 1762, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset

The dataset: "GermanQuAD-Retrieval" is working.

I only copied the [run_mteb_german.py](https://github.com/embeddings-benchmark/mteb/blob/main/scripts/run_mteb_german.py) file and installed sentence_transformers and mteb.
Running on Windows 11:
![grafik](https://github.com/embeddings-benchmark/mteb/assets/166700412/7b1821ed-8189-4d98-ac5c-85b9ef055e27)
Python: 3.12.1

pip packages:
aiohttp==3.9.5
aiosignal==1.3.1
annotated-types==0.6.0
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
colorama==0.4.6
datasets==2.18.0
dill==0.3.8
eval-type-backport==0.1.3
filelock==3.13.4
frozenlist==1.4.1
fsspec==2024.2.0
huggingface-hub==0.22.2
idna==3.7
Jinja2==3.1.3
joblib==1.4.0
jsonlines==4.0.0
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mpmath==1.3.0
mteb==1.6.16
multidict==6.0.5
multiprocess==0.70.16
networkx==3.3
numpy==1.26.4
packaging==24.0
pandas==2.2.2
pillow==10.3.0
pyarrow==15.0.2
pyarrow-hotfix==0.6
pydantic==2.7.0
pydantic_core==2.18.1
Pygments==2.17.2
python-dateutil==2.9.0.post0
pytrec-eval-terrier==0.5.6
pytz==2024.1
PyYAML==6.0.1
regex==2024.4.16
requests==2.31.0
rich==13.7.1
safetensors==0.4.3
scikit-learn==1.4.2
scipy==1.13.0
sentence-transformers==2.7.0
setuptools==68.2.2
six==1.16.0
sympy==1.12
threadpoolctl==3.4.0
tokenizers==0.15.2
torch==2.2.2
tqdm==4.66.2
transformers==4.39.3
typing_extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
wheel==0.41.2
xxhash==3.4.1
yarl==1.9.4

**Comment by imenelydiaker** [comment]
Hello, 

Thanks for reporting this issue, a fix was made in PR #428. Hopefully it will be merged soon and you will be able to update mteb and run the task. 🙂
