### ISSUE TITLE
Multiple label annotated datasets 

### ISSUE THREAD

**Issue by asparius** [embeddings-benchmark/mteb#455]
Currently, mmteb has two datasets: a Turkish multidomain product review dataset and a Kurdish sentiment dataset. These datasets contain categorical annotations such as domain tag, in addition to sentiment labels. I am wondering whether we should create a new dataset that includes these categorical annotations. I believe it could be beneficial for low-resource languages. Waiting for your opinions :)

**Comment by imenelydiaker** [comment]
If you're talking about Multilabel classification tasks, I think this PR https://github.com/embeddings-benchmark/mteb/pull/440 may be interesting 🙂

**Comment by asparius** [comment]
It is different than multiple-label classification, perhaps I phrased it incorrectly. They are datasets that have both Sentiment and also category labels for the given samples. I have only uploaded their sentiment part, my question is whether I should also add this category classification task as well?

**Comment by imenelydiaker** [comment]
I guess you can create a new task using the same dataset and only change the label column? But since it's the same dataset and text, I don't know if changing the classes is relevant to the benchmark?

**Comment by KennethEnevoldsen** [comment]
> They are datasets that have both Sentiment and also category labels for the given samples

That seems to me to be multilabel classification (as opposed to multiclass).

**Comment by imenelydiaker** [comment]
I think you can frame it as a multilabel task, since the dataset offers 2 columns that can be used as labels. It's just that in a multilabel setting you'll try to predict both classes at the same time no?

**Comment by x-tabdeveloping** [comment]
For this a `ClassifierChain` seems more appropriate as the labels are clearly dependent on each other. Chime in on the discussion at #440. I'm thinking of adding multiple options to the task so that independence does not need to be assumed but we have to discuss how this is best executed.

**Comment by isaac-chung** [comment]
Feel free to reopen if it's still relevant.
