### ISSUE TITLE
What about a Cross-lingual Retrieval task?

### ISSUE THREAD

**Issue by imenelydiaker** [embeddings-benchmark/mteb#475]
I came across the [mlqa](https://huggingface.co/datasets/mlqa) dataset, where basically you have a document written in language X and a question asked in language Y, the answer is then retrieved in language X. So it is a retrieval task, although it is cross-lingual since it the question and the document are in different languages. 

I think there exist many real-world uses cases for this task. For example, for a bot, you can have many source documents in English or any other language and would like to ask questions in another language as your native language that may be different from the docs' one. I think it would be nice to see how a retiever would perform on two languages at the same time.

Let me know what you think and I'll make a draft PR with the proposed task and experiments. But before that, do we already cover this task in mteb?
@KennethEnevoldsen @isaac-chung @MartinBernstorff @Muennighoff  and any other person that is interested in commenting 🙂

**Comment by KennethEnevoldsen** [comment]
I believe @orionw already started a discussion on this over at #362

**Comment by imenelydiaker** [comment]
Okay great, I'm joining the discussion and closing this issue 🙂
