### ISSUE TITLE
Add swiss judgements

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#542]
Based on a previous PR here which was never finished: https://github.com/embeddings-benchmark/mteb/pull/357

**Comment by Akash190104** [comment]
I'll take it if no one else is working on it.

**Comment by Akash190104** [comment]
@KennethEnevoldsen I feel this issue can be closed by PR #569 now. Please take a look. Really appreciate your time.

**Comment by Akash190104** [comment]
@KennethEnevoldsen sorry for pinging again. This issue can be closed now.
