### ISSUE TITLE
CI fails unexpectedly

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#544]
The CI is still failing unexpectedly, see PR #527 and #539, I had to re-run jobs for #527 for them to pass. Any idea on why this is happening?

_Originally posted by @imenelydiaker in https://github.com/embeddings-benchmark/mteb/issues/540#issuecomment-2074410094_

**Comment by KennethEnevoldsen** [comment]
#527 seems to be GitHub (it happens sometimes)

> Error: The operation was canceled.

#539 seems to be a request issue (downloading a rerank model)


These errors generally seems to happen more for windows runners.

A potential solution is to replace the models and datasets to local models and datasets (just have the downloaded to the repo potentially creating mini datasets just for tests)

Another potential solution is just to automatically try to [rerun](https://stackoverflow.com/questions/71574593/how-to-automatically-retry-github-action-jobs-on-failure) jobs. We can have it try it for 2 attempts (since rerunning almost always fixes the issue)

**Comment by mrshu** [comment]
I guess as per https://github.com/embeddings-benchmark/mteb/pull/646 this might be already fixed?

**Comment by KennethEnevoldsen** [comment]
I believe it is (we at least very rarely see issues)
