### ISSUE TITLE
Do not skip if running new split

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#55]
We currently skip when running a new split & a result file of the same name exists
It'd be better to run & append the new results of the new split to the existing result file.

**Comment by Sakshamrzt** [comment]
The result file also has dataset_version and mteb_version. Does it also makes sense to add the result  in case the dataset_version or mteb_version is different than the one in the result file?

**Comment by KennethEnevoldsen** [comment]
I generally imagine version changes not leading to different results. Then we would have to keep a version for each dataset (which seems problematic). Updating it when the revision is outdated though seems very reasonable.

**Comment by isaac-chung** [comment]
Evaluating a missing split is now available via [this PR](https://github.com/embeddings-benchmark/mteb/pull/1525), which addresses the original description regarding new splits.
