### ISSUE TITLE
Convert French Clustering tasks to Fast

### ISSUE THREAD

**Issue by imenelydiaker** [embeddings-benchmark/mteb#568]
For the French benchmark, convert clustering tasks to fast using `AbsTaskClusteringFast`:

- [x] AlloProfClusteringP2P
- [x] AlloProfClusteringS2S
- [x] **HALClusteringS2S** #814 
- ~MasakhaNEWSClusteringP2P~ (less than 1000 samples per language)
- ~MasakhaNEWSClusteringS2S~ (less than 1000 samples per language)
- **MLSUMClusteringP2P** https://github.com/embeddings-benchmark/mteb/issues/798
- **MLSUMClusteringS2S** https://github.com/embeddings-benchmark/mteb/issues/798

Priority for tasks in bold because they contain a big number of samples.

**Comment by isaac-chung** [comment]
Looks like this issue will be addressing the first 3 dataset mentioned in the description. @imenelydiaker will you be working on these? or could we assign this to one of the new contributors?

**Comment by imenelydiaker** [comment]
> Looks like this issue will be addressing the first 3 dataset mentioned in the description. @imenelydiaker will you be working on these? or could we assign this to one of the new contributors?

Yes it could be assigned to any person who'd like to contribute!
