### ISSUE TITLE
S2S vs P2P

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#58]
The BEIR tasks are currently all marked as S2S, but some of them are P2P or S2P / P2S. Retrieval is the only task where we have S2P / P2S. Does that make sense?

Options I see:
- Add S2P & P2S to P2P assuming that the main use case for selecting S2S is to get short texts
- Introduce S2P & P2S

Any thoughts? cc @NouamaneTazi

**Comment by NouamaneTazi** [comment]
Agreed, I think the S2S in BEIR tasks was mainly from copying other task configs. Please feel free to correct that
