### ISSUE TITLE
More languages for summarization

### ISSUE THREAD

**Issue by wissam-sib** [embeddings-benchmark/mteb#631]
I found a few possibly machine translated versions of summeval:
* https://huggingface.co/datasets/sproos/summeval-sw
* https://huggingface.co/datasets/sproos/summeval-de
* https://huggingface.co/datasets/sproos/summeval-tr
* https://huggingface.co/datasets/sproos/summeval-es

I am thinking about adding them. Any reservations?

They seem to align with the one we have for english: https://huggingface.co/datasets/mteb/summeval
And the machine translated one we have for french: https://huggingface.co/datasets/lyon-nlp/summarization-summeval-fr-p2p

**Comment by Akash190104** [comment]
I don't think there are any researvations yet, although, if you allow, I would like to work on this and add a couple of datasets (while you work on the other two). I would get started on the first two then.

**Comment by isaac-chung** [comment]
From https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object:
> We do not include any machine-translated (without verification) datasets in the benchmark.

So I don't see an issue _if_ there is evidence supporting that these are verified translations.

**Comment by wissam-sib** [comment]
Hi @isaac-chung good point, I am contacting the owner of these datasets to verify this!

@Akash190104 thank you for proposing your help. However, since these datasets are very similar, adding two or four won't make much of a difference in effort on my end. Might be more worthwhile spending your efforts on datasets that are different (e.g. the ones referred to in this issue: https://github.com/embeddings-benchmark/mteb/issues/419)

**Comment by KennethEnevoldsen** [comment]
@wissam-sib it seems like most of these datasets are machine translations of the English dataset (might be wrong here). If that is the case. I don't believe we are that interested (introduce potential evaluation biases, like overestimation of performance). 

However if they are not we would love to use these as this task is not well covered within any other language.

**Comment by wissam-sib** [comment]
@KennethEnevoldsen I agree about the evaluation bias. Also the owner just confirmed these are machine translated. Closing the issue.
