### ISSUE TITLE
Add hardware info to results file

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#64]
It'd be nice to also have information about the hardware used in the results file in addition to the evaluation time if this is easy to get!

**Comment by spolisar** [comment]
This isn't exactly related but this issue reminded me of it. It'd be convenient if model size was displayed in the leaderboard.

**Comment by Muennighoff** [comment]
Agreed! The problem is I'm not sure how to automatically extract model size from a model if someone submits. The embedding dimension in the leaderboard can be nicely pulled from the `config.json` file most models have, but for parameter count I think it would have to be manual..

**Comment by spolisar** [comment]
Maybe modifying the test script or required interface so this information is included?
I'm also referring to size in memory here, since I'd like to know what models I can run on my own hardware just by looking through the leaderboard instead of looking into each model to find out.

**Comment by Muennighoff** [comment]
> Maybe modifying the test script or required interface so this information is included? I'm also referring to size in memory here, since I'd like to know what models I can run on my own hardware just by looking through the leaderboard instead of looking into each model to find out.

Memory usage in terms of how much GPU memory a model takes should correlate with the model size I think - E.g. loading a 1 billion parameter model in float32 takes ~4GB. Precision or input data may change that but that's largely model-independent. So model parameters would be enough to cover that, no?

**Comment by spolisar** [comment]
Fair enough
