### ISSUE TITLE
How to Save Retrieved Documents in Retrieval Tasks

### ISSUE THREAD

**Issue by AugustLHHHHHH** [embeddings-benchmark/mteb#667]
Hi，

I am currently working on an information retrieval task and I want to save the retrieved documents for bad case analysis.
I have printed the output of the search function in beir/retrieval/search/dense/exact_search.py, and the format is {q_id: {pid: score}}. such as:

![image](https://github.com/embeddings-benchmark/mteb/assets/109325850/52e73aa5-2d29-40b6-839d-2d5b81193307)

However, it seems that the corpus ids are not sorted according to the scores. Should I sort the results by cosine similarity from high to low and save them so that the most relevant documents are placed at the beginning?

Thanks!

**Comment by isaac-chung** [comment]
Sorry for the delay. To answer the question in the title, see this section of README: https://github.com/embeddings-benchmark/mteb?tab=readme-ov-file#saving-retrieval-task-predictions.
