### ISSUE TITLE
Add LegalBench supply chain tasks

### ISSUE THREAD

**Issue by KranthiGV** [embeddings-benchmark/mteb#689]
We have 10 supply chain tasks here: https://hazyresearch.stanford.edu/legalbench/tasks/supply_chain_disclosure_disclosed_verification.html

Original data source: The limitations of supply chain disclosure regimes by Chilton, Adam S and Sarfaty, Galit A

**Comment by KennethEnevoldsen** [comment]
I believe @awinml  is adding legalbench
