### ISSUE TITLE
BitextMining could support both ways

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#70]
For BUCC-fr-en we currently search from english texts given french texts.

a) Most uses cases are probably the inverse
b) We should generally support both ways / automatically run both (e.g. like it's done in https://arxiv.org/pdf/2007.01852.pdf)

What do you think @NouamaneTazi ?

**Comment by NouamaneTazi** [comment]
I think this is [the source ](https://comparable.limsi.fr/bucc2018/bucc2018-task.html)from where we downloaded the dataset, and it only contains 4 pairs in the order they precised. Do you think the same dataset can be used inversely without issue?

**Comment by Muennighoff** [comment]
My understanding is that in the original task each sentence from lang_a could only be mapped to one sentence from lang_b & vice-verca. In that case inversing does not make a difference.

In our implementation, however, each sentence from lang_b (corpus) can be mapped to multiple sentences from lang_a (query). Thus inversing it would make a difference. This is also what's done in https://arxiv.org/pdf/2007.01852.pdf afaict. Given that these are parallel sentences, we should be able to inverse without issues.

**Comment by Muennighoff** [comment]
> My understanding is that in the original task each sentence from lang_a could only be mapped to one sentence from lang_b & vice-verca. In that case inversing does not make a difference.
> 
> In our implementation, however, each sentence from lang_b (corpus) can be mapped to multiple sentences from lang_a (query). Thus inversing it would make a difference. This is also what's done in https://arxiv.org/pdf/2007.01852.pdf afaict. Given that these are parallel sentences, we should be able to inverse without issues.

Actually, I think you are right - The original BUCC is intended to be in the same order as in MTEB, i.e. en is target that is searched from. I guess this is more of a feature request then that's not very urgent. I will leave it open if anyone ever demonstrates interest in this.

**Comment by KennethEnevoldsen** [comment]
Will close this for now as it seems to have gotten stale. If someone wants to implement or re-request this they are more than welcome to let us know
