### ISSUE TITLE
monolingual evaluation gives more than target language in results

### ISSUE THREAD

**Issue by achibb** [embeddings-benchmark/mteb#708]
scripts/run_mteb_german.py

I am running this script and observed, that the script, even though specifying "de", also creates the other languages (like en, es, mostly for the multilingual datasets i suppose). Is this intended and if so, how to get rid of it?

![image](https://github.com/embeddings-benchmark/mteb/assets/42097962/798185a4-4fed-4e03-852b-9c26057450ad)

Thank you!

**Comment by KennethEnevoldsen** [comment]
Thanks @achibb. Yeah, that does seem to be an issue. Thanks for letting us know

**Comment by achibb** [comment]
Sounds great for me. Not working on this.

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Imene Kerboua ***@***.***>
Gesendet: Wednesday, May 15, 2024 12:34:52 PM
An: embeddings-benchmark/mteb ***@***.***>
Cc: achibb ***@***.***>; Mention ***@***.***>
Betreff: Re: [embeddings-benchmark/mteb] monolingual evaluation gives more than target language in results (Issue #708)


Thanks @achibb<https://github.com/achibb>. Yeah, that does seem to be an issue. Thanks for letting us know

I'm working on this, seem to ve related to the lastest refactoring where we replaced task_langs by hf_subsets in load_data() functions.
Is anyone working on this? Else, I'll open a PR by the end of the day

**Comment by imenelydiaker** [comment]
Okay, I'll take it, thanks for reporting the bug, fix coming soon 🙂

**Comment by KennethEnevoldsen** [comment]
@imenelydiaker I believe the `mteb.get_tasks()` already handles this case.

A solution might be to reformat the benchmark such it looks like:

```
tasks = mteb.get_tasks(task_names = list_of_task_names, languages = ["deu"])
bench = MTEB(tasks=tasks)  
...
```

I believe the only thing we would have to do is add the task_names argument to mteb_get_tasks. (in the future I would like to remove all the filtering from MTEB and just do it in `get_tasks`

**Comment by imenelydiaker** [comment]
Maybe I'm mixing up things, I tried selecting a language with the CLI and it didn't work, I'll look more into it when I'll have my laptop. I'll keep you updated!

**Comment by KennethEnevoldsen** [comment]
I am actually not sure how the CLI selects languages atm.
