### ISSUE TITLE
Convert Biorxiv and Medrxiv clustering to fast

### ISSUE THREAD

**Issue by jankounchained** [embeddings-benchmark/mteb#713]
Converting the following tasks to ClusteringFast following #660 

- [x] [Biorxiv P2P](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/eng/BiorxivClusteringP2P.py)
- [x] Biorxiv S2S
- [x] [Medrxiv P2P](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/eng/MedrxivClusteringP2P.py)
- [x] Medrxiv S2S

**Comment by isaac-chung** [comment]
hi @jankounchained if you've started on any of those, feel free to add a PR. We're hoping to wrap up on the parent issue soon. Let us know if you don't have time for that or if you need any help!

**Comment by jankounchained** [comment]
hey @isaac-chung, it's basically done, i'll submit the PR today. 
I just need to update the datasets in the mteb organization on huggingface.
can you give me access?

this is my [hf profile](https://huggingface.co/janko)

**Comment by KennethEnevoldsen** [comment]
@jankounchained I have added you as a contributor to mteb
