### ISSUE TITLE
Convert SIB200Classification to SIB200Clustering

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#732]
We currently have quite a reasonable coverage on Classification tasks in MTEB, however only have a subpar performance on clustering. I would probably suggest that we convert SIB200Classification to a clustering task. @x-tabdeveloping what are your thoughts here? @jankounchained might be something that you could do? (we should probably combine train/val/test into one dataset).

**Comment by x-tabdeveloping** [comment]
Sounds very reasonable to me. Topics are better suited for clustering than classification in my opinion anyway.

**Comment by isaac-chung** [comment]
Just opened a PR ☝️ if anyone wanted to take a look.
