### ISSUE TITLE
Running Models

### ISSUE THREAD

**Issue by y12uc231** [embeddings-benchmark/mteb#746]
Hi, 

I would like to contribute to this project. I just noticed that to day is the last day to add datasets and it will be about running models from tomorrow. Could you please share the process to run models on the datasets? And how does it count as a contribution points for co-authorship?

**Comment by imenelydiaker** [comment]
Hello, 

- Discussion about running models here: #705. 
- Points attribution [here](https://github.com/embeddings-benchmark/mteb/tree/main/docs/mmteb#contribution-point-guideline).

**Comment by isaac-chung** [comment]
Closing this as there's an existing discussion.
