### ISSUE TITLE
Integrate JMTEB

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#749]
Would be great to have the datasets in JMTEB (https://github.com/sbintuitions/JMTEB) integrated into MTEB for those which aren't yet already, so we can also add a Japanese leaderboard sometime 😊 cc @lsz05 @ryokan0123 @masaya-ohagi & anyone who may be interested

**Comment by awinml** [comment]
I would like to help integrate JMTEB. The following datasets from JMTEB are already present in MTEB:

- [AmazonCounterfactualClassification](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Classification/multilingual/AmazonCounterfactualClassification.py)
- [AmazonReviewClassification](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Classification/multilingual/AmazonReviewsClassification.py)
- [MassiveIntentClassification](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Classification/multilingual/MassiveIntentClassification.py)
- [MassiveScenarioClassification](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Classification/multilingual/MassiveScenarioClassification.py)
- [JSTS](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/STS/jpn/JSTS.py)
- [PawsX PairClassification](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/PairClassification/multilingual/PawsX.py)


The following ones would need to be added:

- Clustering:
  - [ ] Livedoor News 
  - [ ] MewsC-16-ja 

- STS:
  - [ ] JSICK

- Retrieval:
  - [ ] JAQKET
  - [ ] Mr.TyDi-ja 
  - [ ] NLP Journal title-abs 
  - [ ] NLP Journal title-intro 
  - [ ] NLP Journal abs-intro 
  - [ ] JaGovFaqs-22k 

- Reranking:
  - [ ] ESCI

**Comment by AlexeyVatolin** [comment]
@Muennighoff, I can take over the integration of ESCI. I have already looked at the contents of this dataset. In the original dataset https://huggingface.co/datasets/tasksource/esci there are three languages: English, Spanish and Japanese. Do we want to add all three languages or just Japanese?

**Comment by Muennighoff** [comment]
> @Muennighoff, I can take over the integration of ESCI. I have already looked at the contents of this dataset. In the original dataset https://huggingface.co/datasets/tasksource/esci there are three languages: English, Spanish and Japanese. Do we want to add all three languages or just Japanese?

I think if we can add all 3 that'd be even better! 🙌

**Comment by KennethEnevoldsen** [comment]
@awinml do you still want to finish up this issue or should I mark is as "up for graps"?

**Comment by awinml** [comment]
@KennethEnevoldsen, I don't have the bandwidth at the moment to add the remaining three datasets. Feel free to mark it as open for contributions. I’m happy to help review any PRs that come in!

**Comment by KennethEnevoldsen** [comment]
I suspected as much - thanks for the help so far though
