### ISSUE TITLE
Extend pair classification

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#753]
Currently pair classification can only account for NLI problems formulated as binary classification between entailment and contradiction, and this is done by thresholding on different scalar distances between the two embeddings.
This severely limits what we can do with pair classification, and we are not estimating how well models are able to detect neutral examples in NLI datasets we already have.
I have a handful of suggestions for how we could change this, to allow for more nuance in binary classification tasks.

#### Option 1: Training a classifier over actual features:
I think one way we could make these tasks a bit more nuanced and natural is by using logistic regression over:<br>
a) The two embeddings concatenated
b) The difference vector of the two embeddings
c) Concatenate the two embeddings and their absolute difference - This is the approach used by [SentenceTransformers](https://www.sbert.net/examples/training/nli/README.html) for training on NLI datasets

![Figure of NLI training in SBERT](https://raw.githubusercontent.com/UKPLab/sentence-transformers/master/docs/img/SBERT_SoftmaxLoss.png)

#### Option 2: Training a classifier _(maybe tree based)_ on distances
We might not want to use all of the features as it would make the tasks more difficult and we might have to encode more training examples.
We could still use distances in a manner that would at least be suitable for also accounting for neutral examples.
Currently we have some heuristics for choosing the best thresholds, but this is only good for binary classification.
I think by using a tree-based model (decision tree, random forest, etc.) we could obtain these implicitly and could utilize neutral examples still.

**Comment by x-tabdeveloping** [comment]
What do you think @imenelydiaker @isaac-chung @KennethEnevoldsen @Muennighoff ?

**Comment by KennethEnevoldsen** [comment]
related to https://github.com/embeddings-benchmark/mteb/issues/123

I think option 1 is reasonable

**Comment by x-tabdeveloping** [comment]
Oh yeah this is clearly a duplicate, sorry about that.
