### ISSUE TITLE
Fix : Error [test_all_metadata_is_filled ]

### ISSUE THREAD

**Issue by Ruqyai** [embeddings-benchmark/mteb#762]
<img width="1013" alt="Screenshot 2024-05-18 at 7 33 30 AM" src="https://github.com/embeddings-benchmark/mteb/assets/13546372/09d1b625-3639-42dc-945d-a6f2ae17abcc">

PR #763 
https://github.com/embeddings-benchmark/mteb/pull/669#issuecomment-2117932543

**Comment by KennethEnevoldsen** [comment]
Not sure what is meant by this screenshot. I get that you refer to the comment in 669 but I don't see how the PR addresses it. Or at least it addresses a variety of other things as well. I have closed it for now, but do feel free to open a new PR.

**Comment by Ruqyai** [comment]
hello @KennethEnevoldsen 

I was just testing the error that appeared for me when I ran `make test` or `make pr`. It was fixed when you solved the issue in  PR on https://github.com/embeddings-benchmark/mteb/pull/781.
