### ISSUE TITLE
Only Spanish is covered in FloresClustering 

### ISSUE THREAD

**Issue by isaac-chung** [embeddings-benchmark/mteb#782]
Not sure if this has been discussed before. This was discovered when I considered converting flores to ClusteringFast. 

`FloresClusteringS2S` currently only has Spanish, whereas the original dataset (`https://huggingface.co/datasets/facebook/flores`) should have 200 languages. Should this be converted to a multilingual clustering task instead? 

CC @KennethEnevoldsen @imenelydiaker and anyone else who may be interested.

**Comment by imenelydiaker** [comment]
On what column does FloresClustering do the actual clustering? Does the original Flores contain other columns than bitexmining ones?

**Comment by isaac-chung** [comment]
`FloresClustering`'s labels are taken from the `topic` column and the subtopics are removed.
> We normalized topics by 1. making them lowercase and 2. removing subcategories ('travel, expenses' -> 'travel'). Afterwards, we dropped every category that contained less than 15 sentences.

**Comment by isaac-chung** [comment]
Specifically on `dropped every category that contained less than 15 sentences`, this will be done per language. Does that sound good?

**Comment by imenelydiaker** [comment]
> Specifically on `dropped every category that contained less than 15 sentences`, this will be done per language. Does that sound good?

Yes per language, sounds good!

**Comment by isaac-chung** [comment]
Cool. As for splits, should we do both `dev` and `devtest`? or only the latter?

**Comment by imenelydiaker** [comment]
> Cool. As for splits, should we do both `dev` and `devtest`? or only the latter?

You can add both, it'll just make them available for users, a benchmark will use the test set only

**Comment by KennethEnevoldsen** [comment]
isn't SIB200ClusteringFastS2S the clustering version of flores?

**Comment by isaac-chung** [comment]
I think you're right @KennethEnevoldsen . In that case, maybe we should remove `FloresClustering`.
