### ISSUE TITLE
Convert MLSUM to Fast

### ISSUE THREAD

**Issue by jankounchained** [embeddings-benchmark/mteb#798]
Following #660 

Tasks to be edited:
https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/multilingual/MLSUMClusteringP2P.py
https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/multilingual/MLSUMClusteringS2S.py

**Comment by imenelydiaker** [comment]
Feel free to open a PR for this! 🙂

**Comment by isaac-chung** [comment]
@jankounchained wondering if you already have a PR open for this, or would it be alright for someone else to start?
