### ISSUE TITLE
Convert MasakhaNews to Fast

### ISSUE THREAD

**Issue by AlexeyVatolin** [embeddings-benchmark/mteb#800]
Following https://github.com/embeddings-benchmark/mteb/issues/660

Tasks to be edited:
https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/multilingual/MasakhaNEWSClusteringP2P.py
https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/multilingual/MasakhaNEWSClusteringS2S.py

**Comment by imenelydiaker** [comment]
This dataset has less than 1000 sample per language, so I'm not sure it should be converted. @isaac-chung wdyt?

**Comment by isaac-chung** [comment]
Agreed @imenelydiaker

**Comment by imenelydiaker** [comment]
I'm closing this issue and removing the dataset from the list, thank you @AlexeyVatolin!
