### ISSUE TITLE
Convert BigPatent to Fast

### ISSUE THREAD

**Issue by AlexeyVatolin** [embeddings-benchmark/mteb#801]
Following https://github.com/embeddings-benchmark/mteb/issues/660

Tasks to be edited:
https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/eng/BigPatentClustering.py

**Comment by imenelydiaker** [comment]
Feel free to open a PR for this!

**Comment by AlexeyVatolin** [comment]
@imenelydiaker, Hi. Can you give me access to huggingface to upload the dataset on behalf of mteb organization?
Here is my [hf profile](https://huggingface.co/vatolinalex)

**Comment by imenelydiaker** [comment]
> @imenelydiaker, Hi. Can you give me access to huggingface to upload the dataset on behalf of mteb organization? Here is my [hf profile](https://huggingface.co/vatolinalex)

Invitation sent!

**Comment by AlexeyVatolin** [comment]
@imenelydiaker, I think we can close this issue since pull request is already merged and there is nothing more to do here
