### ISSUE TITLE
Question about Adding Datasets

### ISSUE THREAD

**Issue by Ruqyai** [embeddings-benchmark/mteb#802]
Question:

I don't know if I am allowed to add a dataset that is not my own work. In the first submission, I collected the data myself through web scraping. 

However, when I browsed the task folder, I found that the Arabic language is almost limited to classification. There are several large datasets like this one. Can I add it now?

https://huggingface.co/datasets/Cohere/miracl-ar-corpus-22-12

Or others from the list:
https://huggingface.co/datasets?language=language:ar&sort=trending

**Comment by imenelydiaker** [comment]
Hello,

Yes you can add datasets that are sourced and are not your own. 

For [this one](https://huggingface.co/datasets/Cohere/miracl-ar-corpus-22-12), we already handle MIRACL with all languages, see this PR #642.

Feel free to add any other dataset from the list, just make sure it is of good quality.

**Comment by Ruqyai** [comment]
Thank you a lot @imenelydiaker

**Comment by KennethEnevoldsen** [comment]
This issue seem resolved. Will close it for now. Feel free to reopen it
