### ISSUE TITLE
Inconsistencies in the naming of some tasks  fast clustering versions

### ISSUE THREAD

**Issue by imenelydiaker** [embeddings-benchmark/mteb#823]
Hello,

I've found the following inconsistencies in the package:

1. Fast version of the clustering sometimes implemented in a new file and sometimes in the same file as the old task. See [ArxivClusteringP2PFast](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/eng/ArxivClusteringP2PFast.py), [BlurbsClusteringP2PFast](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/deu/BlurbsClusteringP2PFast.py) and [BigPatentClustering](https://github.com/embeddings-benchmark/mteb/blob/85dbcf84fc58a6e5375d671c36d9a89551574b96/mteb/tasks/Clustering/eng/BigPatentClustering.py#L42).
2. Inconsistencies in naming: in [ArxivClusteringP2PFast](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/tasks/Clustering/eng/ArxivClusteringP2PFast.py), the task is named `ArxivClusteringP2P.v3`, why? was there a v2 somewhere?
3. Suffixing the name of the task with `.v2` is confusing: MSMARCO has 2 versions, so one of the tasks is named `MSMARCOv2` although it's not a faster version. https://github.com/embeddings-benchmark/mteb/blob/85dbcf84fc58a6e5375d671c36d9a89551574b96/mteb/tasks/Retrieval/eng/MSMARCOv2Retrieval.py#L10

Any opinions? I'd like to update these.
@isaac-chung @KennethEnevoldsen

**Comment by isaac-chung** [comment]
1. My preference is the old and new tasks should be in the same file.
2. Seems like v3 was a typo? there are v2 results committed.
3. This is likely the biggest issue on this naming topic. There was an agreement with v2 at the time [here](https://github.com/embeddings-benchmark/mteb/pull/757#discussion_r1605240988), but given the new evidence I'm leaning towards renaming to `XYZClusteringFast` (instead of `XYZClustering.v2`). This would affect the relevant results and some values within those files.

**Comment by imenelydiaker** [comment]
> 1. My preference is the old and new tasks should be in the same file.
> 2. Seems like v3 was a typo? there are v2 results committed.

Okay I'll update old tasks with these changes.

> 3. This is likely the biggest issue on this naming topic. There was an agreement with v2 at the time [here](https://github.com/embeddings-benchmark/mteb/pull/757#discussion_r1605240988), but given the new evidence I'm leaning towards renaming to `XYZClusteringFast` (instead of `XYZClustering.v2`). This would affect the relevant results and some values within those files.

I also tend to prefer using `Fast` instead of `.v2`, although I remember that @KennethEnevoldsen had a reason for naming them `.v2`, we should wait for his opinion before updating.

**Comment by isaac-chung** [comment]
Looping in @x-tabdeveloping and @Muennighoff as well just in case

**Comment by isaac-chung** [comment]
Good call! I just realized that we have `CMedQAv1-reranking` and `CMedQAv2-reranking`. I'm happy with that arrangement.

**Comment by KennethEnevoldsen** [comment]
> Would the fast version be named LeCaRDv2.v2?

it probably would be if we keep to the current system (which might not be ideal)

> MSMARCOv2Retrieval -> another dataset
> ArxivClusteringP2P.v2 -> same dataset but new implementation

I completely agree that it is not great. it might be worth looking at alternatives.

----

An alternative is to **not** have two different names for the datasets:

```
tasks = mteb.get_tasks(tasks = ["LeCaRDv2"], exclude_superseeded=True) # default
len(tasks) # 1

tasks = mteb.get_tasks(tasks = ["LeCaRDv2"], exclude_superseeded=False)
len(tasks) # 2

task[0].metadata.name == task[1].metadata.name # True

# to differentiate between to two task:
task[0].is_superseeded_by # None
task[0].is_superseeded_by # ev
```

I believe we might have a test that disallows this (but we can always remove that) I also believe that there are a few places where we assume that the name is unique (e.g. in the TASK_REGISTRY).

fetching an older version then becomes harder (which maybe is encouraged?):

```
from mteb.tasks.Retrieval.zho.LeCaRDv2Retrieval import LeCaRDv2Retrieval
```

vs the newer:
```
from mteb.tasks.Retrieval.zho.LeCaRDv2Retrieval import LeCaRDv2RetrievalFast
# or
from mteb.tasks.Retrieval.zho.LeCaRDv2Retrieval import LeCaRDv2RetrievalWithoutDuplicates
# or
from mteb.tasks.Retrieval.zho.LeCaRDv2Retrieval import LeCaRDv2RetrievalMini
# or whatever it is named
```

This has the potential option that some might think they are running on "LeCaRDv2"(v1) but instead runs on "LeCaRDv2.v2". 

For benchmarks it is not too much of a problem as it is just a list of tasks.

**Comment by KennethEnevoldsen** [comment]
Just to update my comment I think @imenelydiaker suggestion is great

**Comment by KennethEnevoldsen** [comment]
I believe this is resolved. Feel free to reopen if it is not
