### ISSUE TITLE
Consolidate "convert_to_fast" methods in AbsTaskClusteringFast

### ISSUE THREAD

**Issue by isaac-chung** [embeddings-benchmark/mteb#834]
Currently there are
- `clustering_downsample`: used only by `ArxivClusteringP2P.v2`
- `convert_to_fast`: used only by `TenKGnadClusteringS2S.v2`
- `dataset_transform` from #660 

To make AbsTaskClusteringFast consistent, the proposal is to
1. consolidate into one `convert_to_fast` method that will be called in a dataset's `dataset_transform`. This new method will be refactored to use the logic from the 3rd points above.
2. rerun results for `ArxivClusteringP2P.v2` and `TenKGnadClusteringS2S.v2`

Aside: I've also compared the speed of using dataset filtering (e.g. in `HALClusteringS2S.v2`) vs the current method for filtering out single count labels in clustering datasets (e.g. in `BlurbsClusteringP2P.v2`). The former is 5x slower.
```
HALClusteringS2S.v2: 5.16 s ± 40.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
BlurbsClusteringP2P.v2: 1.03 s ± 39.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by KennethEnevoldsen** [comment]
One point here is that `clustering_downsample` it not intended to convert to fast, but rather just downsample "old-format" clustering tasks.

**Comment by isaac-chung** [comment]
Can those be effectively overwritten and replaced by the current version of fast-conversion?

**Comment by KennethEnevoldsen** [comment]
Not in all cases e.g. #828 where it is specified in the comment:

```
# a faster version of BlurbsClusteringP2P, since it does not sample from the same distribution we can't use the AbsTaskClusteringFast, instead we
# we simply downsample each cluster.
```

So clusters can be constructed e.g. using different labels

**Comment by isaac-chung** [comment]
But in #832 we followed the steps in #660 to convert Blurbs to use `AbsTaskClusteringFast`. Should we not have done that?

**Comment by KennethEnevoldsen** [comment]
So one cluster might do "genres" and another do "subgenres", which will lead the new dataset clustering at two different levels at the same time (worse cases include e.g. "newspaper source" and "news/sports/etc"). There might even be duplicates across these categories. I believe the conversion script that I made for one of the datasets specifically checks if the labels are the same across clusters.

**Comment by isaac-chung** [comment]
Got it. This check exists in `AbsTaskClusteringFast.convert_to_fast` ( used only in `TenKGnadClusteringS2SFast`) but not in `AbsTaskClusteringFast.clustering_downsample`. Other than manually checking every converted dataset in #660, is there a quicker way to know whether we've used the right method to convert them to fast?

i.e. if the dataset contains subsets (rows are lists), then should we have used `AbsTaskClusteringFast.convert_to_fast`, and not the method described in #660 ?

**Comment by x-tabdeveloping** [comment]
I honestly prefer to stay explicit in `dataset_transform`. The easier it is for newcomers to understand how we change the dataset they are working with, and the less places they have to look, the better.

**Comment by isaac-chung** [comment]
I think the issue here is about the "splits", i.e. having lists of examples as each row in the old clustering dataset format. Specifically, the check in [convert_to_fast](https://github.com/embeddings-benchmark/mteb/blame/4bded5a653a806d9068cfb9f246c86d75c3e4c55/mteb/abstasks/AbsTaskClusteringFast.py#L179)` does not seem to work, as `categories` will always be None and the assert will never be run. As a current state, none of the clustering datasets have gone through the distribution check. Instead, all splits were combined and examples are sampled without stratification. So what we did in #660 (to apply stratified subsampling) is a step better.

I see some options:
1) Fix `convert_to_fast` to actually check the distribution, keep it and apply to the converted datasets if it applies
2) Replace `convert_to_fast` with what we've been doing in #660

**Comment by KennethEnevoldsen** [comment]
I suppose just checking if the labels match across clusters in the original dataset is the best way to do it?

**Comment by isaac-chung** [comment]
@KennethEnevoldsen  This code is very similar to the one mentioned in my comment above. Since `labels` is always None, the first branch in the if/else is always taken. Am I missing obvious?
