### ISSUE TITLE
running baseline models

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#840]
We currently have run almost all tasks using the two baseline models. We might want to use these results, however, currently, we just use the e5 implementation from the sentence transformer (without query or corpus encode).

@Muennighoff would it be possible for you to run these two baseline models on the full set of MTEB? Replacing existing scores at least for e5 small. We can then replace the results in the `results/` folder with all the new results.

Side issue: should we record the system we are running on along with the evaluation speed? (I can add that if it is something that we want - it will make the results bigger but easier to compare speed)

(@imenelydiaker might be relevant for #838)

**Comment by Muennighoff** [comment]
Sure I can run that --- I assume we want to run them with the new model integration i.e. get_model? What should the script look like? (maybe we should put the scripts somewhere too)

**Comment by KennethEnevoldsen** [comment]
@Muennighoff I have tried to outline the code (I believe it should work) in #845. Sadly, my internet is a bit wonky (wifi on German ICE trains is nothing to write home about), so I haven't had a chance to test it yet.

@imenelydiaker and @isaac-chung, I would love your eyes on the approach as well (especially since I deleted all the previous results - I just checked if that is something we want?)

**Comment by isaac-chung** [comment]
Will take a look at the code. 
Is it worth reusing the results if we converted them?

**Comment by KennethEnevoldsen** [comment]
> Is it worth reusing the results if we converted them?

yea def. except for e5 (we would have to also fix the revision part). Also assuming that the task didn't change since it was ran. I am unsure how consistently people have been rerunning the tasks during development.

**Comment by imenelydiaker** [comment]
> Side issue: should we record the system we are running on along with the evaluation speed? (I can add that if it is something that we want - it will make the results bigger but easier to compare speed)

CO2 tracker can do this I think, we just need to save the info. 
 
We agreed that it's okay to run all evals on different machines, as we will provide a CO2 estimation of the experiments we ran for the paper only. And not a general estimation for the benchmark. The information about machines is a nice to have imo.

**Comment by KennethEnevoldsen** [comment]
Added an issue on adding system info here #848

**Comment by KennethEnevoldsen** [comment]
Will close this as it seems mostly done
