### ISSUE TITLE
Paper: Multilevel clustering and Multi clf

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#849]
We have to describe how we did it, along with explanations of stratification if it's something we want.

**Comment by x-tabdeveloping** [comment]
@dokato Would you be interested in helping me out writing a bit about stratification for multilabel tasks?

**Comment by dokato** [comment]
Yes, totally, I'll help!

**Comment by KennethEnevoldsen** [comment]
I belive this is added - will close
