### ISSUE TITLE
Use stratification in multilabel tasks.

### ISSUE THREAD

**Issue by x-tabdeveloping** [embeddings-benchmark/mteb#850]
Currently there are multiple multilabel tasks that use dummy or no subsampling leading to potentially unrealistic results.
We will soon have a PR merged that introduces multilabel stratification #760. And it would be very useful to convert all tasks to using this.

These are:
 - [ ] Hierarchical clustering tasks:
     - [ ] SNL
     - [ ] VG
     - [ ] ArXiv
     - [ ] Blurbs
 - [ ] Multilabel classification tasks:
     - [ ] MalteseNews
     - [ ] MultiEURLEX
     - [ ] BrazilianToxicTweets

**Comment by x-tabdeveloping** [comment]
@KennethEnevoldsen @imenelydiaker @orionw @isaac-chung @Muennighoff Is this something we want to get done quickly before running everything or should we just roll with things as they are?

**Comment by KennethEnevoldsen** [comment]
The current subsampling is just random. I don't believe it is a reason to convert them (at least for hierarchical), we can do it for new tasks.

**Comment by x-tabdeveloping** [comment]
Alright, I will close this then.
