### ISSUE TITLE
Handling model_meta.json in new results folder structure

### ISSUE THREAD

**Issue by isaac-chung** [embeddings-benchmark/mteb#860]
As we transition to use a new results folder structure in https://github.com/embeddings-benchmark/mteb/pull/842, we should consider saving revisions in `model_meta.json`. Specifically, Right now there's a field that we can potentially overwrite and append to as a list of revisions.
```
"versions": model._model_config.get("__version__", None)
```

The results folder would be:
```
results
|-- model name
  |-- model_meta.json
  |-- model revision
    |-- datasetA.json
```

I also wonder if `model_meta.json` is still needed, since #807 adds entries like `mteb/models/sentence_transformers_models.py`. Would love some thoughts on this @KennethEnevoldsen @imenelydiaker and whoever is interested.

**Comment by KennethEnevoldsen** [comment]
Looks good though, since we can have multiple revisions I would do it as such:

```
results
|-- model name
  |-- model revision
     |-- model_meta.json
     |-- datasetA.json

**Comment by isaac-chung** [comment]
Sounds good to me

**Comment by isaac-chung** [comment]
It seems like there will be duplicate information in 1) `model_meta.json` and 2) files like `mteb/models/sentence_transformers_models.py`. Are files in `mteb/models` meant for a different purpose? Maybe we could consolidate the two?

**Comment by KennethEnevoldsen** [comment]
I believe they should at least be compatible

`mteb/models/sentence_transformers_models.py`, can essentially be autogenerated, with a few exceptions - we might change mteb.get_model(...) to just use sentence transformer by default and then we can use mteb.get_model_meta(...) to automatically create the metadata. However, for models like e5, it also adds a loader for how the model is run.

**Comment by KennethEnevoldsen** [comment]
@isaac-chung I believe we have resolved this issue in the latest couple of PRs
