### ISSUE TITLE
Having inference or evaluation results

### ISSUE THREAD

**Issue by jihyukkim-nlp** [embeddings-benchmark/mteb#87]
Hi all, 
thank you for sharing this awesome repo!

I am having experiments on classification tasks.
I am wondering if the inference results (e.g., predicted class for each test sentence) and evaluation results (e.g., whether predicted class for each test sentence is correct) are available via some commands?

Best regards,
Jihyuk

**Comment by Muennighoff** [comment]
Hey, currently the package only reports aggregated results.
But you can simply print / write out the `y_test` & `y_pred` variables in https://github.com/embeddings-benchmark/mteb/blob/76dc3637ed2b49d0c182e0fff762a6d5cad37105/mteb/evaluation/evaluators/ClassificationEvaluator.py#LL106C39-L106C59

Let me know if this works!

**Comment by jihyukkim-nlp** [comment]
It works! Thanks!
