### ISSUE TITLE
scripts/mteb_meta.py does not work with the latest version

### ISSUE THREAD

**Issue by tobiaskungenlu** [embeddings-benchmark/mteb#875]
Evaluation results files (.json) have a different format in "mteb_version": "1.11.0" compared to "mteb_version": "1.10.1". The scripts/mteb_meta.py seems to only work for the older format.

**Comment by KennethEnevoldsen** [comment]
Thanks @tobiaskungenlu I believe this is a known error (but something that we have to fix). I believe the plan is to transition to using a CLI which we can also test continuously to avoid these issues.  

If you have the time we would very much welcome the a PR for a quick fix

**Comment by KennethEnevoldsen** [comment]
@tobiaskungenlu we have now implemented a new CLI which you can find more about here:

https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_model.md

I believe this should solve your issues
