### ISSUE TITLE
CodeSearchNet task

### ISSUE THREAD

**Issue by Rabrg** [embeddings-benchmark/mteb#88]
would the maintainers be interested in the addition of a code retrieval task ([CodeSearchNet](https://wandb.ai/github/CodeSearchNet/benchmark), uses text queries to retrieve code documents), either as a new code retrieval type or added into the existing retrieval category?

**Comment by Muennighoff** [comment]
> would the maintainers be interested in the addition of a code retrieval task ([CodeSearchNet](https://wandb.ai/github/CodeSearchNet/benchmark), uses text queries to retrieve code documents), either as a new code retrieval type or added into the existing retrieval category?

Yes definitely! I think it would be best to add it to the existing retrieval category if possible. It would require some changes in the code to differentiate between BEIR and non-BEIR, but should not be too difficult.

The language splits would then be the coding languages go, java etc.

Do you want to tackle this? Very happy to help along the way! 🤗

**Comment by Rabrg** [comment]
i haven't gotten around to this yet, but would be happy to give it a shot

**Comment by Muennighoff** [comment]
> i haven't gotten around to this yet, but would be happy to give it a shot

Amazing! Let me know when you run into problems 👍

**Comment by Muennighoff** [comment]
I think @bwanglzu & team have also been working on this - Let us know if we can help in any way!

**Comment by Manouchehri** [comment]
Oh nice! Is there a fork or WIP script anywhere?

**Comment by bwanglzu** [comment]
hi @Muennighoff, @Manouchehri  and all, yes we're working on this. Maybe a bit more, we'll add ~3 coding tasks to MTEB :)

**Comment by Muennighoff** [comment]
> hi @Muennighoff, @Manouchehri and all, yes we're working on this. Maybe a bit more, we'll add ~3 coding tasks to MTEB :)
> 
> reason behind this is we're training a coding embedding model, similar as: [jina-embeddings-v2](https://huggingface.co/jinaai/jina-embeddings-v2-base-en) :)

Amazing really looking forward to it! Let us know if we can help :)

**Comment by cassanof** [comment]
Hello everyone! I'll be working on getting this integrated :hugs:
