### ISSUE TITLE
Make search case-insensitive

### ISSUE THREAD

**Issue by paulmis** [embeddings-benchmark/mteb#889]
Model search is case-sensitive, e.g. typing `titan` vs `Titan` yields different results (only v1 and only v2 respectively). Make the search case-insensitive.

![Screenshot 2024-06-06 at 22 43 18 (1)](https://github.com/embeddings-benchmark/mteb/assets/45182027/f6331ba1-9489-4044-967b-d48cb393e580)
<img width="1262" alt="Screenshot 2024-06-06 at 22 46 18" src="https://github.com/embeddings-benchmark/mteb/assets/45182027/55254d2d-5985-4920-bdaf-1f51ccf76a8f">

**Comment by KennethEnevoldsen** [comment]
Thanks for this @paulmis. 

@Muennighoff and @tomaarsen I don't see any problems in making it case-insensitive. Let me know if you guys agree

**Comment by tomaarsen** [comment]
That seems fine, yeah. Implemented and merged it with the leaderboard:
![image](https://github.com/embeddings-benchmark/mteb/assets/37621491/68b686fa-8848-4d5b-9bf2-9cd5902e94a3)

Thanks for the suggestion @paulmis.

- Tom Aarsen
