### ISSUE TITLE
paper writing;: table overview of tasks

### ISSUE THREAD

**Issue by KennethEnevoldsen** [embeddings-benchmark/mteb#897]
see https://github.com/embeddings-benchmark/mteb/discussions/595#discussioncomment-9467714

**Comment by KennethEnevoldsen** [comment]
Assigned to @ Sakshamrzt

**Comment by Sakshamrzt** [comment]
<img width="532" alt="Screenshot 2024-06-17 at 1 59 54 PM" src="https://github.com/embeddings-benchmark/mteb/assets/68951147/0b4dfc6f-e768-4864-8f5e-f5c8faba8c41">

@KennethEnevoldsen Having a lang column seems necessary but it could lead to issues like above. What do you think should be done here?

**Comment by KennethEnevoldsen** [comment]
Ahh yea that seems a bit frustrating. A solution would be to reduce it to ["acm", "afr", "als", ...], with a maximum on n=10 languages. This does not convey the size though. So would add a column with the number or something like 

```
N. Languages
---
107 ("acm", "afr", "als", ...)
```

**Comment by Sakshamrzt** [comment]
Sounds good!

**Comment by KennethEnevoldsen** [comment]
Had a look at the table. Looking good so far! 

A few suggestions at which point I think we are getting there)
- introduce a space between name and citation
- make the text smaller (size the table is quite large) e.g. [see](https://tex.stackexchange.com/questions/111765/problem-with-fontsize-when-using-longtable) - ideally no more than 2 lines pr. dataset.
- Move the table to appendix D (though that should probably be moved to be the last appendix). We should also add a small introduction here as well as long with a reference to the table on docs (which includes the description).
- I would add a parenthesis around the language)
- remove decimals from N. Docs, as well as reduce the avg. length decimals to 1.
- We will probably need to add in the size for the cases where it is missing
- there is one citation that does render properly

**Comment by KennethEnevoldsen** [comment]
Will close this issue for now. the MTEBTasks object now has a to_latex function
