### ISSUE TITLE
Evaluating New Embeddings

### ISSUE THREAD

**Issue by rlyCarlson** [embeddings-benchmark/mteb#90]
I understand that standard word embeddings (like average_word_embeddings_glove.6B.300d) are downloaded from hugging face, but is there code to evaluate new embeddings? I have a .txt file with vectors trained with the GloVe model that I would like to evaluate. 

I see in the documentation that we can write our own encoder model that can be evaluated. But is there a way to only input a .txt file of the word embeddings for evaluation? 

If there is no code to support a .txt file input, then for the encoder, is the input `sentences` tokenized already?

**Comment by Muennighoff** [comment]
> I have a .txt file with vectors trained with the GloVe model that I would like to evaluate.

Hey! The input is not tokenized, so in your case you could write something like this:

```python
class MyModel():
    def encode(self, sentences, batch_size=32, **kwargs):
        """ Returns a list of embeddings for the given sentences.
        Args:
            sentences (`List[str]`): List of sentences to encode
            batch_size (`int`): Batch size for the encoding

        Returns:
            `List[np.ndarray]` or `List[tensor]`: List of embeddings for the given sentences
        """
        with open("MYTXTFILE.txt", "r") as f:
            vectors = f.read() # Probably something more complex
        # Maybe your tokenization is more complex than space splitting
        emb = [vectors[token] for text in sentences for token in text.split(" ")]
        return emb

model = MyModel()
evaluation = MTEB(tasks=["Banking77Classification"])
evaluation.run(model)
```

**Comment by rlyCarlson** [comment]
What is the right approach for non contextual embeddings? I used the code skeleton you provided (thank you!) to return an embedding for each word in the sentence, but I am not able to run the evaluations because I run into inconsistent array shapes.

**Comment by Muennighoff** [comment]
> What is the right approach for non contextual embeddings? I used the code skeleton you provided (thank you!) to return an embedding for each word in the sentence, but I am not able to run the evaluations because I run into inconsistent array shapes.

The function should return something of shape (num_sentences, embedding_dim), i.e. one embedding per sentence.

Normally, non-contextual embeddings include a pooling layer to make the output independent of text length. The pooling layer could e.g. be averaging the embeddings across all words. Else you could also look into padding the embeddings.

**Comment by KennethEnevoldsen** [comment]
@rlyCarlson seems like this issue has gone stale. I will close it for now, but feel free to reopen it.
