### ISSUE TITLE
Changes in metadata broke backward compat of metric name

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#903]
The metric name for STS & co changed in the metadata as previously it was created via merging the `cos_sim` & `spearman` names i.e. https://github.com/embeddings-benchmark/mteb/blob/2cc222efd84c29cbb5ff04fb8e6703674d53dda9/scripts/mteb_meta.py#L113 and now it is defined as `cosine_spearman` i.e. https://github.com/embeddings-benchmark/mteb/blob/b16d7d5620b987992e16ee663e5d82ee007acd8e/mteb/tasks/STS/eng/BiossesSTS.py#L21C21-L21C36 which is then taken as is i.e. https://github.com/embeddings-benchmark/mteb/blob/b16d7d5620b987992e16ee663e5d82ee007acd8e/mteb/cli.py#L265

For old models like https://huggingface.co/w601sxs/b1ade-embed it was called `cos_sim_spearman`.
For new models like https://huggingface.co/w601sxs/b1ade-embed-kd_3 it is now called `cosine_spearman`.

This now breaks the leaderboard as people are starting to submit with the new metric name but the old one is asked for in the code via https://huggingface.co/spaces/mteb/leaderboard/blob/a812c3bbcc3cd88510b60c6c5788d95668d69dc6/config.yaml#L38 which is then used to get the scores via 
 https://huggingface.co/spaces/mteb/leaderboard/blob/a812c3bbcc3cd88510b60c6c5788d95668d69dc6/app.py#L245

Same will happen for PairClassification and others I think. 🤔

Options are:
1) Allow both metric names; Requires some changes to the leaderboard code
2) Revert `cosine_spearman` to `cos_sim_spearman` & others
3) Maybe sth else reasonable that I'm missing?

Not sure what's best, cc @KennethEnevoldsen & @tomaarsen who probably know better! 🙌

**Comment by KennethEnevoldsen** [comment]
1 and 2 both work I am up for either. Assuming that some models might in the future use their own similarity metric we might want to allow for that. E.g. use "similarity_spearman" instead? (and then the "similarity" is defined by the model but defaults to "cosine"

**Comment by Muennighoff** [comment]
Are there any notable models thus far that have a similarity metric that is not native in MTEB anyways (i.e. cosine, dot & co)?

Another big difference is that previously the metadata would include all metrics which is nice in case someone wants to fetch different scores, while now it only includes the main score? I think we want to revert this, no?

**Comment by Muennighoff** [comment]
Maybe we want to add a test that checks that the metadata generation is working to prevent such issues in the future? 🤔

**Comment by KennethEnevoldsen** [comment]
> Are there any notable models thus far that have a similarity metric that is not native in MTEB anyways (i.e. cosine, dot & co)?

Binary still uses cosine? (then I don't think so). It is simply from the perspective of limiting modeling.

> Another big difference is that previously the metadata would include all metrics which is nice in case someone wants to fetch different scores, while now it only includes the main score? I think we want to revert this, no?

All metrics are totally doable, we can totally add that in.

> Maybe we want to add a test that checks that the metadata generation is working to prevent such issues in the future? 🤔

Def.! A test will solve this going forward (I actually added a test based on the example in the readme of the previous script, but I can see that it is not comprehensive).

So a solution would be:

1) Convert `cosine_spearman` > `cos_sim_spearman`

We can optionally add `similarity_spearman` which uses the model's custom similarity, without breaking compatibility. At a later stage we might want to change the main metric while still calculating cosine (might e.g. be interesting for vector databases, which can be limited to online certain metrics)

2) Add in all scores in the metadata 

3) Update the test to reflect compatibility with previous results (do you have a gold standard + results that lead to it)

**Comment by Muennighoff** [comment]
1. Seeing https://github.com/embeddings-benchmark/mteb/issues/885 it makes sense to me that you want to separate similarity measure and metric. Indeed, maybe there should be a tab on the leaderboard similar to `Max Tokens` that says what similarity metric a model uses and we switch to defining similarity metrics at the model, not dataset/task level 🤔
Maybe having: `spearman` (uses default similarity metric) ; `cosine_spearman` ; `dot_spearman` etc?
(I don't have a preference for `cos_sim_spearman` over `cosine_spearman`; I think `cosine_spearman` is fine, similar to how we don't say `dot_prod_spearman`)

2. Sounds good
3. Should we just take some result files of different formats from https://huggingface.co/datasets/mteb/results?

**Comment by achibb** [comment]
two things to add for creating metadata: 

hf gives trouble because the create meta calls it "metric" and not "metrics". and also it must be an array so instead of:

type: ...
value: ...

it needs to be
- type: ...
value


then it seems to work :-)

**Comment by Muennighoff** [comment]
> two things to add for creating metadata:
> 
> hf gives trouble because the create meta calls it "metric" and not "metrics". and also it must be an array so instead of:
> 
> type: ... value: ...
> 
> it needs to be
> 
> * type: ...
>   value
> 
> then it seems to work :-)

Thanks for finding that! Do you want to open a PR to fix it & the other issues mentioned here? Would be amazing 🙌

**Comment by KennethEnevoldsen** [comment]
I have added a pr #931
