### ISSUE TITLE
Integrate MINERS

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#907]
Amazing work by @gentaiscool on [MINERS](https://arxiv.org/abs/2406.07424)! I think it'd be really nice to allow people to evaluate MINERS in MTEB, too. Let me know if you @gentaiscool or someone else is interested in integrating it 🙌  I think this one is very high priority given its multilinguality for MMTEB (https://github.com/embeddings-benchmark/mteb/tree/main/docs/mmteb)!

**Comment by gentaiscool** [comment]
Hello @Muennighoff, thank you for initiating the issue and suggesting the idea. Is the MMTEB project still ongoing or has it been completed? I think integrating MINERS into MMTEB would be a valuable addition.

**Comment by Muennighoff** [comment]
> Hello @Muennighoff, thank you for initiating the issue and suggesting the idea. Is the MMTEB project still ongoing or has it been completed? Happy to contribute to the benchmark if you are still looking for contributors. I think integrating MINERS into MMTEB would be a valuable addition.

Agree that it'd be very valuable! I think we can still add it with points & co so you can join the MMTEB paper if you want; wdyt @KennethEnevoldsen?

**Comment by gentaiscool** [comment]
yes, I am happy to be added to the paper and I can work on the integration.

**Comment by KennethEnevoldsen** [comment]
I think that sounds great! MMTEB is still ongoing, the hope is to have an arxiv article sometime this summer. 

I Would be more than happy to review a PR and would be more than fine adding contributions points for it (we have generally stopped it, but I believe that a few cases such as this one more than justify it)

**Comment by gentaiscool** [comment]
I have started to create a PR https://github.com/embeddings-benchmark/mteb/pull/910 for NusaX. I will add more datasets.

**Comment by gentaiscool** [comment]
I created a new PR https://github.com/embeddings-benchmark/mteb/pull/914 for NusaTranslation Bitext Mining.

**Comment by gentaiscool** [comment]
I have completed the checklists https://github.com/embeddings-benchmark/mteb/pull/910 https://github.com/embeddings-benchmark/mteb/pull/914 https://github.com/embeddings-benchmark/mteb/pull/915. @KennethEnevoldsen

**Comment by gentaiscool** [comment]
Add another one https://github.com/embeddings-benchmark/mteb/pull/927 (it was derived from the dataset I used in MINERS).

**Comment by KennethEnevoldsen** [comment]
All PRs are merged @gentaiscool do you want to create an MINER benchmark and then we can close this issue?

**Comment by gentaiscool** [comment]
> All PRs are merged @gentaiscool do you want to create an MINERS benchmark and then we can close this issue?

Hi @KennethEnevoldsen, thank you for reviewing the datasets. I tried to incorporate the datasets used in MINERS to the existing tasks in MMTEB, instead of creating a new task solely only for MINERS. I have integrated most of the monolingual / multilingual datasets, except the code-switching ones, which I am not sure how to configure the languages in the benchmark (e.g., if the language is hinglish, it has both Hindi and English). If you have the solution for this, I am happy to add them. Otherwise, we can close the issue.

**Comment by KennethEnevoldsen** [comment]
Oh, we should totally add the code-switching ones! Have been looking forward to seeing some of those.

So, a dataset on MTEB can have two forms of language annotations:

```
# a dict
eval_langs = {"en": ["eng_Latn"]} # "en" is the HuggingFace subset
# or a list
eval_langs = ["eng_Latn"]
# which under the hood translates to:
eval_langs = {"default": ["eng_Latn"]}
```
However, as we use a list for all of the annotations, they can just as well be two languages (e.g. seen in the language identification tasks or in the bitext tasks)

Thus Danglish (Danish+English) would be:
```
eval_langs = {"default": ["eng_Latn", "dan_Latn"]}
```
This, however, only notes that the dataset contains two languages, not how/why it does it. I would just specify this in the description, but we have previously debated using

```
eval_langs = {"default": LanguagePair("eng_Latn", "dan_Latn")} # for bitext
eval_langs = {"default": UnknownLanguage("eng_Latn", "dan_Latn")} # for language identification
eval_langs = {"default": CodeSwitching("eng_Latn", "dan_Latn")} # for code-switching
```
We have had no use for these yet though, so we haven't implemented them. I don't think it is needed here, but if you want to add it, feel free to go ahead. I believe you just need to do:

```
class CodeSwitching(list):
  pass
  
CodeSwitching(lang1, lang2, ....)
```

**Comment by gentaiscool** [comment]
@KennethEnevoldsen thank you for your explanation and suggestion. I think I can work on adding the code-switching datasets, and also preparing a collection of datasets / tasks as MINERS benchmark.

**Comment by gentaiscool** [comment]
@KennethEnevoldsen I have a special case for bitext code-switching data where the source language is a (English-Malayalam) and the target is another code-switching language (English-Tamil).

**Comment by gentaiscool** [comment]
Added 2 code-switching bitext mining datasets:
https://github.com/embeddings-benchmark/mteb/pull/947 and https://github.com/embeddings-benchmark/mteb/pull/948

**Comment by gentaiscool** [comment]
Adding the PR for bitext retrieval benchmark https://github.com/embeddings-benchmark/mteb/pull/951

**Comment by gentaiscool** [comment]
thank you for reviewing the PRs @KennethEnevoldsen. Currently, we have covered the MINERS bitext mining benchmark, and we still can get the benefit for the classification benchmark. And, I might need more time to compile the datasets. Probably, we can close this issue for now and if I have the time to prepare the dataset, I will just create the PRs.

**Comment by KennethEnevoldsen** [comment]
Wonderful will close this issue then
