### ISSUE TITLE
How to customize parameters for AbsTaskClassification

### ISSUE THREAD

**Issue by jihyukkim-nlp** [embeddings-benchmark/mteb#91]
Hi all,

I would like to compare varying configurations for `AbsTaskClassification`.
For example, I am wondering about evaluation results with `method=kNN`.
But, I am not sure how can I change those parameters in python scripts.
Could you help me with this?

* BTW, I am wondering which method was used for the performance presented in the paper/leaderboard, between `method=kNN` (as described in the paper; 3.2 Tasks and evaluation - Classification) and `method=logReg` (which is the default value for method param in the codes).

Best regards,
Jihyuk

**Comment by Muennighoff** [comment]
**1]** You can set the method to `kNN` like below:
```python
from mteb import MTEB
from sentence_transformers import SentenceTransformer

# Define the sentence-transformers model name
model_name = "all-MiniLM-L6-v2"

model = SentenceTransformer(model_name)
evaluation = MTEB(tasks=["ImdbClassification"], method="kNN")
results = evaluation.run(model, output_folder=f"results/{model_name}")
```
There's a small bug for multiclassification datasets like `Banking77Classification`, which is fixed here: https://github.com/embeddings-benchmark/mteb/pull/92. You may want to install from that branch / adapt the few lines of code it changes in your install if you intend to run multiclassification. Will try to merge it soon!



**2]** The default is `logReg` & all results in the paper/leaderboard use `logReg`. We will adjust section 3.2 & write logReg instead! Thanks for pointing this out 🤗

**Comment by jihyukkim-nlp** [comment]
Thank you for detail information and clarification!
