### ISSUE TITLE
Testing issue (probably bug)

### ISSUE THREAD

**Issue by gentaiscool** [embeddings-benchmark/mteb#916]
I found two issues:
1. I got an error when running `make test`
`===================================================== short test summary info =====================================================
FAILED tests/test_RerankingEvaluator.py::TestRerankingEvaluator::test_nAUC - assert 0.9406528189910982 == 0.86943 ± 8.7e-05`

2. I also got an error when running `mteb -m {model_name} -t {task_name}` using the cli for `intfloat/multilingual-e5-small` from the `main` branch.
e.g., `mteb -m intfloat/multilingual-e5-small -t FloresBitextMining`

`ValueError: Model None not found for model intfloat/multilingual-e5-small`

I was wondering if anyone is facing the same issue or know a workaround if I missed anything. Thank you.
cc @Muennighoff @KennethEnevoldsen

**Comment by Muennighoff** [comment]
Hm maybe we should add more tests, as there should be no errors given the latest commit passed all tests (https://github.com/embeddings-benchmark/mteb/commit/a3b556e7cafddd1c88eb6462fa9ac9247dff1623) 🤔

**Comment by gentaiscool** [comment]
Somehow I rerun the code on different machine (with python 3.10.14) with V100 and it worked. Previously I ran on python 3.10.12 with A10 machine. And, for E5 model, the issue persists, I couldn't find the model when I ran the cli command.

**Comment by gentaiscool** [comment]
thank you @KennethEnevoldsen. We can close this issue.
