### ISSUE TITLE
Remove CrosslingualTask & MultilingualTask?

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#933]
https://github.com/embeddings-benchmark/mteb/blob/main/mteb/abstasks/CrosslingualTask.py & https://github.com/embeddings-benchmark/mteb/blob/main/mteb/abstasks/MultilingualTask.py are essentially the same thing and the `is_crosslingual` & `is_multilingual` attributes are only used to change the console color I think 🤔 

In the spirit of reducing complexity & keeping it simple I think we can:
(a) Merge them into just `MultilingualTask`
(b) Remove both - I don't think we need these classes, as checking whether a task is multilingual should be as simple as `len(self.metadata_dict["eval_langs"]) > 1`. But maybe we don't even need that check - ideally it just works out of the box with multilingual or monolingual I think by just iterating through whatever languages are there? We have already standardized the format for that (https://github.com/embeddings-benchmark/mteb/issues/251#issuecomment-2036569253) I think 🤔

Curious if @KennethEnevoldsen has thoughts!

**Comment by KennethEnevoldsen** [comment]
Yeah, I think you are right; we could just factor these out. It would require some work, though. I think it could be done in two steps. 1) replace CrossLingual with Multilingual and 2) factor Multilingual into Abstask.
