### ISSUE TITLE
Policy on machine translated datasets

### ISSUE THREAD

**Issue by emrecncelik** [embeddings-benchmark/mteb#935]
What is the exact policy on machine translated datasets? Can we add datasets that are proven to have good quality translations?

Guide for adding datasets states,

> "Note that these fields can be left blank if the information is not available and can be extended if necessary. We do not include any machine-translated _(without verification)_ datasets in the benchmark."

What does "without verification" entail? Is it enough to have good quality translations approved by annotators? In order to provide a concrete example we can take a look at [NLI-tr](https://arxiv.org/abs/2004.14963). Authors state the following,

> "Overall, it seems that the very high estimates of translation quality and label consistency of NLI-TR are trustworthy, and only a small percentage of premise–hypothesis have inconsistent semantic labels between their original and translated forms."
> 
> "However, such examples seem to be rare and so pose minimal risk for conducting research using NLI-TR."

Here is a table from the paper for translation quality,
![Capture](https://github.com/embeddings-benchmark/mteb/assets/20845117/6aa2d2e2-1130-4516-ad10-be9a8c910021)

Does this and similar others count as verification?

Thank you.

**Comment by KennethEnevoldsen** [comment]
When I wrote it, verification I meant verified by a human who speaks the language.

That being said, there is def. degrees of verification, and what you propose would be accepted as verification (I would at least accept it).

It should be noted, however, that if you wish to contribute to MMTEB, we no longer give points for dataset additions (with a few exceptions for high-quality dataset additions), as we have exceeded the dataset contribution phase. However, we still accept and review PRs for datasets.

**Comment by emrecncelik** [comment]
Thank you for the clarification and the prompt reply! Turkish is lacking a lot in terms of benchmarking embeddings and that makes it difficult to develop quality models, so I'll try to contribute.

**Comment by KennethEnevoldsen** [comment]
Türkish seems fairly well covered or at least covered enough such that a benchmark could be constructed from this:

| Name | Type | Domain | Text creation |
| --- | --- | --- | --- |
| BibleNLPBitextMining | BitextMining | ['Religious'] | created |
| FloresBitextMining | BitextMining | ['Non-fiction', 'Encyclopaedic'] | created |
| NTREXBitextMining | BitextMining | ['News'] | human-translated and localized |
| Tatoeba | BitextMining | [] | found |
| LanguageClassification | Classification | ['Reviews', 'Web', 'Non-fiction', 'Fiction', 'Government'] | found |
| MassiveIntentClassification | Classification | None | None |
| MassiveScenarioClassification | Classification | None | None |
| MultilingualSentimentClassification | Classification | ['Reviews'] | found |
| SIB200Classification | Classification | ['News'] | human-translated and localized |
| TurkishMovieSentimentClassification | Classification | ['Reviews'] | found |
| TurkishProductSentimentClassification | Classification | ['Reviews'] | found |
| BelebeleRetrieval | Retrieval | ['Web', 'News'] | created |
| XQuADRetrieval | Retrieval | ['Web'] | created |
| TurHistQuadRetrieval | Retrieval | ['Encyclopaedic', 'Non-fiction', 'Academic'] | found |
| XNLI | PairClassification | ['Non-fiction', 'Fiction', 'Government'] | created |
| XNLIV2 | PairClassification | ['Non-fiction', 'Fiction', 'Government'] | machine-translated and verified |
| STS17 | STS | None | None |
| STS22 | STS | None | None |
| SIB200ClusteringFastS2S | Clustering | ['News'] | human-translated and localized |


produced using:

```
import mteb

tasks = mteb.get_tasks(languages=["tur"])

print("| Name | Type | Domain | Text creation |")
print("| --- | --- | --- | --- |")
for task in tasks:
    # print(tasks.metadata.name + " - " + tasks.metadata.type + " | " + tasks.metadata.domain)
    print(f"| {task.metadata.name} | {task.metadata.type} | {task.metadata.domains} | {task.metadata.text_creation} |")
```
