### ISSUE TITLE
Convergence warning on classification tasks

### ISSUE THREAD

**Issue by ShengYun-Peng** [embeddings-benchmark/mteb#944]
Models I used:
- model = SentenceTransformer("google-bert/bert-base-uncased")

Warnings I got:
ConvergenceWarning: lbfgs failed to converge (status=1): STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.
Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

Is this expected?

**Comment by KennethEnevoldsen** [comment]
I don't usually see it no, but it can def. happen. We limit the number of steps to avoid too much time spent during the logistic function (we really want the embedding to be the main component here).

I would suspect it happens more with models not tuned for document embeddings (e.g. bert).

Also, note that a failure to converge does not nec. mean that the fit is bad.

**Comment by ShengYun-Peng** [comment]
Thanks, @KennethEnevoldsen! You are right! Even if the warning pops up, I can still reproduce the number of bert on the official benchmark.
