### ISSUE TITLE
GritLM not using instructions

### ISSUE THREAD

**Issue by Muennighoff** [embeddings-benchmark/mteb#973]
I think that GritLM is not using instructions atm - https://github.com/embeddings-benchmark/mteb/blob/main/mteb/models/gritlm.py vs https://github.com/ContextualAI/gritlm/tree/main?tab=readme-ov-file#inference

**Comment by KennethEnevoldsen** [comment]
No I believe you are right. You might have to wrap gritLM's encode to convert the "prompt_name" argument to instructions.
