### ISSUE TITLE
create-table fails

### ISSUE THREAD

**Issue by isaac-chung** [embeddings-benchmark/mteb#975]
The create-table workflow calls `make install` and fails as GPUtil is not installed.

Should we
1. update Makefile to use `pip install -e ".[dev, speedtask]"` for `make install`, or
2. update the workflow to use `make install-for-tests` ?

**Comment by KennethEnevoldsen** [comment]
It greatly simplified installation just to have one workflow so I would go for (1).

**Comment by isaac-chung** [comment]
@KennethEnevoldsen yes you're right. Just checked out that branch, uninstalled `GPUtil`, and ran `python docs/create_tasks_table.py` without errors.
