### ISSUE TITLE
Incorrect logic when retrieval top-k

### ISSUE THREAD

**Issue by thangylvp** [embeddings-benchmark/mteb#978]
I think the logic in this line is incorrect.
The corpus_id and query_id are not relevant, so even if corpus_id == query_id, it is still correct.
Can anybody explain the logic in here?

https://github.com/embeddings-benchmark/mteb/blob/0e58e52afad1241933f5cb310613a8e98749afc5/mteb/evaluation/evaluators/RetrievalEvaluator.py#L183C1-L184C1

**Comment by imenelydiaker** [comment]
This was resolved in PR #642 and #833. The retrieval used to compute self-retrieval metrics by default. 
See these comments for more details: https://github.com/embeddings-benchmark/mteb/pull/642#issuecomment-2098830205 and https://github.com/embeddings-benchmark/mteb/pull/642#issuecomment-2104947181
