### ISSUE TITLE
GPUtil is optional but required by default

### ISSUE THREAD

**Issue by imenelydiaker** [embeddings-benchmark/mteb#983]
`GPUtil` is an optional dependency although when installing mteb only (`pip install mteb`) and importing it seems to be required (see screenshot below). 

![image](https://github.com/embeddings-benchmark/mteb/assets/33312980/4a267519-b44e-4c67-a039-f7f0d3767f02)

cc @isaac-chung @KennethEnevoldsen

**Comment by isaac-chung** [comment]
Good catch!
