### ISSUE TITLE
Discrepancy in Score Ranges Between Metadata and Leaderboard in MTEB

### ISSUE THREAD

**Issue by omarnj-lab** [embeddings-benchmark/mteb#991]
It appears that the scores I got in the metadata range from 0 to 1, whereas the scores on the leaderboard range from 0 to 100. I have followed the instructions carefully and encountered this issue with all models I tried. I believe the metadata results from MTEB might be causing this discrepancy. Any help in this regard would be appreciated.

**Comment by imenelydiaker** [comment]
Scores in the leaderboard are multiplied by 100.

**Comment by omarnj-lab** [comment]
I know this is why I open this issue for, metadata I got ranging from 0 to 1 which is produced by MTEB.. I am wondering why !

**Comment by KennethEnevoldsen** [comment]
I suppose it is because 0-1 is easier to analyze (the goal of the json file) while 0-100 is easier to read (the goal of the leaderboard).

**Comment by Muennighoff** [comment]
We previously multiplied them by 100 for the metadata:
https://github.com/Muennighoff/mteb/blob/7a8398f016bb5ed1a83b15910bec597aec533222/scripts/mteb_meta.py#L111

It seems like in one of the recent changes, this got lost and they are no longer multiplied by 100 (e.g. this one should have them multiplied by 100 - https://github.com/embeddings-benchmark/mteb/blob/main/tests/create_meta/model_card_gold.md) 🤔

Let's multiply them by 100 again? It makes them much easier to view in the model sidebar; other reasons are explained here: 
https://github.com/Muennighoff/mteb/blob/7a8398f016bb5ed1a83b15910bec597aec533222/scripts/mteb_meta.py#L106

Thanks for raising this @omarnj-lab - i should have noticed this earlier 😅

**Comment by omarnj-lab** [comment]
Thanks for replying .. I will try the meter_meta.py since it solves the issue

**Comment by Muennighoff** [comment]
Sure; you can also just check the current metadata creation and just add *100 in the right place - should be very easy to do (feel free to open a PR if so; would be great!)

**Comment by omarnj-lab** [comment]
Great .. checking that as well !

**Comment by Muennighoff** [comment]
I think we should close this after we've merged a PR (or decided to stick with the format as is) - it's a very important issue you opened I think 👍

**Comment by KennethEnevoldsen** [comment]
Ahh right here it should be 100 for the meta file def. - I have added a PR in #993
