### ISSUE TITLE
extracting embedding from other than CLS token during eval mteb

### ISSUE THREAD

**Issue by riyajatar37003** [embeddings-benchmark/mteb#999]
Hi,

Where exactly i need to made changes in order to use the other tokens representation as embedding instead of 'cls' token?

can u point out to the file?

thanks

**Comment by malteos** [comment]
You can change that in the config file of the corresponding sentence transformers model, e.g., [here](https://huggingface.co/malteos/scincl/blob/main/1_Pooling/config.json#L3-L8).

**Comment by KennethEnevoldsen** [comment]
You might also take a look at the documentation for how to use a [custom model](https://github.com/embeddings-benchmark/mteb?tab=readme-ov-file#using-a-custom-model).

**Comment by isaac-chung** [comment]
Closing this now. Feel free to reopen if there are further questions.
